// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v3.19.4
// source: apollo.proto

package apollo

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	Passkeys_StartRegistration_FullMethodName  = "/apollo.Passkeys/StartRegistration"
	Passkeys_FinishRegistration_FullMethodName = "/apollo.Passkeys/FinishRegistration"
	Passkeys_StartLogin_FullMethodName         = "/apollo.Passkeys/StartLogin"
	Passkeys_FinishLogin_FullMethodName        = "/apollo.Passkeys/FinishLogin"
)

// PasskeysClient is the client API for Passkeys service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// ================= 服务定义 =================
type PasskeysClient interface {
	// 注册
	// StartRegistration 注册第一步 - 开始
	StartRegistration(ctx context.Context, in *StartRegistrationReq, opts ...grpc.CallOption) (*StartRegistrationResp, error)
	// FinishRegistration 注册第二步 - 完成
	FinishRegistration(ctx context.Context, in *FinishRegistrationReq, opts ...grpc.CallOption) (*FinishRegistrationResp, error)
	// 登录
	// StartLogin 登陆第一步 - 开始
	StartLogin(ctx context.Context, in *StartLoginReq, opts ...grpc.CallOption) (*StartLoginResp, error)
	// FinishLogin 登陆第二步 - 完成
	FinishLogin(ctx context.Context, in *FinishLoginReq, opts ...grpc.CallOption) (*FinishLoginResp, error)
}

type passkeysClient struct {
	cc grpc.ClientConnInterface
}

func NewPasskeysClient(cc grpc.ClientConnInterface) PasskeysClient {
	return &passkeysClient{cc}
}

func (c *passkeysClient) StartRegistration(ctx context.Context, in *StartRegistrationReq, opts ...grpc.CallOption) (*StartRegistrationResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(StartRegistrationResp)
	err := c.cc.Invoke(ctx, Passkeys_StartRegistration_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *passkeysClient) FinishRegistration(ctx context.Context, in *FinishRegistrationReq, opts ...grpc.CallOption) (*FinishRegistrationResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(FinishRegistrationResp)
	err := c.cc.Invoke(ctx, Passkeys_FinishRegistration_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *passkeysClient) StartLogin(ctx context.Context, in *StartLoginReq, opts ...grpc.CallOption) (*StartLoginResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(StartLoginResp)
	err := c.cc.Invoke(ctx, Passkeys_StartLogin_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *passkeysClient) FinishLogin(ctx context.Context, in *FinishLoginReq, opts ...grpc.CallOption) (*FinishLoginResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(FinishLoginResp)
	err := c.cc.Invoke(ctx, Passkeys_FinishLogin_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// PasskeysServer is the server API for Passkeys service.
// All implementations must embed UnimplementedPasskeysServer
// for forward compatibility.
//
// ================= 服务定义 =================
type PasskeysServer interface {
	// 注册
	// StartRegistration 注册第一步 - 开始
	StartRegistration(context.Context, *StartRegistrationReq) (*StartRegistrationResp, error)
	// FinishRegistration 注册第二步 - 完成
	FinishRegistration(context.Context, *FinishRegistrationReq) (*FinishRegistrationResp, error)
	// 登录
	// StartLogin 登陆第一步 - 开始
	StartLogin(context.Context, *StartLoginReq) (*StartLoginResp, error)
	// FinishLogin 登陆第二步 - 完成
	FinishLogin(context.Context, *FinishLoginReq) (*FinishLoginResp, error)
	mustEmbedUnimplementedPasskeysServer()
}

// UnimplementedPasskeysServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedPasskeysServer struct{}

func (UnimplementedPasskeysServer) StartRegistration(context.Context, *StartRegistrationReq) (*StartRegistrationResp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method StartRegistration not implemented")
}
func (UnimplementedPasskeysServer) FinishRegistration(context.Context, *FinishRegistrationReq) (*FinishRegistrationResp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method FinishRegistration not implemented")
}
func (UnimplementedPasskeysServer) StartLogin(context.Context, *StartLoginReq) (*StartLoginResp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method StartLogin not implemented")
}
func (UnimplementedPasskeysServer) FinishLogin(context.Context, *FinishLoginReq) (*FinishLoginResp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method FinishLogin not implemented")
}
func (UnimplementedPasskeysServer) mustEmbedUnimplementedPasskeysServer() {}
func (UnimplementedPasskeysServer) testEmbeddedByValue()                  {}

// UnsafePasskeysServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to PasskeysServer will
// result in compilation errors.
type UnsafePasskeysServer interface {
	mustEmbedUnimplementedPasskeysServer()
}

func RegisterPasskeysServer(s grpc.ServiceRegistrar, srv PasskeysServer) {
	// If the following call pancis, it indicates UnimplementedPasskeysServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&Passkeys_ServiceDesc, srv)
}

func _Passkeys_StartRegistration_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(StartRegistrationReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PasskeysServer).StartRegistration(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Passkeys_StartRegistration_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PasskeysServer).StartRegistration(ctx, req.(*StartRegistrationReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _Passkeys_FinishRegistration_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(FinishRegistrationReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PasskeysServer).FinishRegistration(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Passkeys_FinishRegistration_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PasskeysServer).FinishRegistration(ctx, req.(*FinishRegistrationReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _Passkeys_StartLogin_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(StartLoginReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PasskeysServer).StartLogin(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Passkeys_StartLogin_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PasskeysServer).StartLogin(ctx, req.(*StartLoginReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _Passkeys_FinishLogin_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(FinishLoginReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PasskeysServer).FinishLogin(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Passkeys_FinishLogin_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PasskeysServer).FinishLogin(ctx, req.(*FinishLoginReq))
	}
	return interceptor(ctx, in, info, handler)
}

// Passkeys_ServiceDesc is the grpc.ServiceDesc for Passkeys service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Passkeys_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "apollo.Passkeys",
	HandlerType: (*PasskeysServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "StartRegistration",
			Handler:    _Passkeys_StartRegistration_Handler,
		},
		{
			MethodName: "FinishRegistration",
			Handler:    _Passkeys_FinishRegistration_Handler,
		},
		{
			MethodName: "StartLogin",
			Handler:    _Passkeys_StartLogin_Handler,
		},
		{
			MethodName: "FinishLogin",
			Handler:    _Passkeys_FinishLogin_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "apollo.proto",
}
