// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.34.2
// 	protoc        v5.27.0
// source: apollo.proto

package apollo

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// ========== 注册流程 ==========
type StartRegistrationReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	UserId      int64  `protobuf:"varint,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`               // API生成
	UserName    string `protobuf:"bytes,2,opt,name=user_name,json=userName,proto3" json:"user_name,omitempty"`          // API提供
	DisplayName string `protobuf:"bytes,3,opt,name=display_name,json=displayName,proto3" json:"display_name,omitempty"` // API提供
}

func (x *StartRegistrationReq) Reset() {
	*x = StartRegistrationReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_apollo_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *StartRegistrationReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StartRegistrationReq) ProtoMessage() {}

func (x *StartRegistrationReq) ProtoReflect() protoreflect.Message {
	mi := &file_apollo_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StartRegistrationReq.ProtoReflect.Descriptor instead.
func (*StartRegistrationReq) Descriptor() ([]byte, []int) {
	return file_apollo_proto_rawDescGZIP(), []int{0}
}

func (x *StartRegistrationReq) GetUserId() int64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *StartRegistrationReq) GetUserName() string {
	if x != nil {
		return x.UserName
	}
	return ""
}

func (x *StartRegistrationReq) GetDisplayName() string {
	if x != nil {
		return x.DisplayName
	}
	return ""
}

type StartRegistrationResp struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	OptionsJson []byte `protobuf:"bytes,1,opt,name=options_json,json=optionsJson,proto3" json:"options_json,omitempty"` // WebAuthn标准选项
	SessionData []byte `protobuf:"bytes,2,opt,name=session_data,json=sessionData,proto3" json:"session_data,omitempty"` // 序列化的SessionData（API需存储）
}

func (x *StartRegistrationResp) Reset() {
	*x = StartRegistrationResp{}
	if protoimpl.UnsafeEnabled {
		mi := &file_apollo_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *StartRegistrationResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StartRegistrationResp) ProtoMessage() {}

func (x *StartRegistrationResp) ProtoReflect() protoreflect.Message {
	mi := &file_apollo_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StartRegistrationResp.ProtoReflect.Descriptor instead.
func (*StartRegistrationResp) Descriptor() ([]byte, []int) {
	return file_apollo_proto_rawDescGZIP(), []int{1}
}

func (x *StartRegistrationResp) GetOptionsJson() []byte {
	if x != nil {
		return x.OptionsJson
	}
	return nil
}

func (x *StartRegistrationResp) GetSessionData() []byte {
	if x != nil {
		return x.SessionData
	}
	return nil
}

type FinishRegistrationReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	UserId         int64  `protobuf:"varint,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`                        // 必须与StartRegistration一致
	CredentialJson []byte `protobuf:"bytes,2,opt,name=credential_json,json=credentialJson,proto3" json:"credential_json,omitempty"` // 前端返回的完整认证数据
	SessionData    []byte `protobuf:"bytes,3,opt,name=session_data,json=sessionData,proto3" json:"session_data,omitempty"`          // 新增：StartRegistration返回的session_data
}

func (x *FinishRegistrationReq) Reset() {
	*x = FinishRegistrationReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_apollo_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *FinishRegistrationReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FinishRegistrationReq) ProtoMessage() {}

func (x *FinishRegistrationReq) ProtoReflect() protoreflect.Message {
	mi := &file_apollo_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FinishRegistrationReq.ProtoReflect.Descriptor instead.
func (*FinishRegistrationReq) Descriptor() ([]byte, []int) {
	return file_apollo_proto_rawDescGZIP(), []int{2}
}

func (x *FinishRegistrationReq) GetUserId() int64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *FinishRegistrationReq) GetCredentialJson() []byte {
	if x != nil {
		return x.CredentialJson
	}
	return nil
}

func (x *FinishRegistrationReq) GetSessionData() []byte {
	if x != nil {
		return x.SessionData
	}
	return nil
}

type FinishRegistrationResp struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	CredentialId []byte `protobuf:"bytes,1,opt,name=credential_id,json=credentialId,proto3" json:"credential_id,omitempty"`
	PublicKey    []byte `protobuf:"bytes,2,opt,name=public_key,json=publicKey,proto3" json:"public_key,omitempty"`
}

func (x *FinishRegistrationResp) Reset() {
	*x = FinishRegistrationResp{}
	if protoimpl.UnsafeEnabled {
		mi := &file_apollo_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *FinishRegistrationResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FinishRegistrationResp) ProtoMessage() {}

func (x *FinishRegistrationResp) ProtoReflect() protoreflect.Message {
	mi := &file_apollo_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FinishRegistrationResp.ProtoReflect.Descriptor instead.
func (*FinishRegistrationResp) Descriptor() ([]byte, []int) {
	return file_apollo_proto_rawDescGZIP(), []int{3}
}

func (x *FinishRegistrationResp) GetCredentialId() []byte {
	if x != nil {
		return x.CredentialId
	}
	return nil
}

func (x *FinishRegistrationResp) GetPublicKey() []byte {
	if x != nil {
		return x.PublicKey
	}
	return nil
}

// ========== 登录流程 ==========
type StartLoginReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *StartLoginReq) Reset() {
	*x = StartLoginReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_apollo_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *StartLoginReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StartLoginReq) ProtoMessage() {}

func (x *StartLoginReq) ProtoReflect() protoreflect.Message {
	mi := &file_apollo_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StartLoginReq.ProtoReflect.Descriptor instead.
func (*StartLoginReq) Descriptor() ([]byte, []int) {
	return file_apollo_proto_rawDescGZIP(), []int{4}
}

type StartLoginResp struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	OptionsJson []byte `protobuf:"bytes,1,opt,name=options_json,json=optionsJson,proto3" json:"options_json,omitempty"`
	SessionData []byte `protobuf:"bytes,2,opt,name=session_data,json=sessionData,proto3" json:"session_data,omitempty"` // 必须返回给API存储
}

func (x *StartLoginResp) Reset() {
	*x = StartLoginResp{}
	if protoimpl.UnsafeEnabled {
		mi := &file_apollo_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *StartLoginResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StartLoginResp) ProtoMessage() {}

func (x *StartLoginResp) ProtoReflect() protoreflect.Message {
	mi := &file_apollo_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StartLoginResp.ProtoReflect.Descriptor instead.
func (*StartLoginResp) Descriptor() ([]byte, []int) {
	return file_apollo_proto_rawDescGZIP(), []int{5}
}

func (x *StartLoginResp) GetOptionsJson() []byte {
	if x != nil {
		return x.OptionsJson
	}
	return nil
}

func (x *StartLoginResp) GetSessionData() []byte {
	if x != nil {
		return x.SessionData
	}
	return nil
}

type FinishLoginReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	CredentialJson []byte `protobuf:"bytes,1,opt,name=credential_json,json=credentialJson,proto3" json:"credential_json,omitempty"` // 前端原始JSON
	SessionData    []byte `protobuf:"bytes,2,opt,name=session_data,json=sessionData,proto3" json:"session_data,omitempty"`          // StartLogin返回的session_data
}

func (x *FinishLoginReq) Reset() {
	*x = FinishLoginReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_apollo_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *FinishLoginReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FinishLoginReq) ProtoMessage() {}

func (x *FinishLoginReq) ProtoReflect() protoreflect.Message {
	mi := &file_apollo_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FinishLoginReq.ProtoReflect.Descriptor instead.
func (*FinishLoginReq) Descriptor() ([]byte, []int) {
	return file_apollo_proto_rawDescGZIP(), []int{6}
}

func (x *FinishLoginReq) GetCredentialJson() []byte {
	if x != nil {
		return x.CredentialJson
	}
	return nil
}

func (x *FinishLoginReq) GetSessionData() []byte {
	if x != nil {
		return x.SessionData
	}
	return nil
}

type FinishLoginResp struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	UserId       int64  `protobuf:"varint,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`                  // 验证通过的用户ID
	CredentialId []byte `protobuf:"bytes,2,opt,name=credential_id,json=credentialId,proto3" json:"credential_id,omitempty"` // 使用的凭证ID（用于审计）
}

func (x *FinishLoginResp) Reset() {
	*x = FinishLoginResp{}
	if protoimpl.UnsafeEnabled {
		mi := &file_apollo_proto_msgTypes[7]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *FinishLoginResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FinishLoginResp) ProtoMessage() {}

func (x *FinishLoginResp) ProtoReflect() protoreflect.Message {
	mi := &file_apollo_proto_msgTypes[7]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FinishLoginResp.ProtoReflect.Descriptor instead.
func (*FinishLoginResp) Descriptor() ([]byte, []int) {
	return file_apollo_proto_rawDescGZIP(), []int{7}
}

func (x *FinishLoginResp) GetUserId() int64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *FinishLoginResp) GetCredentialId() []byte {
	if x != nil {
		return x.CredentialId
	}
	return nil
}

var File_apollo_proto protoreflect.FileDescriptor

var file_apollo_proto_rawDesc = []byte{
	0x0a, 0x0c, 0x61, 0x70, 0x6f, 0x6c, 0x6c, 0x6f, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x06,
	0x61, 0x70, 0x6f, 0x6c, 0x6c, 0x6f, 0x22, 0x6f, 0x0a, 0x14, 0x53, 0x74, 0x61, 0x72, 0x74, 0x52,
	0x65, 0x67, 0x69, 0x73, 0x74, 0x72, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x52, 0x65, 0x71, 0x12, 0x17,
	0x0a, 0x07, 0x75, 0x73, 0x65, 0x72, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x52,
	0x06, 0x75, 0x73, 0x65, 0x72, 0x49, 0x64, 0x12, 0x1b, 0x0a, 0x09, 0x75, 0x73, 0x65, 0x72, 0x5f,
	0x6e, 0x61, 0x6d, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x75, 0x73, 0x65, 0x72,
	0x4e, 0x61, 0x6d, 0x65, 0x12, 0x21, 0x0a, 0x0c, 0x64, 0x69, 0x73, 0x70, 0x6c, 0x61, 0x79, 0x5f,
	0x6e, 0x61, 0x6d, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0b, 0x64, 0x69, 0x73, 0x70,
	0x6c, 0x61, 0x79, 0x4e, 0x61, 0x6d, 0x65, 0x22, 0x5d, 0x0a, 0x15, 0x53, 0x74, 0x61, 0x72, 0x74,
	0x52, 0x65, 0x67, 0x69, 0x73, 0x74, 0x72, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x52, 0x65, 0x73, 0x70,
	0x12, 0x21, 0x0a, 0x0c, 0x6f, 0x70, 0x74, 0x69, 0x6f, 0x6e, 0x73, 0x5f, 0x6a, 0x73, 0x6f, 0x6e,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x0b, 0x6f, 0x70, 0x74, 0x69, 0x6f, 0x6e, 0x73, 0x4a,
	0x73, 0x6f, 0x6e, 0x12, 0x21, 0x0a, 0x0c, 0x73, 0x65, 0x73, 0x73, 0x69, 0x6f, 0x6e, 0x5f, 0x64,
	0x61, 0x74, 0x61, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x0b, 0x73, 0x65, 0x73, 0x73, 0x69,
	0x6f, 0x6e, 0x44, 0x61, 0x74, 0x61, 0x22, 0x7c, 0x0a, 0x15, 0x46, 0x69, 0x6e, 0x69, 0x73, 0x68,
	0x52, 0x65, 0x67, 0x69, 0x73, 0x74, 0x72, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x52, 0x65, 0x71, 0x12,
	0x17, 0x0a, 0x07, 0x75, 0x73, 0x65, 0x72, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03,
	0x52, 0x06, 0x75, 0x73, 0x65, 0x72, 0x49, 0x64, 0x12, 0x27, 0x0a, 0x0f, 0x63, 0x72, 0x65, 0x64,
	0x65, 0x6e, 0x74, 0x69, 0x61, 0x6c, 0x5f, 0x6a, 0x73, 0x6f, 0x6e, 0x18, 0x02, 0x20, 0x01, 0x28,
	0x0c, 0x52, 0x0e, 0x63, 0x72, 0x65, 0x64, 0x65, 0x6e, 0x74, 0x69, 0x61, 0x6c, 0x4a, 0x73, 0x6f,
	0x6e, 0x12, 0x21, 0x0a, 0x0c, 0x73, 0x65, 0x73, 0x73, 0x69, 0x6f, 0x6e, 0x5f, 0x64, 0x61, 0x74,
	0x61, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x0b, 0x73, 0x65, 0x73, 0x73, 0x69, 0x6f, 0x6e,
	0x44, 0x61, 0x74, 0x61, 0x22, 0x5c, 0x0a, 0x16, 0x46, 0x69, 0x6e, 0x69, 0x73, 0x68, 0x52, 0x65,
	0x67, 0x69, 0x73, 0x74, 0x72, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x52, 0x65, 0x73, 0x70, 0x12, 0x23,
	0x0a, 0x0d, 0x63, 0x72, 0x65, 0x64, 0x65, 0x6e, 0x74, 0x69, 0x61, 0x6c, 0x5f, 0x69, 0x64, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x0c, 0x63, 0x72, 0x65, 0x64, 0x65, 0x6e, 0x74, 0x69, 0x61,
	0x6c, 0x49, 0x64, 0x12, 0x1d, 0x0a, 0x0a, 0x70, 0x75, 0x62, 0x6c, 0x69, 0x63, 0x5f, 0x6b, 0x65,
	0x79, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x09, 0x70, 0x75, 0x62, 0x6c, 0x69, 0x63, 0x4b,
	0x65, 0x79, 0x22, 0x0f, 0x0a, 0x0d, 0x53, 0x74, 0x61, 0x72, 0x74, 0x4c, 0x6f, 0x67, 0x69, 0x6e,
	0x52, 0x65, 0x71, 0x22, 0x56, 0x0a, 0x0e, 0x53, 0x74, 0x61, 0x72, 0x74, 0x4c, 0x6f, 0x67, 0x69,
	0x6e, 0x52, 0x65, 0x73, 0x70, 0x12, 0x21, 0x0a, 0x0c, 0x6f, 0x70, 0x74, 0x69, 0x6f, 0x6e, 0x73,
	0x5f, 0x6a, 0x73, 0x6f, 0x6e, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x0b, 0x6f, 0x70, 0x74,
	0x69, 0x6f, 0x6e, 0x73, 0x4a, 0x73, 0x6f, 0x6e, 0x12, 0x21, 0x0a, 0x0c, 0x73, 0x65, 0x73, 0x73,
	0x69, 0x6f, 0x6e, 0x5f, 0x64, 0x61, 0x74, 0x61, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x0b,
	0x73, 0x65, 0x73, 0x73, 0x69, 0x6f, 0x6e, 0x44, 0x61, 0x74, 0x61, 0x22, 0x5c, 0x0a, 0x0e, 0x46,
	0x69, 0x6e, 0x69, 0x73, 0x68, 0x4c, 0x6f, 0x67, 0x69, 0x6e, 0x52, 0x65, 0x71, 0x12, 0x27, 0x0a,
	0x0f, 0x63, 0x72, 0x65, 0x64, 0x65, 0x6e, 0x74, 0x69, 0x61, 0x6c, 0x5f, 0x6a, 0x73, 0x6f, 0x6e,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x0e, 0x63, 0x72, 0x65, 0x64, 0x65, 0x6e, 0x74, 0x69,
	0x61, 0x6c, 0x4a, 0x73, 0x6f, 0x6e, 0x12, 0x21, 0x0a, 0x0c, 0x73, 0x65, 0x73, 0x73, 0x69, 0x6f,
	0x6e, 0x5f, 0x64, 0x61, 0x74, 0x61, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x0b, 0x73, 0x65,
	0x73, 0x73, 0x69, 0x6f, 0x6e, 0x44, 0x61, 0x74, 0x61, 0x22, 0x4f, 0x0a, 0x0f, 0x46, 0x69, 0x6e,
	0x69, 0x73, 0x68, 0x4c, 0x6f, 0x67, 0x69, 0x6e, 0x52, 0x65, 0x73, 0x70, 0x12, 0x17, 0x0a, 0x07,
	0x75, 0x73, 0x65, 0x72, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x52, 0x06, 0x75,
	0x73, 0x65, 0x72, 0x49, 0x64, 0x12, 0x23, 0x0a, 0x0d, 0x63, 0x72, 0x65, 0x64, 0x65, 0x6e, 0x74,
	0x69, 0x61, 0x6c, 0x5f, 0x69, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x0c, 0x63, 0x72,
	0x65, 0x64, 0x65, 0x6e, 0x74, 0x69, 0x61, 0x6c, 0x49, 0x64, 0x32, 0xae, 0x02, 0x0a, 0x08, 0x50,
	0x61, 0x73, 0x73, 0x6b, 0x65, 0x79, 0x73, 0x12, 0x50, 0x0a, 0x11, 0x53, 0x74, 0x61, 0x72, 0x74,
	0x52, 0x65, 0x67, 0x69, 0x73, 0x74, 0x72, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x12, 0x1c, 0x2e, 0x61,
	0x70, 0x6f, 0x6c, 0x6c, 0x6f, 0x2e, 0x53, 0x74, 0x61, 0x72, 0x74, 0x52, 0x65, 0x67, 0x69, 0x73,
	0x74, 0x72, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x52, 0x65, 0x71, 0x1a, 0x1d, 0x2e, 0x61, 0x70, 0x6f,
	0x6c, 0x6c, 0x6f, 0x2e, 0x53, 0x74, 0x61, 0x72, 0x74, 0x52, 0x65, 0x67, 0x69, 0x73, 0x74, 0x72,
	0x61, 0x74, 0x69, 0x6f, 0x6e, 0x52, 0x65, 0x73, 0x70, 0x12, 0x53, 0x0a, 0x12, 0x46, 0x69, 0x6e,
	0x69, 0x73, 0x68, 0x52, 0x65, 0x67, 0x69, 0x73, 0x74, 0x72, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x12,
	0x1d, 0x2e, 0x61, 0x70, 0x6f, 0x6c, 0x6c, 0x6f, 0x2e, 0x46, 0x69, 0x6e, 0x69, 0x73, 0x68, 0x52,
	0x65, 0x67, 0x69, 0x73, 0x74, 0x72, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x52, 0x65, 0x71, 0x1a, 0x1e,
	0x2e, 0x61, 0x70, 0x6f, 0x6c, 0x6c, 0x6f, 0x2e, 0x46, 0x69, 0x6e, 0x69, 0x73, 0x68, 0x52, 0x65,
	0x67, 0x69, 0x73, 0x74, 0x72, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x52, 0x65, 0x73, 0x70, 0x12, 0x3b,
	0x0a, 0x0a, 0x53, 0x74, 0x61, 0x72, 0x74, 0x4c, 0x6f, 0x67, 0x69, 0x6e, 0x12, 0x15, 0x2e, 0x61,
	0x70, 0x6f, 0x6c, 0x6c, 0x6f, 0x2e, 0x53, 0x74, 0x61, 0x72, 0x74, 0x4c, 0x6f, 0x67, 0x69, 0x6e,
	0x52, 0x65, 0x71, 0x1a, 0x16, 0x2e, 0x61, 0x70, 0x6f, 0x6c, 0x6c, 0x6f, 0x2e, 0x53, 0x74, 0x61,
	0x72, 0x74, 0x4c, 0x6f, 0x67, 0x69, 0x6e, 0x52, 0x65, 0x73, 0x70, 0x12, 0x3e, 0x0a, 0x0b, 0x46,
	0x69, 0x6e, 0x69, 0x73, 0x68, 0x4c, 0x6f, 0x67, 0x69, 0x6e, 0x12, 0x16, 0x2e, 0x61, 0x70, 0x6f,
	0x6c, 0x6c, 0x6f, 0x2e, 0x46, 0x69, 0x6e, 0x69, 0x73, 0x68, 0x4c, 0x6f, 0x67, 0x69, 0x6e, 0x52,
	0x65, 0x71, 0x1a, 0x17, 0x2e, 0x61, 0x70, 0x6f, 0x6c, 0x6c, 0x6f, 0x2e, 0x46, 0x69, 0x6e, 0x69,
	0x73, 0x68, 0x4c, 0x6f, 0x67, 0x69, 0x6e, 0x52, 0x65, 0x73, 0x70, 0x42, 0x0a, 0x5a, 0x08, 0x2e,
	0x2f, 0x61, 0x70, 0x6f, 0x6c, 0x6c, 0x6f, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_apollo_proto_rawDescOnce sync.Once
	file_apollo_proto_rawDescData = file_apollo_proto_rawDesc
)

func file_apollo_proto_rawDescGZIP() []byte {
	file_apollo_proto_rawDescOnce.Do(func() {
		file_apollo_proto_rawDescData = protoimpl.X.CompressGZIP(file_apollo_proto_rawDescData)
	})
	return file_apollo_proto_rawDescData
}

var file_apollo_proto_msgTypes = make([]protoimpl.MessageInfo, 8)
var file_apollo_proto_goTypes = []any{
	(*StartRegistrationReq)(nil),   // 0: apollo.StartRegistrationReq
	(*StartRegistrationResp)(nil),  // 1: apollo.StartRegistrationResp
	(*FinishRegistrationReq)(nil),  // 2: apollo.FinishRegistrationReq
	(*FinishRegistrationResp)(nil), // 3: apollo.FinishRegistrationResp
	(*StartLoginReq)(nil),          // 4: apollo.StartLoginReq
	(*StartLoginResp)(nil),         // 5: apollo.StartLoginResp
	(*FinishLoginReq)(nil),         // 6: apollo.FinishLoginReq
	(*FinishLoginResp)(nil),        // 7: apollo.FinishLoginResp
}
var file_apollo_proto_depIdxs = []int32{
	0, // 0: apollo.Passkeys.StartRegistration:input_type -> apollo.StartRegistrationReq
	2, // 1: apollo.Passkeys.FinishRegistration:input_type -> apollo.FinishRegistrationReq
	4, // 2: apollo.Passkeys.StartLogin:input_type -> apollo.StartLoginReq
	6, // 3: apollo.Passkeys.FinishLogin:input_type -> apollo.FinishLoginReq
	1, // 4: apollo.Passkeys.StartRegistration:output_type -> apollo.StartRegistrationResp
	3, // 5: apollo.Passkeys.FinishRegistration:output_type -> apollo.FinishRegistrationResp
	5, // 6: apollo.Passkeys.StartLogin:output_type -> apollo.StartLoginResp
	7, // 7: apollo.Passkeys.FinishLogin:output_type -> apollo.FinishLoginResp
	4, // [4:8] is the sub-list for method output_type
	0, // [0:4] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_apollo_proto_init() }
func file_apollo_proto_init() {
	if File_apollo_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_apollo_proto_msgTypes[0].Exporter = func(v any, i int) any {
			switch v := v.(*StartRegistrationReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_apollo_proto_msgTypes[1].Exporter = func(v any, i int) any {
			switch v := v.(*StartRegistrationResp); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_apollo_proto_msgTypes[2].Exporter = func(v any, i int) any {
			switch v := v.(*FinishRegistrationReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_apollo_proto_msgTypes[3].Exporter = func(v any, i int) any {
			switch v := v.(*FinishRegistrationResp); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_apollo_proto_msgTypes[4].Exporter = func(v any, i int) any {
			switch v := v.(*StartLoginReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_apollo_proto_msgTypes[5].Exporter = func(v any, i int) any {
			switch v := v.(*StartLoginResp); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_apollo_proto_msgTypes[6].Exporter = func(v any, i int) any {
			switch v := v.(*FinishLoginReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_apollo_proto_msgTypes[7].Exporter = func(v any, i int) any {
			switch v := v.(*FinishLoginResp); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_apollo_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   8,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_apollo_proto_goTypes,
		DependencyIndexes: file_apollo_proto_depIdxs,
		MessageInfos:      file_apollo_proto_msgTypes,
	}.Build()
	File_apollo_proto = out.File
	file_apollo_proto_rawDesc = nil
	file_apollo_proto_goTypes = nil
	file_apollo_proto_depIdxs = nil
}
