// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v3.19.4
// source: apollo-rpc.proto

package apollo

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Empty struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Empty) Reset() {
	*x = Empty{}
	mi := &file_apollo_rpc_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Empty) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Empty) ProtoMessage() {}

func (x *Empty) ProtoReflect() protoreflect.Message {
	mi := &file_apollo_rpc_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Empty.ProtoReflect.Descriptor instead.
func (*Empty) Descriptor() ([]byte, []int) {
	return file_apollo_rpc_proto_rawDescGZIP(), []int{0}
}

// Account
// ========== 注册流程 ==========
type RegistrationReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        int64                  `protobuf:"varint,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Email         string                 `protobuf:"bytes,2,opt,name=email,proto3" json:"email,omitempty"`
	Password      string                 `protobuf:"bytes,3,opt,name=password,proto3" json:"password,omitempty"`
	Locate        string                 `protobuf:"bytes,4,opt,name=locate,proto3" json:"locate,omitempty"`
	Language      string                 `protobuf:"bytes,5,opt,name=language,proto3" json:"language,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RegistrationReq) Reset() {
	*x = RegistrationReq{}
	mi := &file_apollo_rpc_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RegistrationReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegistrationReq) ProtoMessage() {}

func (x *RegistrationReq) ProtoReflect() protoreflect.Message {
	mi := &file_apollo_rpc_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RegistrationReq.ProtoReflect.Descriptor instead.
func (*RegistrationReq) Descriptor() ([]byte, []int) {
	return file_apollo_rpc_proto_rawDescGZIP(), []int{1}
}

func (x *RegistrationReq) GetUserId() int64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *RegistrationReq) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

func (x *RegistrationReq) GetPassword() string {
	if x != nil {
		return x.Password
	}
	return ""
}

func (x *RegistrationReq) GetLocate() string {
	if x != nil {
		return x.Locate
	}
	return ""
}

func (x *RegistrationReq) GetLanguage() string {
	if x != nil {
		return x.Language
	}
	return ""
}

// ========== 登录流程 ==========
type LoginReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Email         string                 `protobuf:"bytes,1,opt,name=email,proto3" json:"email,omitempty"`
	Password      string                 `protobuf:"bytes,2,opt,name=password,proto3" json:"password,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LoginReq) Reset() {
	*x = LoginReq{}
	mi := &file_apollo_rpc_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LoginReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LoginReq) ProtoMessage() {}

func (x *LoginReq) ProtoReflect() protoreflect.Message {
	mi := &file_apollo_rpc_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LoginReq.ProtoReflect.Descriptor instead.
func (*LoginReq) Descriptor() ([]byte, []int) {
	return file_apollo_rpc_proto_rawDescGZIP(), []int{2}
}

func (x *LoginReq) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

func (x *LoginReq) GetPassword() string {
	if x != nil {
		return x.Password
	}
	return ""
}

type LoginResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        int64                  `protobuf:"varint,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	GivenName     string                 `protobuf:"bytes,2,opt,name=given_name,json=givenName,proto3" json:"given_name,omitempty"`
	MiddleName    string                 `protobuf:"bytes,3,opt,name=middle_name,json=middleName,proto3" json:"middle_name,omitempty"`
	FamilyName    string                 `protobuf:"bytes,4,opt,name=family_name,json=familyName,proto3" json:"family_name,omitempty"`
	Avatar        string                 `protobuf:"bytes,5,opt,name=avatar,proto3" json:"avatar,omitempty"`
	Locale        string                 `protobuf:"bytes,6,opt,name=locale,proto3" json:"locale,omitempty"`
	Language      string                 `protobuf:"bytes,7,opt,name=language,proto3" json:"language,omitempty"`
	BirthdayYear  int64                  `protobuf:"varint,8,opt,name=birthday_year,json=birthdayYear,proto3" json:"birthday_year,omitempty"`
	BirthdayMonth int64                  `protobuf:"varint,9,opt,name=birthday_month,json=birthdayMonth,proto3" json:"birthday_month,omitempty"`
	BirthdayDay   int64                  `protobuf:"varint,10,opt,name=birthday_day,json=birthdayDay,proto3" json:"birthday_day,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LoginResp) Reset() {
	*x = LoginResp{}
	mi := &file_apollo_rpc_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LoginResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LoginResp) ProtoMessage() {}

func (x *LoginResp) ProtoReflect() protoreflect.Message {
	mi := &file_apollo_rpc_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LoginResp.ProtoReflect.Descriptor instead.
func (*LoginResp) Descriptor() ([]byte, []int) {
	return file_apollo_rpc_proto_rawDescGZIP(), []int{3}
}

func (x *LoginResp) GetUserId() int64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *LoginResp) GetGivenName() string {
	if x != nil {
		return x.GivenName
	}
	return ""
}

func (x *LoginResp) GetMiddleName() string {
	if x != nil {
		return x.MiddleName
	}
	return ""
}

func (x *LoginResp) GetFamilyName() string {
	if x != nil {
		return x.FamilyName
	}
	return ""
}

func (x *LoginResp) GetAvatar() string {
	if x != nil {
		return x.Avatar
	}
	return ""
}

func (x *LoginResp) GetLocale() string {
	if x != nil {
		return x.Locale
	}
	return ""
}

func (x *LoginResp) GetLanguage() string {
	if x != nil {
		return x.Language
	}
	return ""
}

func (x *LoginResp) GetBirthdayYear() int64 {
	if x != nil {
		return x.BirthdayYear
	}
	return 0
}

func (x *LoginResp) GetBirthdayMonth() int64 {
	if x != nil {
		return x.BirthdayMonth
	}
	return 0
}

func (x *LoginResp) GetBirthdayDay() int64 {
	if x != nil {
		return x.BirthdayDay
	}
	return 0
}

// ========== 用户信息 ==========
type UserInfoReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        int64                  `protobuf:"varint,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UserInfoReq) Reset() {
	*x = UserInfoReq{}
	mi := &file_apollo_rpc_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UserInfoReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UserInfoReq) ProtoMessage() {}

func (x *UserInfoReq) ProtoReflect() protoreflect.Message {
	mi := &file_apollo_rpc_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UserInfoReq.ProtoReflect.Descriptor instead.
func (*UserInfoReq) Descriptor() ([]byte, []int) {
	return file_apollo_rpc_proto_rawDescGZIP(), []int{4}
}

func (x *UserInfoReq) GetUserId() int64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

type UserInfoResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserBytes     []byte                 `protobuf:"bytes,1,opt,name=user_bytes,json=userBytes,proto3" json:"user_bytes,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UserInfoResp) Reset() {
	*x = UserInfoResp{}
	mi := &file_apollo_rpc_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UserInfoResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UserInfoResp) ProtoMessage() {}

func (x *UserInfoResp) ProtoReflect() protoreflect.Message {
	mi := &file_apollo_rpc_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UserInfoResp.ProtoReflect.Descriptor instead.
func (*UserInfoResp) Descriptor() ([]byte, []int) {
	return file_apollo_rpc_proto_rawDescGZIP(), []int{5}
}

func (x *UserInfoResp) GetUserBytes() []byte {
	if x != nil {
		return x.UserBytes
	}
	return nil
}

// ========== 用户安全信息 ==========
type UserSecurityInfoReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        int64                  `protobuf:"varint,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UserSecurityInfoReq) Reset() {
	*x = UserSecurityInfoReq{}
	mi := &file_apollo_rpc_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UserSecurityInfoReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UserSecurityInfoReq) ProtoMessage() {}

func (x *UserSecurityInfoReq) ProtoReflect() protoreflect.Message {
	mi := &file_apollo_rpc_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UserSecurityInfoReq.ProtoReflect.Descriptor instead.
func (*UserSecurityInfoReq) Descriptor() ([]byte, []int) {
	return file_apollo_rpc_proto_rawDescGZIP(), []int{6}
}

func (x *UserSecurityInfoReq) GetUserId() int64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

type UserContact struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Value         string                 `protobuf:"bytes,2,opt,name=value,proto3" json:"value,omitempty"`
	Type          int64                  `protobuf:"varint,3,opt,name=type,proto3" json:"type,omitempty"`
	PhoneRegion   string                 `protobuf:"bytes,4,opt,name=phone_region,json=phoneRegion,proto3" json:"phone_region,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UserContact) Reset() {
	*x = UserContact{}
	mi := &file_apollo_rpc_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UserContact) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UserContact) ProtoMessage() {}

func (x *UserContact) ProtoReflect() protoreflect.Message {
	mi := &file_apollo_rpc_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UserContact.ProtoReflect.Descriptor instead.
func (*UserContact) Descriptor() ([]byte, []int) {
	return file_apollo_rpc_proto_rawDescGZIP(), []int{7}
}

func (x *UserContact) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *UserContact) GetValue() string {
	if x != nil {
		return x.Value
	}
	return ""
}

func (x *UserContact) GetType() int64 {
	if x != nil {
		return x.Type
	}
	return 0
}

func (x *UserContact) GetPhoneRegion() string {
	if x != nil {
		return x.PhoneRegion
	}
	return ""
}

type PasswordUpdatedDate struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Year          int64                  `protobuf:"varint,1,opt,name=year,proto3" json:"year,omitempty"`
	Month         int64                  `protobuf:"varint,2,opt,name=month,proto3" json:"month,omitempty"`
	Day           int64                  `protobuf:"varint,3,opt,name=day,proto3" json:"day,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PasswordUpdatedDate) Reset() {
	*x = PasswordUpdatedDate{}
	mi := &file_apollo_rpc_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PasswordUpdatedDate) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PasswordUpdatedDate) ProtoMessage() {}

func (x *PasswordUpdatedDate) ProtoReflect() protoreflect.Message {
	mi := &file_apollo_rpc_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PasswordUpdatedDate.ProtoReflect.Descriptor instead.
func (*PasswordUpdatedDate) Descriptor() ([]byte, []int) {
	return file_apollo_rpc_proto_rawDescGZIP(), []int{8}
}

func (x *PasswordUpdatedDate) GetYear() int64 {
	if x != nil {
		return x.Year
	}
	return 0
}

func (x *PasswordUpdatedDate) GetMonth() int64 {
	if x != nil {
		return x.Month
	}
	return 0
}

func (x *PasswordUpdatedDate) GetDay() int64 {
	if x != nil {
		return x.Day
	}
	return 0
}

type ThirdPartyAccounts struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Github        bool                   `protobuf:"varint,1,opt,name=github,proto3" json:"github,omitempty"`
	Google        bool                   `protobuf:"varint,2,opt,name=google,proto3" json:"google,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ThirdPartyAccounts) Reset() {
	*x = ThirdPartyAccounts{}
	mi := &file_apollo_rpc_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ThirdPartyAccounts) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ThirdPartyAccounts) ProtoMessage() {}

func (x *ThirdPartyAccounts) ProtoReflect() protoreflect.Message {
	mi := &file_apollo_rpc_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ThirdPartyAccounts.ProtoReflect.Descriptor instead.
func (*ThirdPartyAccounts) Descriptor() ([]byte, []int) {
	return file_apollo_rpc_proto_rawDescGZIP(), []int{9}
}

func (x *ThirdPartyAccounts) GetGithub() bool {
	if x != nil {
		return x.Github
	}
	return false
}

func (x *ThirdPartyAccounts) GetGoogle() bool {
	if x != nil {
		return x.Google
	}
	return false
}

type UserSecurityInfoResp struct {
	state                   protoimpl.MessageState `protogen:"open.v1"`
	Contacts                []*UserContact         `protobuf:"bytes,1,rep,name=contacts,proto3" json:"contacts,omitempty"`
	PasswordUpdatedDate     *PasswordUpdatedDate   `protobuf:"bytes,2,opt,name=password_updated_date,json=passwordUpdatedDate,proto3" json:"password_updated_date,omitempty"`
	AccountSecurityTokenNum int64                  `protobuf:"varint,3,opt,name=account_security_token_num,json=accountSecurityTokenNum,proto3" json:"account_security_token_num,omitempty"`
	PasskeysNum             int64                  `protobuf:"varint,4,opt,name=passkeys_num,json=passkeysNum,proto3" json:"passkeys_num,omitempty"`
	ThirdPartyAccounts      *ThirdPartyAccounts    `protobuf:"bytes,5,opt,name=third_party_accounts,json=thirdPartyAccounts,proto3" json:"third_party_accounts,omitempty"`
	unknownFields           protoimpl.UnknownFields
	sizeCache               protoimpl.SizeCache
}

func (x *UserSecurityInfoResp) Reset() {
	*x = UserSecurityInfoResp{}
	mi := &file_apollo_rpc_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UserSecurityInfoResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UserSecurityInfoResp) ProtoMessage() {}

func (x *UserSecurityInfoResp) ProtoReflect() protoreflect.Message {
	mi := &file_apollo_rpc_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UserSecurityInfoResp.ProtoReflect.Descriptor instead.
func (*UserSecurityInfoResp) Descriptor() ([]byte, []int) {
	return file_apollo_rpc_proto_rawDescGZIP(), []int{10}
}

func (x *UserSecurityInfoResp) GetContacts() []*UserContact {
	if x != nil {
		return x.Contacts
	}
	return nil
}

func (x *UserSecurityInfoResp) GetPasswordUpdatedDate() *PasswordUpdatedDate {
	if x != nil {
		return x.PasswordUpdatedDate
	}
	return nil
}

func (x *UserSecurityInfoResp) GetAccountSecurityTokenNum() int64 {
	if x != nil {
		return x.AccountSecurityTokenNum
	}
	return 0
}

func (x *UserSecurityInfoResp) GetPasskeysNum() int64 {
	if x != nil {
		return x.PasskeysNum
	}
	return 0
}

func (x *UserSecurityInfoResp) GetThirdPartyAccounts() *ThirdPartyAccounts {
	if x != nil {
		return x.ThirdPartyAccounts
	}
	return nil
}

// Passkeys
// ========== 注册流程 ==========
type PasskeysStartRegistrationReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        int64                  `protobuf:"varint,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`               // API生成
	UserName      string                 `protobuf:"bytes,2,opt,name=user_name,json=userName,proto3" json:"user_name,omitempty"`          // API提供
	DisplayName   string                 `protobuf:"bytes,3,opt,name=display_name,json=displayName,proto3" json:"display_name,omitempty"` // API提供
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PasskeysStartRegistrationReq) Reset() {
	*x = PasskeysStartRegistrationReq{}
	mi := &file_apollo_rpc_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PasskeysStartRegistrationReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PasskeysStartRegistrationReq) ProtoMessage() {}

func (x *PasskeysStartRegistrationReq) ProtoReflect() protoreflect.Message {
	mi := &file_apollo_rpc_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PasskeysStartRegistrationReq.ProtoReflect.Descriptor instead.
func (*PasskeysStartRegistrationReq) Descriptor() ([]byte, []int) {
	return file_apollo_rpc_proto_rawDescGZIP(), []int{11}
}

func (x *PasskeysStartRegistrationReq) GetUserId() int64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *PasskeysStartRegistrationReq) GetUserName() string {
	if x != nil {
		return x.UserName
	}
	return ""
}

func (x *PasskeysStartRegistrationReq) GetDisplayName() string {
	if x != nil {
		return x.DisplayName
	}
	return ""
}

type PasskeysStartRegistrationResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	OptionsJson   []byte                 `protobuf:"bytes,1,opt,name=options_json,json=optionsJson,proto3" json:"options_json,omitempty"` // WebAuthn标准选项
	SessionData   []byte                 `protobuf:"bytes,2,opt,name=session_data,json=sessionData,proto3" json:"session_data,omitempty"` // 序列化的SessionData（API需存储）
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PasskeysStartRegistrationResp) Reset() {
	*x = PasskeysStartRegistrationResp{}
	mi := &file_apollo_rpc_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PasskeysStartRegistrationResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PasskeysStartRegistrationResp) ProtoMessage() {}

func (x *PasskeysStartRegistrationResp) ProtoReflect() protoreflect.Message {
	mi := &file_apollo_rpc_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PasskeysStartRegistrationResp.ProtoReflect.Descriptor instead.
func (*PasskeysStartRegistrationResp) Descriptor() ([]byte, []int) {
	return file_apollo_rpc_proto_rawDescGZIP(), []int{12}
}

func (x *PasskeysStartRegistrationResp) GetOptionsJson() []byte {
	if x != nil {
		return x.OptionsJson
	}
	return nil
}

func (x *PasskeysStartRegistrationResp) GetSessionData() []byte {
	if x != nil {
		return x.SessionData
	}
	return nil
}

type PasskeysFinishRegistrationReq struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	UserId         int64                  `protobuf:"varint,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`                        // 必须与StartRegistration一致
	CredentialJson []byte                 `protobuf:"bytes,2,opt,name=credential_json,json=credentialJson,proto3" json:"credential_json,omitempty"` // 前端返回的完整认证数据
	SessionData    []byte                 `protobuf:"bytes,3,opt,name=session_data,json=sessionData,proto3" json:"session_data,omitempty"`          // 新增：StartRegistration返回的session_data
	Locate         string                 `protobuf:"bytes,4,opt,name=Locate,proto3" json:"Locate,omitempty"`
	Language       string                 `protobuf:"bytes,5,opt,name=Language,proto3" json:"Language,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *PasskeysFinishRegistrationReq) Reset() {
	*x = PasskeysFinishRegistrationReq{}
	mi := &file_apollo_rpc_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PasskeysFinishRegistrationReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PasskeysFinishRegistrationReq) ProtoMessage() {}

func (x *PasskeysFinishRegistrationReq) ProtoReflect() protoreflect.Message {
	mi := &file_apollo_rpc_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PasskeysFinishRegistrationReq.ProtoReflect.Descriptor instead.
func (*PasskeysFinishRegistrationReq) Descriptor() ([]byte, []int) {
	return file_apollo_rpc_proto_rawDescGZIP(), []int{13}
}

func (x *PasskeysFinishRegistrationReq) GetUserId() int64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *PasskeysFinishRegistrationReq) GetCredentialJson() []byte {
	if x != nil {
		return x.CredentialJson
	}
	return nil
}

func (x *PasskeysFinishRegistrationReq) GetSessionData() []byte {
	if x != nil {
		return x.SessionData
	}
	return nil
}

func (x *PasskeysFinishRegistrationReq) GetLocate() string {
	if x != nil {
		return x.Locate
	}
	return ""
}

func (x *PasskeysFinishRegistrationReq) GetLanguage() string {
	if x != nil {
		return x.Language
	}
	return ""
}

// ========== 登录流程 ==========
type PasskeysStartLoginResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	OptionsJson   []byte                 `protobuf:"bytes,1,opt,name=options_json,json=optionsJson,proto3" json:"options_json,omitempty"`
	SessionData   []byte                 `protobuf:"bytes,2,opt,name=session_data,json=sessionData,proto3" json:"session_data,omitempty"` // 必须返回给API存储
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PasskeysStartLoginResp) Reset() {
	*x = PasskeysStartLoginResp{}
	mi := &file_apollo_rpc_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PasskeysStartLoginResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PasskeysStartLoginResp) ProtoMessage() {}

func (x *PasskeysStartLoginResp) ProtoReflect() protoreflect.Message {
	mi := &file_apollo_rpc_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PasskeysStartLoginResp.ProtoReflect.Descriptor instead.
func (*PasskeysStartLoginResp) Descriptor() ([]byte, []int) {
	return file_apollo_rpc_proto_rawDescGZIP(), []int{14}
}

func (x *PasskeysStartLoginResp) GetOptionsJson() []byte {
	if x != nil {
		return x.OptionsJson
	}
	return nil
}

func (x *PasskeysStartLoginResp) GetSessionData() []byte {
	if x != nil {
		return x.SessionData
	}
	return nil
}

type PasskeysFinishLoginReq struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	CredentialJson  string                 `protobuf:"bytes,1,opt,name=credential_json,json=credentialJson,proto3" json:"credential_json,omitempty"`      // 前端原始JSON
	SessionDataJson string                 `protobuf:"bytes,2,opt,name=session_data_json,json=sessionDataJson,proto3" json:"session_data_json,omitempty"` // StartLogin返回的session_data
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *PasskeysFinishLoginReq) Reset() {
	*x = PasskeysFinishLoginReq{}
	mi := &file_apollo_rpc_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PasskeysFinishLoginReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PasskeysFinishLoginReq) ProtoMessage() {}

func (x *PasskeysFinishLoginReq) ProtoReflect() protoreflect.Message {
	mi := &file_apollo_rpc_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PasskeysFinishLoginReq.ProtoReflect.Descriptor instead.
func (*PasskeysFinishLoginReq) Descriptor() ([]byte, []int) {
	return file_apollo_rpc_proto_rawDescGZIP(), []int{15}
}

func (x *PasskeysFinishLoginReq) GetCredentialJson() string {
	if x != nil {
		return x.CredentialJson
	}
	return ""
}

func (x *PasskeysFinishLoginReq) GetSessionDataJson() string {
	if x != nil {
		return x.SessionDataJson
	}
	return ""
}

type PasskeysFinishLoginResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        int64                  `protobuf:"varint,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"` // JUS User ID
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PasskeysFinishLoginResp) Reset() {
	*x = PasskeysFinishLoginResp{}
	mi := &file_apollo_rpc_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PasskeysFinishLoginResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PasskeysFinishLoginResp) ProtoMessage() {}

func (x *PasskeysFinishLoginResp) ProtoReflect() protoreflect.Message {
	mi := &file_apollo_rpc_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PasskeysFinishLoginResp.ProtoReflect.Descriptor instead.
func (*PasskeysFinishLoginResp) Descriptor() ([]byte, []int) {
	return file_apollo_rpc_proto_rawDescGZIP(), []int{16}
}

func (x *PasskeysFinishLoginResp) GetUserId() int64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

// Third-Party
// ========== 绑定流程 ==========
type ThirdPartyBindReq struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// int64 user_id = 1;          // API生成
	Token         []byte `protobuf:"bytes,1,opt,name=token,proto3" json:"token,omitempty"` //  string raw_data_json = 2;       // API提供
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ThirdPartyBindReq) Reset() {
	*x = ThirdPartyBindReq{}
	mi := &file_apollo_rpc_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ThirdPartyBindReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ThirdPartyBindReq) ProtoMessage() {}

func (x *ThirdPartyBindReq) ProtoReflect() protoreflect.Message {
	mi := &file_apollo_rpc_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ThirdPartyBindReq.ProtoReflect.Descriptor instead.
func (*ThirdPartyBindReq) Descriptor() ([]byte, []int) {
	return file_apollo_rpc_proto_rawDescGZIP(), []int{17}
}

func (x *ThirdPartyBindReq) GetToken() []byte {
	if x != nil {
		return x.Token
	}
	return nil
}

// ========== 继续流程 ==========
type ThirdPartyContinueReq struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// int64 id = 1;
	Provider      string `protobuf:"bytes,1,opt,name=provider,proto3" json:"provider,omitempty"`
	Token         []byte `protobuf:"bytes,2,opt,name=token,proto3" json:"token,omitempty"`
	RedisDataJson string `protobuf:"bytes,3,opt,name=redis_data_json,json=redisDataJson,proto3" json:"redis_data_json,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ThirdPartyContinueReq) Reset() {
	*x = ThirdPartyContinueReq{}
	mi := &file_apollo_rpc_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ThirdPartyContinueReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ThirdPartyContinueReq) ProtoMessage() {}

func (x *ThirdPartyContinueReq) ProtoReflect() protoreflect.Message {
	mi := &file_apollo_rpc_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ThirdPartyContinueReq.ProtoReflect.Descriptor instead.
func (*ThirdPartyContinueReq) Descriptor() ([]byte, []int) {
	return file_apollo_rpc_proto_rawDescGZIP(), []int{18}
}

func (x *ThirdPartyContinueReq) GetProvider() string {
	if x != nil {
		return x.Provider
	}
	return ""
}

func (x *ThirdPartyContinueReq) GetToken() []byte {
	if x != nil {
		return x.Token
	}
	return nil
}

func (x *ThirdPartyContinueReq) GetRedisDataJson() string {
	if x != nil {
		return x.RedisDataJson
	}
	return ""
}

type ThirdPartyContinueResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        int64                  `protobuf:"varint,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"` // API提供
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ThirdPartyContinueResp) Reset() {
	*x = ThirdPartyContinueResp{}
	mi := &file_apollo_rpc_proto_msgTypes[19]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ThirdPartyContinueResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ThirdPartyContinueResp) ProtoMessage() {}

func (x *ThirdPartyContinueResp) ProtoReflect() protoreflect.Message {
	mi := &file_apollo_rpc_proto_msgTypes[19]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ThirdPartyContinueResp.ProtoReflect.Descriptor instead.
func (*ThirdPartyContinueResp) Descriptor() ([]byte, []int) {
	return file_apollo_rpc_proto_rawDescGZIP(), []int{19}
}

func (x *ThirdPartyContinueResp) GetUserId() int64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

// ========== 生成子系统令牌 ==========
type GenerateSubsystemTokenReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        int64                  `protobuf:"varint,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Scope         []byte                 `protobuf:"bytes,3,opt,name=scope,proto3" json:"scope,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GenerateSubsystemTokenReq) Reset() {
	*x = GenerateSubsystemTokenReq{}
	mi := &file_apollo_rpc_proto_msgTypes[20]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GenerateSubsystemTokenReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GenerateSubsystemTokenReq) ProtoMessage() {}

func (x *GenerateSubsystemTokenReq) ProtoReflect() protoreflect.Message {
	mi := &file_apollo_rpc_proto_msgTypes[20]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GenerateSubsystemTokenReq.ProtoReflect.Descriptor instead.
func (*GenerateSubsystemTokenReq) Descriptor() ([]byte, []int) {
	return file_apollo_rpc_proto_rawDescGZIP(), []int{20}
}

func (x *GenerateSubsystemTokenReq) GetUserId() int64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *GenerateSubsystemTokenReq) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *GenerateSubsystemTokenReq) GetScope() []byte {
	if x != nil {
		return x.Scope
	}
	return nil
}

type GenerateSubsystemTokenResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Token         *SubsystemToken        `protobuf:"bytes,1,opt,name=token,proto3" json:"token,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GenerateSubsystemTokenResp) Reset() {
	*x = GenerateSubsystemTokenResp{}
	mi := &file_apollo_rpc_proto_msgTypes[21]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GenerateSubsystemTokenResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GenerateSubsystemTokenResp) ProtoMessage() {}

func (x *GenerateSubsystemTokenResp) ProtoReflect() protoreflect.Message {
	mi := &file_apollo_rpc_proto_msgTypes[21]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GenerateSubsystemTokenResp.ProtoReflect.Descriptor instead.
func (*GenerateSubsystemTokenResp) Descriptor() ([]byte, []int) {
	return file_apollo_rpc_proto_rawDescGZIP(), []int{21}
}

func (x *GenerateSubsystemTokenResp) GetToken() *SubsystemToken {
	if x != nil {
		return x.Token
	}
	return nil
}

// 子系统令牌
type SubsystemToken struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Value         string                 `protobuf:"bytes,2,opt,name=value,proto3" json:"value,omitempty"`
	Name          string                 `protobuf:"bytes,3,opt,name=name,proto3" json:"name,omitempty"`
	Year          int64                  `protobuf:"varint,4,opt,name=year,proto3" json:"year,omitempty"`
	Month         int64                  `protobuf:"varint,5,opt,name=month,proto3" json:"month,omitempty"`
	Day           int64                  `protobuf:"varint,6,opt,name=day,proto3" json:"day,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SubsystemToken) Reset() {
	*x = SubsystemToken{}
	mi := &file_apollo_rpc_proto_msgTypes[22]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SubsystemToken) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SubsystemToken) ProtoMessage() {}

func (x *SubsystemToken) ProtoReflect() protoreflect.Message {
	mi := &file_apollo_rpc_proto_msgTypes[22]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SubsystemToken.ProtoReflect.Descriptor instead.
func (*SubsystemToken) Descriptor() ([]byte, []int) {
	return file_apollo_rpc_proto_rawDescGZIP(), []int{22}
}

func (x *SubsystemToken) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *SubsystemToken) GetValue() string {
	if x != nil {
		return x.Value
	}
	return ""
}

func (x *SubsystemToken) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *SubsystemToken) GetYear() int64 {
	if x != nil {
		return x.Year
	}
	return 0
}

func (x *SubsystemToken) GetMonth() int64 {
	if x != nil {
		return x.Month
	}
	return 0
}

func (x *SubsystemToken) GetDay() int64 {
	if x != nil {
		return x.Day
	}
	return 0
}

// ========== 验证子系统令牌 ==========
type ValidateSubsystemTokenReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        int64                  `protobuf:"varint,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	TokenId       int64                  `protobuf:"varint,2,opt,name=token_id,json=tokenId,proto3" json:"token_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ValidateSubsystemTokenReq) Reset() {
	*x = ValidateSubsystemTokenReq{}
	mi := &file_apollo_rpc_proto_msgTypes[23]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ValidateSubsystemTokenReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ValidateSubsystemTokenReq) ProtoMessage() {}

func (x *ValidateSubsystemTokenReq) ProtoReflect() protoreflect.Message {
	mi := &file_apollo_rpc_proto_msgTypes[23]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ValidateSubsystemTokenReq.ProtoReflect.Descriptor instead.
func (*ValidateSubsystemTokenReq) Descriptor() ([]byte, []int) {
	return file_apollo_rpc_proto_rawDescGZIP(), []int{23}
}

func (x *ValidateSubsystemTokenReq) GetUserId() int64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *ValidateSubsystemTokenReq) GetTokenId() int64 {
	if x != nil {
		return x.TokenId
	}
	return 0
}

type ValidateSubsystemTokenResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Validated     bool                   `protobuf:"varint,1,opt,name=validated,proto3" json:"validated,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ValidateSubsystemTokenResp) Reset() {
	*x = ValidateSubsystemTokenResp{}
	mi := &file_apollo_rpc_proto_msgTypes[24]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ValidateSubsystemTokenResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ValidateSubsystemTokenResp) ProtoMessage() {}

func (x *ValidateSubsystemTokenResp) ProtoReflect() protoreflect.Message {
	mi := &file_apollo_rpc_proto_msgTypes[24]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ValidateSubsystemTokenResp.ProtoReflect.Descriptor instead.
func (*ValidateSubsystemTokenResp) Descriptor() ([]byte, []int) {
	return file_apollo_rpc_proto_rawDescGZIP(), []int{24}
}

func (x *ValidateSubsystemTokenResp) GetValidated() bool {
	if x != nil {
		return x.Validated
	}
	return false
}

// ========== 移除子系统令牌 ==========
type RemoveSubsystemTokenReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TokenId       string                 `protobuf:"bytes,1,opt,name=token_id,json=tokenId,proto3" json:"token_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RemoveSubsystemTokenReq) Reset() {
	*x = RemoveSubsystemTokenReq{}
	mi := &file_apollo_rpc_proto_msgTypes[25]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RemoveSubsystemTokenReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RemoveSubsystemTokenReq) ProtoMessage() {}

func (x *RemoveSubsystemTokenReq) ProtoReflect() protoreflect.Message {
	mi := &file_apollo_rpc_proto_msgTypes[25]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RemoveSubsystemTokenReq.ProtoReflect.Descriptor instead.
func (*RemoveSubsystemTokenReq) Descriptor() ([]byte, []int) {
	return file_apollo_rpc_proto_rawDescGZIP(), []int{25}
}

func (x *RemoveSubsystemTokenReq) GetTokenId() string {
	if x != nil {
		return x.TokenId
	}
	return ""
}

type RemoveSubsystemTokenResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Validated     bool                   `protobuf:"varint,1,opt,name=validated,proto3" json:"validated,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RemoveSubsystemTokenResp) Reset() {
	*x = RemoveSubsystemTokenResp{}
	mi := &file_apollo_rpc_proto_msgTypes[26]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RemoveSubsystemTokenResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RemoveSubsystemTokenResp) ProtoMessage() {}

func (x *RemoveSubsystemTokenResp) ProtoReflect() protoreflect.Message {
	mi := &file_apollo_rpc_proto_msgTypes[26]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RemoveSubsystemTokenResp.ProtoReflect.Descriptor instead.
func (*RemoveSubsystemTokenResp) Descriptor() ([]byte, []int) {
	return file_apollo_rpc_proto_rawDescGZIP(), []int{26}
}

func (x *RemoveSubsystemTokenResp) GetValidated() bool {
	if x != nil {
		return x.Validated
	}
	return false
}

// ========== 查询子系统令牌 ==========
type FindTenSubsystemTokensReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        int64                  `protobuf:"varint,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Page          int64                  `protobuf:"varint,2,opt,name=page,proto3" json:"page,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FindTenSubsystemTokensReq) Reset() {
	*x = FindTenSubsystemTokensReq{}
	mi := &file_apollo_rpc_proto_msgTypes[27]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FindTenSubsystemTokensReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FindTenSubsystemTokensReq) ProtoMessage() {}

func (x *FindTenSubsystemTokensReq) ProtoReflect() protoreflect.Message {
	mi := &file_apollo_rpc_proto_msgTypes[27]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FindTenSubsystemTokensReq.ProtoReflect.Descriptor instead.
func (*FindTenSubsystemTokensReq) Descriptor() ([]byte, []int) {
	return file_apollo_rpc_proto_rawDescGZIP(), []int{27}
}

func (x *FindTenSubsystemTokensReq) GetUserId() int64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *FindTenSubsystemTokensReq) GetPage() int64 {
	if x != nil {
		return x.Page
	}
	return 0
}

type FindTenSubsystemTokensResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Tokens        []*SubsystemToken      `protobuf:"bytes,1,rep,name=tokens,proto3" json:"tokens,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FindTenSubsystemTokensResp) Reset() {
	*x = FindTenSubsystemTokensResp{}
	mi := &file_apollo_rpc_proto_msgTypes[28]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FindTenSubsystemTokensResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FindTenSubsystemTokensResp) ProtoMessage() {}

func (x *FindTenSubsystemTokensResp) ProtoReflect() protoreflect.Message {
	mi := &file_apollo_rpc_proto_msgTypes[28]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FindTenSubsystemTokensResp.ProtoReflect.Descriptor instead.
func (*FindTenSubsystemTokensResp) Descriptor() ([]byte, []int) {
	return file_apollo_rpc_proto_rawDescGZIP(), []int{28}
}

func (x *FindTenSubsystemTokensResp) GetTokens() []*SubsystemToken {
	if x != nil {
		return x.Tokens
	}
	return nil
}

var File_apollo_rpc_proto protoreflect.FileDescriptor

const file_apollo_rpc_proto_rawDesc = "" +
	"\n" +
	"\x10apollo-rpc.proto\x12\x06apollo\"\a\n" +
	"\x05Empty\"\x90\x01\n" +
	"\x0fRegistrationReq\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\x03R\x06userId\x12\x14\n" +
	"\x05email\x18\x02 \x01(\tR\x05email\x12\x1a\n" +
	"\bpassword\x18\x03 \x01(\tR\bpassword\x12\x16\n" +
	"\x06locate\x18\x04 \x01(\tR\x06locate\x12\x1a\n" +
	"\blanguage\x18\x05 \x01(\tR\blanguage\"<\n" +
	"\bLoginReq\x12\x14\n" +
	"\x05email\x18\x01 \x01(\tR\x05email\x12\x1a\n" +
	"\bpassword\x18\x02 \x01(\tR\bpassword\"\xc0\x02\n" +
	"\tLoginResp\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\x03R\x06userId\x12\x1d\n" +
	"\n" +
	"given_name\x18\x02 \x01(\tR\tgivenName\x12\x1f\n" +
	"\vmiddle_name\x18\x03 \x01(\tR\n" +
	"middleName\x12\x1f\n" +
	"\vfamily_name\x18\x04 \x01(\tR\n" +
	"familyName\x12\x16\n" +
	"\x06avatar\x18\x05 \x01(\tR\x06avatar\x12\x16\n" +
	"\x06locale\x18\x06 \x01(\tR\x06locale\x12\x1a\n" +
	"\blanguage\x18\a \x01(\tR\blanguage\x12#\n" +
	"\rbirthday_year\x18\b \x01(\x03R\fbirthdayYear\x12%\n" +
	"\x0ebirthday_month\x18\t \x01(\x03R\rbirthdayMonth\x12!\n" +
	"\fbirthday_day\x18\n" +
	" \x01(\x03R\vbirthdayDay\"&\n" +
	"\vUserInfoReq\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\x03R\x06userId\"-\n" +
	"\fUserInfoResp\x12\x1d\n" +
	"\n" +
	"user_bytes\x18\x01 \x01(\fR\tuserBytes\".\n" +
	"\x13UserSecurityInfoReq\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\x03R\x06userId\"j\n" +
	"\vUserContact\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value\x12\x12\n" +
	"\x04type\x18\x03 \x01(\x03R\x04type\x12!\n" +
	"\fphone_region\x18\x04 \x01(\tR\vphoneRegion\"Q\n" +
	"\x13PasswordUpdatedDate\x12\x12\n" +
	"\x04year\x18\x01 \x01(\x03R\x04year\x12\x14\n" +
	"\x05month\x18\x02 \x01(\x03R\x05month\x12\x10\n" +
	"\x03day\x18\x03 \x01(\x03R\x03day\"D\n" +
	"\x12ThirdPartyAccounts\x12\x16\n" +
	"\x06github\x18\x01 \x01(\bR\x06github\x12\x16\n" +
	"\x06google\x18\x02 \x01(\bR\x06google\"\xc6\x02\n" +
	"\x14UserSecurityInfoResp\x12/\n" +
	"\bcontacts\x18\x01 \x03(\v2\x13.apollo.UserContactR\bcontacts\x12O\n" +
	"\x15password_updated_date\x18\x02 \x01(\v2\x1b.apollo.PasswordUpdatedDateR\x13passwordUpdatedDate\x12;\n" +
	"\x1aaccount_security_token_num\x18\x03 \x01(\x03R\x17accountSecurityTokenNum\x12!\n" +
	"\fpasskeys_num\x18\x04 \x01(\x03R\vpasskeysNum\x12L\n" +
	"\x14third_party_accounts\x18\x05 \x01(\v2\x1a.apollo.ThirdPartyAccountsR\x12thirdPartyAccounts\"w\n" +
	"\x1cPasskeysStartRegistrationReq\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\x03R\x06userId\x12\x1b\n" +
	"\tuser_name\x18\x02 \x01(\tR\buserName\x12!\n" +
	"\fdisplay_name\x18\x03 \x01(\tR\vdisplayName\"e\n" +
	"\x1dPasskeysStartRegistrationResp\x12!\n" +
	"\foptions_json\x18\x01 \x01(\fR\voptionsJson\x12!\n" +
	"\fsession_data\x18\x02 \x01(\fR\vsessionData\"\xb8\x01\n" +
	"\x1dPasskeysFinishRegistrationReq\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\x03R\x06userId\x12'\n" +
	"\x0fcredential_json\x18\x02 \x01(\fR\x0ecredentialJson\x12!\n" +
	"\fsession_data\x18\x03 \x01(\fR\vsessionData\x12\x16\n" +
	"\x06Locate\x18\x04 \x01(\tR\x06Locate\x12\x1a\n" +
	"\bLanguage\x18\x05 \x01(\tR\bLanguage\"^\n" +
	"\x16PasskeysStartLoginResp\x12!\n" +
	"\foptions_json\x18\x01 \x01(\fR\voptionsJson\x12!\n" +
	"\fsession_data\x18\x02 \x01(\fR\vsessionData\"m\n" +
	"\x16PasskeysFinishLoginReq\x12'\n" +
	"\x0fcredential_json\x18\x01 \x01(\tR\x0ecredentialJson\x12*\n" +
	"\x11session_data_json\x18\x02 \x01(\tR\x0fsessionDataJson\"2\n" +
	"\x17PasskeysFinishLoginResp\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\x03R\x06userId\")\n" +
	"\x11ThirdPartyBindReq\x12\x14\n" +
	"\x05token\x18\x01 \x01(\fR\x05token\"q\n" +
	"\x15ThirdPartyContinueReq\x12\x1a\n" +
	"\bprovider\x18\x01 \x01(\tR\bprovider\x12\x14\n" +
	"\x05token\x18\x02 \x01(\fR\x05token\x12&\n" +
	"\x0fredis_data_json\x18\x03 \x01(\tR\rredisDataJson\"1\n" +
	"\x16ThirdPartyContinueResp\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\x03R\x06userId\"^\n" +
	"\x19GenerateSubsystemTokenReq\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\x03R\x06userId\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x14\n" +
	"\x05scope\x18\x03 \x01(\fR\x05scope\"J\n" +
	"\x1aGenerateSubsystemTokenResp\x12,\n" +
	"\x05token\x18\x01 \x01(\v2\x16.apollo.SubsystemTokenR\x05token\"\x86\x01\n" +
	"\x0eSubsystemToken\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value\x12\x12\n" +
	"\x04name\x18\x03 \x01(\tR\x04name\x12\x12\n" +
	"\x04year\x18\x04 \x01(\x03R\x04year\x12\x14\n" +
	"\x05month\x18\x05 \x01(\x03R\x05month\x12\x10\n" +
	"\x03day\x18\x06 \x01(\x03R\x03day\"O\n" +
	"\x19ValidateSubsystemTokenReq\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\x03R\x06userId\x12\x19\n" +
	"\btoken_id\x18\x02 \x01(\x03R\atokenId\":\n" +
	"\x1aValidateSubsystemTokenResp\x12\x1c\n" +
	"\tvalidated\x18\x01 \x01(\bR\tvalidated\"4\n" +
	"\x17RemoveSubsystemTokenReq\x12\x19\n" +
	"\btoken_id\x18\x01 \x01(\tR\atokenId\"8\n" +
	"\x18RemoveSubsystemTokenResp\x12\x1c\n" +
	"\tvalidated\x18\x01 \x01(\bR\tvalidated\"H\n" +
	"\x19FindTenSubsystemTokensReq\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\x03R\x06userId\x12\x12\n" +
	"\x04page\x18\x02 \x01(\x03R\x04page\"L\n" +
	"\x1aFindTenSubsystemTokensResp\x12.\n" +
	"\x06tokens\x18\x01 \x03(\v2\x16.apollo.SubsystemTokenR\x06tokens2\xf5\x01\n" +
	"\aAccount\x126\n" +
	"\fRegistration\x12\x17.apollo.RegistrationReq\x1a\r.apollo.Empty\x12,\n" +
	"\x05Login\x12\x10.apollo.LoginReq\x1a\x11.apollo.LoginResp\x125\n" +
	"\bUserInfo\x12\x13.apollo.UserInfoReq\x1a\x14.apollo.UserInfoResp\x12M\n" +
	"\x10UserSecurityInfo\x12\x1b.apollo.UserSecurityInfoReq\x1a\x1c.apollo.UserSecurityInfoResp2\xc5\x02\n" +
	"\bPasskeys\x12`\n" +
	"\x11StartRegistration\x12$.apollo.PasskeysStartRegistrationReq\x1a%.apollo.PasskeysStartRegistrationResp\x12J\n" +
	"\x12FinishRegistration\x12%.apollo.PasskeysFinishRegistrationReq\x1a\r.apollo.Empty\x12;\n" +
	"\n" +
	"StartLogin\x12\r.apollo.Empty\x1a\x1e.apollo.PasskeysStartLoginResp\x12N\n" +
	"\vFinishLogin\x12\x1e.apollo.PasskeysFinishLoginReq\x1a\x1f.apollo.PasskeysFinishLoginResp2\xda\x01\n" +
	"\n" +
	"ThirdParty\x120\n" +
	"\x04Bind\x12\x19.apollo.ThirdPartyBindReq\x1a\r.apollo.Empty\x12I\n" +
	"\bContinue\x12\x1d.apollo.ThirdPartyContinueReq\x1a\x1e.apollo.ThirdPartyContinueResp\x12O\n" +
	"\x0eHandleCallback\x12\x1d.apollo.ThirdPartyContinueReq\x1a\x1e.apollo.ThirdPartyContinueResp2\x88\x03\n" +
	"\bSecurity\x12_\n" +
	"\x16GenerateSubsystemToken\x12!.apollo.GenerateSubsystemTokenReq\x1a\".apollo.GenerateSubsystemTokenResp\x12_\n" +
	"\x16ValidateSubsystemToken\x12!.apollo.ValidateSubsystemTokenReq\x1a\".apollo.ValidateSubsystemTokenResp\x12Y\n" +
	"\x14RemoveSubsystemToken\x12\x1f.apollo.RemoveSubsystemTokenReq\x1a .apollo.RemoveSubsystemTokenResp\x12_\n" +
	"\x16FindTenSubsystemTokens\x12!.apollo.FindTenSubsystemTokensReq\x1a\".apollo.FindTenSubsystemTokensRespB\n" +
	"Z\b./apollob\x06proto3"

var (
	file_apollo_rpc_proto_rawDescOnce sync.Once
	file_apollo_rpc_proto_rawDescData []byte
)

func file_apollo_rpc_proto_rawDescGZIP() []byte {
	file_apollo_rpc_proto_rawDescOnce.Do(func() {
		file_apollo_rpc_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_apollo_rpc_proto_rawDesc), len(file_apollo_rpc_proto_rawDesc)))
	})
	return file_apollo_rpc_proto_rawDescData
}

var file_apollo_rpc_proto_msgTypes = make([]protoimpl.MessageInfo, 29)
var file_apollo_rpc_proto_goTypes = []any{
	(*Empty)(nil),                         // 0: apollo.Empty
	(*RegistrationReq)(nil),               // 1: apollo.RegistrationReq
	(*LoginReq)(nil),                      // 2: apollo.LoginReq
	(*LoginResp)(nil),                     // 3: apollo.LoginResp
	(*UserInfoReq)(nil),                   // 4: apollo.UserInfoReq
	(*UserInfoResp)(nil),                  // 5: apollo.UserInfoResp
	(*UserSecurityInfoReq)(nil),           // 6: apollo.UserSecurityInfoReq
	(*UserContact)(nil),                   // 7: apollo.UserContact
	(*PasswordUpdatedDate)(nil),           // 8: apollo.PasswordUpdatedDate
	(*ThirdPartyAccounts)(nil),            // 9: apollo.ThirdPartyAccounts
	(*UserSecurityInfoResp)(nil),          // 10: apollo.UserSecurityInfoResp
	(*PasskeysStartRegistrationReq)(nil),  // 11: apollo.PasskeysStartRegistrationReq
	(*PasskeysStartRegistrationResp)(nil), // 12: apollo.PasskeysStartRegistrationResp
	(*PasskeysFinishRegistrationReq)(nil), // 13: apollo.PasskeysFinishRegistrationReq
	(*PasskeysStartLoginResp)(nil),        // 14: apollo.PasskeysStartLoginResp
	(*PasskeysFinishLoginReq)(nil),        // 15: apollo.PasskeysFinishLoginReq
	(*PasskeysFinishLoginResp)(nil),       // 16: apollo.PasskeysFinishLoginResp
	(*ThirdPartyBindReq)(nil),             // 17: apollo.ThirdPartyBindReq
	(*ThirdPartyContinueReq)(nil),         // 18: apollo.ThirdPartyContinueReq
	(*ThirdPartyContinueResp)(nil),        // 19: apollo.ThirdPartyContinueResp
	(*GenerateSubsystemTokenReq)(nil),     // 20: apollo.GenerateSubsystemTokenReq
	(*GenerateSubsystemTokenResp)(nil),    // 21: apollo.GenerateSubsystemTokenResp
	(*SubsystemToken)(nil),                // 22: apollo.SubsystemToken
	(*ValidateSubsystemTokenReq)(nil),     // 23: apollo.ValidateSubsystemTokenReq
	(*ValidateSubsystemTokenResp)(nil),    // 24: apollo.ValidateSubsystemTokenResp
	(*RemoveSubsystemTokenReq)(nil),       // 25: apollo.RemoveSubsystemTokenReq
	(*RemoveSubsystemTokenResp)(nil),      // 26: apollo.RemoveSubsystemTokenResp
	(*FindTenSubsystemTokensReq)(nil),     // 27: apollo.FindTenSubsystemTokensReq
	(*FindTenSubsystemTokensResp)(nil),    // 28: apollo.FindTenSubsystemTokensResp
}
var file_apollo_rpc_proto_depIdxs = []int32{
	7,  // 0: apollo.UserSecurityInfoResp.contacts:type_name -> apollo.UserContact
	8,  // 1: apollo.UserSecurityInfoResp.password_updated_date:type_name -> apollo.PasswordUpdatedDate
	9,  // 2: apollo.UserSecurityInfoResp.third_party_accounts:type_name -> apollo.ThirdPartyAccounts
	22, // 3: apollo.GenerateSubsystemTokenResp.token:type_name -> apollo.SubsystemToken
	22, // 4: apollo.FindTenSubsystemTokensResp.tokens:type_name -> apollo.SubsystemToken
	1,  // 5: apollo.Account.Registration:input_type -> apollo.RegistrationReq
	2,  // 6: apollo.Account.Login:input_type -> apollo.LoginReq
	4,  // 7: apollo.Account.UserInfo:input_type -> apollo.UserInfoReq
	6,  // 8: apollo.Account.UserSecurityInfo:input_type -> apollo.UserSecurityInfoReq
	11, // 9: apollo.Passkeys.StartRegistration:input_type -> apollo.PasskeysStartRegistrationReq
	13, // 10: apollo.Passkeys.FinishRegistration:input_type -> apollo.PasskeysFinishRegistrationReq
	0,  // 11: apollo.Passkeys.StartLogin:input_type -> apollo.Empty
	15, // 12: apollo.Passkeys.FinishLogin:input_type -> apollo.PasskeysFinishLoginReq
	17, // 13: apollo.ThirdParty.Bind:input_type -> apollo.ThirdPartyBindReq
	18, // 14: apollo.ThirdParty.Continue:input_type -> apollo.ThirdPartyContinueReq
	18, // 15: apollo.ThirdParty.HandleCallback:input_type -> apollo.ThirdPartyContinueReq
	20, // 16: apollo.Security.GenerateSubsystemToken:input_type -> apollo.GenerateSubsystemTokenReq
	23, // 17: apollo.Security.ValidateSubsystemToken:input_type -> apollo.ValidateSubsystemTokenReq
	25, // 18: apollo.Security.RemoveSubsystemToken:input_type -> apollo.RemoveSubsystemTokenReq
	27, // 19: apollo.Security.FindTenSubsystemTokens:input_type -> apollo.FindTenSubsystemTokensReq
	0,  // 20: apollo.Account.Registration:output_type -> apollo.Empty
	3,  // 21: apollo.Account.Login:output_type -> apollo.LoginResp
	5,  // 22: apollo.Account.UserInfo:output_type -> apollo.UserInfoResp
	10, // 23: apollo.Account.UserSecurityInfo:output_type -> apollo.UserSecurityInfoResp
	12, // 24: apollo.Passkeys.StartRegistration:output_type -> apollo.PasskeysStartRegistrationResp
	0,  // 25: apollo.Passkeys.FinishRegistration:output_type -> apollo.Empty
	14, // 26: apollo.Passkeys.StartLogin:output_type -> apollo.PasskeysStartLoginResp
	16, // 27: apollo.Passkeys.FinishLogin:output_type -> apollo.PasskeysFinishLoginResp
	0,  // 28: apollo.ThirdParty.Bind:output_type -> apollo.Empty
	19, // 29: apollo.ThirdParty.Continue:output_type -> apollo.ThirdPartyContinueResp
	19, // 30: apollo.ThirdParty.HandleCallback:output_type -> apollo.ThirdPartyContinueResp
	21, // 31: apollo.Security.GenerateSubsystemToken:output_type -> apollo.GenerateSubsystemTokenResp
	24, // 32: apollo.Security.ValidateSubsystemToken:output_type -> apollo.ValidateSubsystemTokenResp
	26, // 33: apollo.Security.RemoveSubsystemToken:output_type -> apollo.RemoveSubsystemTokenResp
	28, // 34: apollo.Security.FindTenSubsystemTokens:output_type -> apollo.FindTenSubsystemTokensResp
	20, // [20:35] is the sub-list for method output_type
	5,  // [5:20] is the sub-list for method input_type
	5,  // [5:5] is the sub-list for extension type_name
	5,  // [5:5] is the sub-list for extension extendee
	0,  // [0:5] is the sub-list for field type_name
}

func init() { file_apollo_rpc_proto_init() }
func file_apollo_rpc_proto_init() {
	if File_apollo_rpc_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_apollo_rpc_proto_rawDesc), len(file_apollo_rpc_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   29,
			NumExtensions: 0,
			NumServices:   4,
		},
		GoTypes:           file_apollo_rpc_proto_goTypes,
		DependencyIndexes: file_apollo_rpc_proto_depIdxs,
		MessageInfos:      file_apollo_rpc_proto_msgTypes,
	}.Build()
	File_apollo_rpc_proto = out.File
	file_apollo_rpc_proto_goTypes = nil
	file_apollo_rpc_proto_depIdxs = nil
}
