// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v3.19.4
// source: apollo.proto

package apollo

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// ========== 注册流程 ==========
type StartRegistrationReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        int64                  `protobuf:"varint,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`               // API生成
	UserName      string                 `protobuf:"bytes,2,opt,name=user_name,json=userName,proto3" json:"user_name,omitempty"`          // API提供
	DisplayName   string                 `protobuf:"bytes,3,opt,name=display_name,json=displayName,proto3" json:"display_name,omitempty"` // API提供
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StartRegistrationReq) Reset() {
	*x = StartRegistrationReq{}
	mi := &file_apollo_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StartRegistrationReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StartRegistrationReq) ProtoMessage() {}

func (x *StartRegistrationReq) ProtoReflect() protoreflect.Message {
	mi := &file_apollo_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StartRegistrationReq.ProtoReflect.Descriptor instead.
func (*StartRegistrationReq) Descriptor() ([]byte, []int) {
	return file_apollo_proto_rawDescGZIP(), []int{0}
}

func (x *StartRegistrationReq) GetUserId() int64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *StartRegistrationReq) GetUserName() string {
	if x != nil {
		return x.UserName
	}
	return ""
}

func (x *StartRegistrationReq) GetDisplayName() string {
	if x != nil {
		return x.DisplayName
	}
	return ""
}

type StartRegistrationResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	OptionsJson   []byte                 `protobuf:"bytes,1,opt,name=options_json,json=optionsJson,proto3" json:"options_json,omitempty"` // WebAuthn标准选项
	SessionData   []byte                 `protobuf:"bytes,2,opt,name=session_data,json=sessionData,proto3" json:"session_data,omitempty"` // 序列化的SessionData（API需存储）
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StartRegistrationResp) Reset() {
	*x = StartRegistrationResp{}
	mi := &file_apollo_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StartRegistrationResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StartRegistrationResp) ProtoMessage() {}

func (x *StartRegistrationResp) ProtoReflect() protoreflect.Message {
	mi := &file_apollo_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StartRegistrationResp.ProtoReflect.Descriptor instead.
func (*StartRegistrationResp) Descriptor() ([]byte, []int) {
	return file_apollo_proto_rawDescGZIP(), []int{1}
}

func (x *StartRegistrationResp) GetOptionsJson() []byte {
	if x != nil {
		return x.OptionsJson
	}
	return nil
}

func (x *StartRegistrationResp) GetSessionData() []byte {
	if x != nil {
		return x.SessionData
	}
	return nil
}

type FinishRegistrationReq struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	UserId         int64                  `protobuf:"varint,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`                        // 必须与StartRegistration一致
	CredentialJson []byte                 `protobuf:"bytes,2,opt,name=credential_json,json=credentialJson,proto3" json:"credential_json,omitempty"` // 前端返回的完整认证数据
	SessionData    []byte                 `protobuf:"bytes,3,opt,name=session_data,json=sessionData,proto3" json:"session_data,omitempty"`          // 新增：StartRegistration返回的session_data
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *FinishRegistrationReq) Reset() {
	*x = FinishRegistrationReq{}
	mi := &file_apollo_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FinishRegistrationReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FinishRegistrationReq) ProtoMessage() {}

func (x *FinishRegistrationReq) ProtoReflect() protoreflect.Message {
	mi := &file_apollo_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FinishRegistrationReq.ProtoReflect.Descriptor instead.
func (*FinishRegistrationReq) Descriptor() ([]byte, []int) {
	return file_apollo_proto_rawDescGZIP(), []int{2}
}

func (x *FinishRegistrationReq) GetUserId() int64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *FinishRegistrationReq) GetCredentialJson() []byte {
	if x != nil {
		return x.CredentialJson
	}
	return nil
}

func (x *FinishRegistrationReq) GetSessionData() []byte {
	if x != nil {
		return x.SessionData
	}
	return nil
}

type FinishRegistrationResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	CredentialId  []byte                 `protobuf:"bytes,1,opt,name=credential_id,json=credentialId,proto3" json:"credential_id,omitempty"`
	PublicKey     []byte                 `protobuf:"bytes,2,opt,name=public_key,json=publicKey,proto3" json:"public_key,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FinishRegistrationResp) Reset() {
	*x = FinishRegistrationResp{}
	mi := &file_apollo_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FinishRegistrationResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FinishRegistrationResp) ProtoMessage() {}

func (x *FinishRegistrationResp) ProtoReflect() protoreflect.Message {
	mi := &file_apollo_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FinishRegistrationResp.ProtoReflect.Descriptor instead.
func (*FinishRegistrationResp) Descriptor() ([]byte, []int) {
	return file_apollo_proto_rawDescGZIP(), []int{3}
}

func (x *FinishRegistrationResp) GetCredentialId() []byte {
	if x != nil {
		return x.CredentialId
	}
	return nil
}

func (x *FinishRegistrationResp) GetPublicKey() []byte {
	if x != nil {
		return x.PublicKey
	}
	return nil
}

// ========== 登录流程 ==========
type StartLoginReq struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	UserId          int64                  `protobuf:"varint,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`                           // API提供
	UserName        string                 `protobuf:"bytes,2,opt,name=user_name,json=userName,proto3" json:"user_name,omitempty"`                      // API提供
	DisplayName     string                 `protobuf:"bytes,3,opt,name=display_name,json=displayName,proto3" json:"display_name,omitempty"`             // API提供
	CredentialsJson []byte                 `protobuf:"bytes,4,opt,name=credentials_json,json=credentialsJson,proto3" json:"credentials_json,omitempty"` // API查询的完整凭证列表
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *StartLoginReq) Reset() {
	*x = StartLoginReq{}
	mi := &file_apollo_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StartLoginReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StartLoginReq) ProtoMessage() {}

func (x *StartLoginReq) ProtoReflect() protoreflect.Message {
	mi := &file_apollo_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StartLoginReq.ProtoReflect.Descriptor instead.
func (*StartLoginReq) Descriptor() ([]byte, []int) {
	return file_apollo_proto_rawDescGZIP(), []int{4}
}

func (x *StartLoginReq) GetUserId() int64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *StartLoginReq) GetUserName() string {
	if x != nil {
		return x.UserName
	}
	return ""
}

func (x *StartLoginReq) GetDisplayName() string {
	if x != nil {
		return x.DisplayName
	}
	return ""
}

func (x *StartLoginReq) GetCredentialsJson() []byte {
	if x != nil {
		return x.CredentialsJson
	}
	return nil
}

type StartLoginResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	OptionsJson   []byte                 `protobuf:"bytes,1,opt,name=options_json,json=optionsJson,proto3" json:"options_json,omitempty"`
	SessionData   []byte                 `protobuf:"bytes,2,opt,name=session_data,json=sessionData,proto3" json:"session_data,omitempty"` // 必须返回给API存储
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StartLoginResp) Reset() {
	*x = StartLoginResp{}
	mi := &file_apollo_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StartLoginResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StartLoginResp) ProtoMessage() {}

func (x *StartLoginResp) ProtoReflect() protoreflect.Message {
	mi := &file_apollo_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StartLoginResp.ProtoReflect.Descriptor instead.
func (*StartLoginResp) Descriptor() ([]byte, []int) {
	return file_apollo_proto_rawDescGZIP(), []int{5}
}

func (x *StartLoginResp) GetOptionsJson() []byte {
	if x != nil {
		return x.OptionsJson
	}
	return nil
}

func (x *StartLoginResp) GetSessionData() []byte {
	if x != nil {
		return x.SessionData
	}
	return nil
}

type FinishLoginReq struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	CredentialJson []byte                 `protobuf:"bytes,1,opt,name=credential_json,json=credentialJson,proto3" json:"credential_json,omitempty"` // 前端原始JSON
	SessionData    []byte                 `protobuf:"bytes,2,opt,name=session_data,json=sessionData,proto3" json:"session_data,omitempty"`          // StartLogin返回的session_data
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *FinishLoginReq) Reset() {
	*x = FinishLoginReq{}
	mi := &file_apollo_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FinishLoginReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FinishLoginReq) ProtoMessage() {}

func (x *FinishLoginReq) ProtoReflect() protoreflect.Message {
	mi := &file_apollo_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FinishLoginReq.ProtoReflect.Descriptor instead.
func (*FinishLoginReq) Descriptor() ([]byte, []int) {
	return file_apollo_proto_rawDescGZIP(), []int{6}
}

func (x *FinishLoginReq) GetCredentialJson() []byte {
	if x != nil {
		return x.CredentialJson
	}
	return nil
}

func (x *FinishLoginReq) GetSessionData() []byte {
	if x != nil {
		return x.SessionData
	}
	return nil
}

type FinishLoginResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        int64                  `protobuf:"varint,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`                  // 验证通过的用户ID
	CredentialId  []byte                 `protobuf:"bytes,2,opt,name=credential_id,json=credentialId,proto3" json:"credential_id,omitempty"` // 使用的凭证ID（用于审计）
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FinishLoginResp) Reset() {
	*x = FinishLoginResp{}
	mi := &file_apollo_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FinishLoginResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FinishLoginResp) ProtoMessage() {}

func (x *FinishLoginResp) ProtoReflect() protoreflect.Message {
	mi := &file_apollo_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FinishLoginResp.ProtoReflect.Descriptor instead.
func (*FinishLoginResp) Descriptor() ([]byte, []int) {
	return file_apollo_proto_rawDescGZIP(), []int{7}
}

func (x *FinishLoginResp) GetUserId() int64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *FinishLoginResp) GetCredentialId() []byte {
	if x != nil {
		return x.CredentialId
	}
	return nil
}

var File_apollo_proto protoreflect.FileDescriptor

const file_apollo_proto_rawDesc = "" +
	"\n" +
	"\fapollo.proto\x12\x06apollo\"o\n" +
	"\x14StartRegistrationReq\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\x03R\x06userId\x12\x1b\n" +
	"\tuser_name\x18\x02 \x01(\tR\buserName\x12!\n" +
	"\fdisplay_name\x18\x03 \x01(\tR\vdisplayName\"]\n" +
	"\x15StartRegistrationResp\x12!\n" +
	"\foptions_json\x18\x01 \x01(\fR\voptionsJson\x12!\n" +
	"\fsession_data\x18\x02 \x01(\fR\vsessionData\"|\n" +
	"\x15FinishRegistrationReq\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\x03R\x06userId\x12'\n" +
	"\x0fcredential_json\x18\x02 \x01(\fR\x0ecredentialJson\x12!\n" +
	"\fsession_data\x18\x03 \x01(\fR\vsessionData\"\\\n" +
	"\x16FinishRegistrationResp\x12#\n" +
	"\rcredential_id\x18\x01 \x01(\fR\fcredentialId\x12\x1d\n" +
	"\n" +
	"public_key\x18\x02 \x01(\fR\tpublicKey\"\x93\x01\n" +
	"\rStartLoginReq\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\x03R\x06userId\x12\x1b\n" +
	"\tuser_name\x18\x02 \x01(\tR\buserName\x12!\n" +
	"\fdisplay_name\x18\x03 \x01(\tR\vdisplayName\x12)\n" +
	"\x10credentials_json\x18\x04 \x01(\fR\x0fcredentialsJson\"V\n" +
	"\x0eStartLoginResp\x12!\n" +
	"\foptions_json\x18\x01 \x01(\fR\voptionsJson\x12!\n" +
	"\fsession_data\x18\x02 \x01(\fR\vsessionData\"\\\n" +
	"\x0eFinishLoginReq\x12'\n" +
	"\x0fcredential_json\x18\x01 \x01(\fR\x0ecredentialJson\x12!\n" +
	"\fsession_data\x18\x02 \x01(\fR\vsessionData\"O\n" +
	"\x0fFinishLoginResp\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\x03R\x06userId\x12#\n" +
	"\rcredential_id\x18\x02 \x01(\fR\fcredentialId2\xae\x02\n" +
	"\bPasskeys\x12P\n" +
	"\x11StartRegistration\x12\x1c.apollo.StartRegistrationReq\x1a\x1d.apollo.StartRegistrationResp\x12S\n" +
	"\x12FinishRegistration\x12\x1d.apollo.FinishRegistrationReq\x1a\x1e.apollo.FinishRegistrationResp\x12;\n" +
	"\n" +
	"StartLogin\x12\x15.apollo.StartLoginReq\x1a\x16.apollo.StartLoginResp\x12>\n" +
	"\vFinishLogin\x12\x16.apollo.FinishLoginReq\x1a\x17.apollo.FinishLoginRespB\n" +
	"Z\b./apollob\x06proto3"

var (
	file_apollo_proto_rawDescOnce sync.Once
	file_apollo_proto_rawDescData []byte
)

func file_apollo_proto_rawDescGZIP() []byte {
	file_apollo_proto_rawDescOnce.Do(func() {
		file_apollo_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_apollo_proto_rawDesc), len(file_apollo_proto_rawDesc)))
	})
	return file_apollo_proto_rawDescData
}

var file_apollo_proto_msgTypes = make([]protoimpl.MessageInfo, 8)
var file_apollo_proto_goTypes = []any{
	(*StartRegistrationReq)(nil),   // 0: apollo.StartRegistrationReq
	(*StartRegistrationResp)(nil),  // 1: apollo.StartRegistrationResp
	(*FinishRegistrationReq)(nil),  // 2: apollo.FinishRegistrationReq
	(*FinishRegistrationResp)(nil), // 3: apollo.FinishRegistrationResp
	(*StartLoginReq)(nil),          // 4: apollo.StartLoginReq
	(*StartLoginResp)(nil),         // 5: apollo.StartLoginResp
	(*FinishLoginReq)(nil),         // 6: apollo.FinishLoginReq
	(*FinishLoginResp)(nil),        // 7: apollo.FinishLoginResp
}
var file_apollo_proto_depIdxs = []int32{
	0, // 0: apollo.Passkeys.StartRegistration:input_type -> apollo.StartRegistrationReq
	2, // 1: apollo.Passkeys.FinishRegistration:input_type -> apollo.FinishRegistrationReq
	4, // 2: apollo.Passkeys.StartLogin:input_type -> apollo.StartLoginReq
	6, // 3: apollo.Passkeys.FinishLogin:input_type -> apollo.FinishLoginReq
	1, // 4: apollo.Passkeys.StartRegistration:output_type -> apollo.StartRegistrationResp
	3, // 5: apollo.Passkeys.FinishRegistration:output_type -> apollo.FinishRegistrationResp
	5, // 6: apollo.Passkeys.StartLogin:output_type -> apollo.StartLoginResp
	7, // 7: apollo.Passkeys.FinishLogin:output_type -> apollo.FinishLoginResp
	4, // [4:8] is the sub-list for method output_type
	0, // [0:4] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_apollo_proto_init() }
func file_apollo_proto_init() {
	if File_apollo_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_apollo_proto_rawDesc), len(file_apollo_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   8,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_apollo_proto_goTypes,
		DependencyIndexes: file_apollo_proto_depIdxs,
		MessageInfos:      file_apollo_proto_msgTypes,
	}.Build()
	File_apollo_proto = out.File
	file_apollo_proto_goTypes = nil
	file_apollo_proto_depIdxs = nil
}
