// Framework generated by goctl 1.9.2; application adapter implemented after generation.
package authlogic

import (
	"context"
	"jian-unified-system/hephaestus/hephaestus-rpc/income"
	"jian-unified-system/hephaestus/hephaestus-rpc/internal/svc"
	"jian-unified-system/hephaestus/internal/transport"
)

type LogoutLogic struct {
	ctx    context.Context
	svcCtx *svc.ServiceContext
}

func NewLogoutLogic(ctx context.Context, svcCtx *svc.ServiceContext) *LogoutLogic {
	return &LogoutLogic{ctx, svcCtx}
}
func (l *LogoutLogic) Logout(in *income.LogoutRequest) (*income.Empty, error) {
	if in.Input == nil {
		in.Input = &income.Empty{}
	}
	if _, e := l.svcCtx.App.Session(l.ctx, in.SessionToken, in.CsrfToken); e != nil {
		return nil, transport.RPCError(e)
	}
	return &income.Empty{}, transport.RPCError(l.svcCtx.App.Logout(l.ctx, in.SessionToken))
}
