// Framework generated by goctl 1.9.2; application adapter implemented after generation.
package authlogic

import (
	"context"
	"jian-unified-system/hephaestus/hephaestus-rpc/income"
	"jian-unified-system/hephaestus/hephaestus-rpc/internal/svc"
	"jian-unified-system/hephaestus/internal/transport"
)

type SessionLogic struct {
	ctx    context.Context
	svcCtx *svc.ServiceContext
}

func NewSessionLogic(ctx context.Context, svcCtx *svc.ServiceContext) *SessionLogic {
	return &SessionLogic{ctx, svcCtx}
}
func (l *SessionLogic) Session(in *income.SessionRequest) (*income.SessionResp, error) {
	if in.Input == nil {
		in.Input = &income.Empty{}
	}
	v, e := l.svcCtx.App.Session(l.ctx, in.SessionToken, in.CsrfToken)
	return transport.Result[income.SessionResp](v, e)
}
