// Code generated by goctl. DO NOT EDIT.
// goctl 1.9.0
// Source: apollo-rpc.proto

package server

import (
	"context"

	"jian-unified-system/apollo/apollo-rpc/apollo"
	"jian-unified-system/apollo/apollo-rpc/internal/logic/security"
	"jian-unified-system/apollo/apollo-rpc/internal/svc"
)

type SecurityServer struct {
	svcCtx *svc.ServiceContext
	apollo.UnimplementedSecurityServer
}

func NewSecurityServer(svcCtx *svc.ServiceContext) *SecurityServer {
	return &SecurityServer{
		svcCtx: svcCtx,
	}
}

// 生成子系统令牌
func (s *SecurityServer) GenerateSubsystemToken(ctx context.Context, in *apollo.GenerateSubsystemTokenReq) (*apollo.GenerateSubsystemTokenResp, error) {
	l := securitylogic.NewGenerateSubsystemTokenLogic(ctx, s.svcCtx)
	return l.GenerateSubsystemToken(in)
}

// 验证子系统令牌
func (s *SecurityServer) ValidateSubsystemToken(ctx context.Context, in *apollo.ValidateSubsystemTokenReq) (*apollo.ValidateSubsystemTokenResp, error) {
	l := securitylogic.NewValidateSubsystemTokenLogic(ctx, s.svcCtx)
	return l.ValidateSubsystemToken(in)
}

// 移除子系统令牌
func (s *SecurityServer) RemoveSubsystemToken(ctx context.Context, in *apollo.RemoveSubsystemTokenReq) (*apollo.RemoveSubsystemTokenResp, error) {
	l := securitylogic.NewRemoveSubsystemTokenLogic(ctx, s.svcCtx)
	return l.RemoveSubsystemToken(in)
}
