
# ===============================
# Service
# ===============================
apiVersion: v1
kind: Service
metadata:
  name: jquantum-rpc-svc
  namespace: harmoniacore
spec:
  ports:
    - port: 30101
      targetPort: 30101
  selector:
    app: jquantum-rpc
    version: v0.1.0
---
# ===============================
# PersistentVolume (NFS)
# ===============================
apiVersion: v1
kind: PersistentVolume
metadata:
  name: jquantum-pv
spec:
  capacity:
    storage: 50Gi
  accessModes:
    - ReadWriteMany
  nfs:
    server: 47.91.29.219
    path: /harmoniacore/jquantum
  persistentVolumeReclaimPolicy: Retain

---
# ===============================
# PersistentVolumeClaim
# ===============================
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: jquantum-pvc
  namespace: harmoniacore
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 50Gi
  volumeName: jquantum-pv
  storageClassName: ""

---
# ===============================
# DaemonSet
# ===============================
apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: jquantum-rpc
  namespace: harmoniacore
  labels:
    app: jquantum-rpc
    version: v0.1.0
spec:
  selector:
    matchLabels:
      app: jquantum-rpc
      version: v0.1.0
  template:
    metadata:
      labels:
        app: jquantum-rpc
        version: v0.1.0
      annotations:
        sidecar.istio.io/inject: "false"
    spec:
      serviceAccountName: find-endpoints
      containers:
        - name: jquantum-rpc
          image: ikarosu/jian-unified-system-go-jquantum-rpc:v0.1.0
          imagePullPolicy: Always
          ports:
            - containerPort: 30101
            - containerPort: 22
          # 健康检查
          readinessProbe:
            tcpSocket:
              port: 30101
            initialDelaySeconds: 5
            periodSeconds: 10
          livenessProbe:
            tcpSocket:
              port: 30101
            initialDelaySeconds: 15
            periodSeconds: 20
          # 挂载 NFS
          volumeMounts:
            - name: timezone
              mountPath: /etc/localtime
            - name: jquantum-storage
              mountPath: /harmoniacore/jquantum
      volumes:
        - name: timezone
          hostPath:
            path: /usr/share/zoneinfo/Asia/Shanghai
        - name: jquantum-storage
          persistentVolumeClaim:
            claimName: jquantum-pvc
