// Code generated by goctl. DO NOT EDIT.
// goctl 1.8.5
// Source: apollo-rpc.proto

package account

import (
	"context"

	"jian-unified-system/apollo/apollo-rpc/apollo"

	"github.com/zeromicro/go-zero/zrpc"
	"google.golang.org/grpc"
)

type (
	Empty                         = apollo.Empty
	LoginReq                      = apollo.LoginReq
	LoginResp                     = apollo.LoginResp
	PasskeysFinishLoginReq        = apollo.PasskeysFinishLoginReq
	PasskeysFinishLoginResp       = apollo.PasskeysFinishLoginResp
	PasskeysFinishRegistrationReq = apollo.PasskeysFinishRegistrationReq
	PasskeysStartLoginResp        = apollo.PasskeysStartLoginResp
	PasskeysStartRegistrationReq  = apollo.PasskeysStartRegistrationReq
	PasskeysStartRegistrationResp = apollo.PasskeysStartRegistrationResp
	RegistrationReq               = apollo.RegistrationReq
	ThirdPartyBindReq             = apollo.ThirdPartyBindReq
	ThirdPartyContinueReq         = apollo.ThirdPartyContinueReq
	ThirdPartyContinueResp        = apollo.ThirdPartyContinueResp

	Account interface {
		// 注册
		Registration(ctx context.Context, in *RegistrationReq, opts ...grpc.CallOption) (*Empty, error)
		// 登录
		Login(ctx context.Context, in *LoginReq, opts ...grpc.CallOption) (*LoginResp, error)
	}

	defaultAccount struct {
		cli zrpc.Client
	}
)

func NewAccount(cli zrpc.Client) Account {
	return &defaultAccount{
		cli: cli,
	}
}

// 注册
func (m *defaultAccount) Registration(ctx context.Context, in *RegistrationReq, opts ...grpc.CallOption) (*Empty, error) {
	client := apollo.NewAccountClient(m.cli.Conn())
	return client.Registration(ctx, in, opts...)
}

// 登录
func (m *defaultAccount) Login(ctx context.Context, in *LoginReq, opts ...grpc.CallOption) (*LoginResp, error) {
	client := apollo.NewAccountClient(m.cli.Conn())
	return client.Login(ctx, in, opts...)
}
