// Code generated by goctl. DO NOT EDIT.
// goctl 1.9.0
// Source: jquantum-rpc.proto

package jquantum

import (
	"context"

	"jian-unified-system/jquantum/jquantum-rpc/jquantum"

	"github.com/zeromicro/go-zero/zrpc"
	"google.golang.org/grpc"
)

type (
	RetrieveResultReq  = jquantum.RetrieveResultReq
	RetrieveResultResp = jquantum.RetrieveResultResp
	SubmitReq          = jquantum.SubmitReq
	SubmitResp         = jquantum.SubmitResp

	JQuantum interface {
		// Submit 提交任务
		Submit(ctx context.Context, in *SubmitReq, opts ...grpc.CallOption) (*SubmitResp, error)
		// RetrieveResult 获取计算任务结果
		RetrieveResult(ctx context.Context, in *RetrieveResultReq, opts ...grpc.CallOption) (*RetrieveResultResp, error)
	}

	defaultJQuantum struct {
		cli zrpc.Client
	}
)

func NewJQuantum(cli zrpc.Client) JQuantum {
	return &defaultJQuantum{
		cli: cli,
	}
}

// Submit 提交任务
func (m *defaultJQuantum) Submit(ctx context.Context, in *SubmitReq, opts ...grpc.CallOption) (*SubmitResp, error) {
	client := jquantum.NewJQuantumClient(m.cli.Conn())
	return client.Submit(ctx, in, opts...)
}

// RetrieveResult 获取计算任务结果
func (m *defaultJQuantum) RetrieveResult(ctx context.Context, in *RetrieveResultReq, opts ...grpc.CallOption) (*RetrieveResultResp, error) {
	client := jquantum.NewJQuantumClient(m.cli.Conn())
	return client.RetrieveResult(ctx, in, opts...)
}
