// Code generated by goctl. DO NOT EDIT.
// goctl 1.9.2
// Source: hephaestus.proto

package server

import (
	"context"

	"jian-unified-system/hephaestus/hephaestus-rpc/income"
	"jian-unified-system/hephaestus/hephaestus-rpc/internal/logic/health"
	"jian-unified-system/hephaestus/hephaestus-rpc/internal/svc"
)

type HealthServer struct {
	svcCtx *svc.ServiceContext
	income.UnimplementedHealthServer
}

func NewHealthServer(svcCtx *svc.ServiceContext) *HealthServer {
	return &HealthServer{
		svcCtx: svcCtx,
	}
}

func (s *HealthServer) Health(ctx context.Context, in *income.HealthRequest) (*income.HealthResp, error) {
	l := healthlogic.NewHealthLogic(ctx, s.svcCtx)
	return l.Health(in)
}
