// Framework generated by goctl 1.9.2; application adapter implemented after generation.
package recordslogic

import (
	"context"
	"jian-unified-system/hephaestus/hephaestus-rpc/income"
	"jian-unified-system/hephaestus/hephaestus-rpc/internal/adapter"
	d "jian-unified-system/hephaestus/hephaestus-rpc/internal/domain"
	"jian-unified-system/hephaestus/hephaestus-rpc/internal/svc"
	"jian-unified-system/hephaestus/internal/transport"
)

type CreateRecordLogic struct {
	ctx    context.Context
	svcCtx *svc.ServiceContext
}

func NewCreateRecordLogic(ctx context.Context, svcCtx *svc.ServiceContext) *CreateRecordLogic {
	return &CreateRecordLogic{ctx, svcCtx}
}
func (l *CreateRecordLogic) CreateRecord(in *income.CreateRecordRequest) (*income.Record, error) {
	if in.Input == nil {
		in.Input = &income.CreateRecordReq{}
	}
	if e := adapter.Authorize(l.ctx, l.svcCtx.App, in.OwnerId, in.SessionToken); e != nil {
		return nil, transport.RPCError(e)
	}
	data, e := transport.Convert[d.Data](in.Input.Data)
	if e != nil {
		return nil, transport.RPCError(d.Invalid("invalid record data"))
	}
	v, e := l.svcCtx.App.Create(l.ctx, in.OwnerId, in.IdempotencyKey, *data)
	return transport.Result[income.Record](v, e)
}
