// Framework generated by goctl 1.9.2; application adapter implemented after generation.
package recordslogic

import (
	"context"
	"jian-unified-system/hephaestus/hephaestus-rpc/income"
	"jian-unified-system/hephaestus/hephaestus-rpc/internal/adapter"
	"jian-unified-system/hephaestus/hephaestus-rpc/internal/svc"
	"jian-unified-system/hephaestus/internal/transport"
)

type ListRecordsLogic struct {
	ctx    context.Context
	svcCtx *svc.ServiceContext
}

func NewListRecordsLogic(ctx context.Context, svcCtx *svc.ServiceContext) *ListRecordsLogic {
	return &ListRecordsLogic{ctx, svcCtx}
}
func (l *ListRecordsLogic) ListRecords(in *income.ListRecordsRequest) (*income.RecordList, error) {
	if in.Input == nil {
		in.Input = &income.QueryReq{}
	}
	if e := adapter.Authorize(l.ctx, l.svcCtx.App, in.OwnerId, in.SessionToken); e != nil {
		return nil, transport.RPCError(e)
	}
	v, e := l.svcCtx.App.List(l.ctx, in.OwnerId, adapter.Filter(in.Input))
	return transport.Result[income.RecordList](v, e)
}
