// Framework generated by goctl 1.9.2; application adapter implemented after generation.
package recordslogic

import (
	"context"
	"jian-unified-system/hephaestus/hephaestus-rpc/income"
	"jian-unified-system/hephaestus/hephaestus-rpc/internal/adapter"
	d "jian-unified-system/hephaestus/hephaestus-rpc/internal/domain"
	"jian-unified-system/hephaestus/hephaestus-rpc/internal/svc"
	"jian-unified-system/hephaestus/internal/transport"
)

type UpdateRecordLogic struct {
	ctx    context.Context
	svcCtx *svc.ServiceContext
}

func NewUpdateRecordLogic(ctx context.Context, svcCtx *svc.ServiceContext) *UpdateRecordLogic {
	return &UpdateRecordLogic{ctx, svcCtx}
}
func (l *UpdateRecordLogic) UpdateRecord(in *income.UpdateRecordRequest) (*income.Record, error) {
	if in.Input == nil {
		in.Input = &income.UpdateRecordReq{}
	}
	if e := adapter.Authorize(l.ctx, l.svcCtx.App, in.OwnerId, in.SessionToken); e != nil {
		return nil, transport.RPCError(e)
	}
	id, e := adapter.IntID(in.Input.Id)
	if e != nil {
		return nil, transport.RPCError(e)
	}
	changes, e := transport.Convert[[]d.Change](in.Input.Changes)
	if e != nil {
		return nil, transport.RPCError(d.Invalid("invalid changes"))
	}
	v, e := l.svcCtx.App.Mutate(l.ctx, in.OwnerId, id, in.ExpectedVersion, in.IdempotencyKey, "updated", in.Input.Reason, "", *changes)
	return transport.Result[income.Record](v, e)
}
