// Code generated by goctl. DO NOT EDIT.
// goctl 1.9.0

package types

type BaseResponse struct {
	Code    int    `json:"code"`
	Message string `json:"message"`
}

type ClusterInfoReq struct {
}

type ClusterInfoResp struct {
	BaseResponse
	TotalCPU  int64 `json:"totalCpu"`
	TotalMem  int64 `json:"totalMem"`
	MaxQubits int64 `json:"maxQubits"`
	Nodes     int64 `json:"nodes"`
}

type Empty struct {
}

type RetrieveResultReq struct {
	JobID string `json:"jobId"`
}

type RetrieveResultResp struct {
	BaseResponse
	Result []byte `json:"result"`
}

type SubmitReq struct {
}

type SubmitResp struct {
	BaseResponse
	JobID string `json:"jobId"`
}
