// Code generated by goctl. DO NOT EDIT.
// goctl 1.8.5

package types

type BaseResponse struct {
	Code    int    `json:"code"`
	Message string `json:"message"`
}

type Empty struct {
}

type SubmitReq struct {
}

type SubmitResp struct {
	Email           string `json:"email" validate:"required"`
	Password        string `json:"password" validate:"required"`
	ConfirmPassword string `json:"confirm_password" validate:"required"`
	Language        string `json:"language" validate:"required"`
}
