// Code generated by goctl. DO NOT EDIT.
// goctl 1.8.5
// Source: apollo-rpc.proto

package server

import (
	"context"

	"jian-unified-system/apollo/apollo-rpc/apollo"
	"jian-unified-system/apollo/apollo-rpc/internal/logic/account"
	"jian-unified-system/apollo/apollo-rpc/internal/svc"
)

type AccountServer struct {
	svcCtx *svc.ServiceContext
	apollo.UnimplementedAccountServer
}

func NewAccountServer(svcCtx *svc.ServiceContext) *AccountServer {
	return &AccountServer{
		svcCtx: svcCtx,
	}
}

// 注册
func (s *AccountServer) Registration(ctx context.Context, in *apollo.RegistrationReq) (*apollo.Empty, error) {
	l := accountlogic.NewRegistrationLogic(ctx, s.svcCtx)
	return l.Registration(in)
}

// 登录
func (s *AccountServer) Login(ctx context.Context, in *apollo.LoginReq) (*apollo.LoginResp, error) {
	l := accountlogic.NewLoginLogic(ctx, s.svcCtx)
	return l.Login(in)
}
