// Code generated by goctl. DO NOT EDIT.
// goctl 1.9.2
// Source: apollo-rpc.proto

package server

import (
	"context"

	"jian-unified-system/apollo/apollo-rpc/apollo"
	"jian-unified-system/apollo/apollo-rpc/internal/logic/account"
	"jian-unified-system/apollo/apollo-rpc/internal/svc"
)

type AccountServer struct {
	svcCtx *svc.ServiceContext
	apollo.UnimplementedAccountServer
}

func NewAccountServer(svcCtx *svc.ServiceContext) *AccountServer {
	return &AccountServer{
		svcCtx: svcCtx,
	}
}

func (s *AccountServer) Registration(ctx context.Context, in *apollo.RegistrationReq) (*apollo.Empty, error) {
	l := accountlogic.NewRegistrationLogic(ctx, s.svcCtx)
	return l.Registration(in)
}

func (s *AccountServer) Login(ctx context.Context, in *apollo.LoginReq) (*apollo.LoginResp, error) {
	l := accountlogic.NewLoginLogic(ctx, s.svcCtx)
	return l.Login(in)
}

func (s *AccountServer) UserInfo(ctx context.Context, in *apollo.UserInfoReq) (*apollo.UserInfoResp, error) {
	l := accountlogic.NewUserInfoLogic(ctx, s.svcCtx)
	return l.UserInfo(in)
}

func (s *AccountServer) UserSecurityInfo(ctx context.Context, in *apollo.UserSecurityInfoReq) (*apollo.UserSecurityInfoResp, error) {
	l := accountlogic.NewUserSecurityInfoLogic(ctx, s.svcCtx)
	return l.UserSecurityInfo(in)
}

func (s *AccountServer) SessionVersion(ctx context.Context, in *apollo.SessionVersionReq) (*apollo.SessionVersionResp, error) {
	l := accountlogic.NewSessionVersionLogic(ctx, s.svcCtx)
	return l.SessionVersion(in)
}

func (s *AccountServer) UpdateName(ctx context.Context, in *apollo.UpdateNameReq) (*apollo.Empty, error) {
	l := accountlogic.NewUpdateNameLogic(ctx, s.svcCtx)
	return l.UpdateName(in)
}

func (s *AccountServer) UpdateBirthday(ctx context.Context, in *apollo.UpdateBirthdayReq) (*apollo.Empty, error) {
	l := accountlogic.NewUpdateBirthdayLogic(ctx, s.svcCtx)
	return l.UpdateBirthday(in)
}

func (s *AccountServer) UpdateLanguage(ctx context.Context, in *apollo.UpdateLanguageReq) (*apollo.Empty, error) {
	l := accountlogic.NewUpdateLanguageLogic(ctx, s.svcCtx)
	return l.UpdateLanguage(in)
}

func (s *AccountServer) AddContact(ctx context.Context, in *apollo.AddContactReq) (*apollo.AddContactResp, error) {
	l := accountlogic.NewAddContactLogic(ctx, s.svcCtx)
	return l.AddContact(in)
}

func (s *AccountServer) RemoveContact(ctx context.Context, in *apollo.RemoveContactReq) (*apollo.Empty, error) {
	l := accountlogic.NewRemoveContactLogic(ctx, s.svcCtx)
	return l.RemoveContact(in)
}

func (s *AccountServer) ChangePassword(ctx context.Context, in *apollo.ChangePasswordReq) (*apollo.Empty, error) {
	l := accountlogic.NewChangePasswordLogic(ctx, s.svcCtx)
	return l.ChangePassword(in)
}

func (s *AccountServer) ChangeNotificationEmail(ctx context.Context, in *apollo.ChangeNotificationEmailReq) (*apollo.Empty, error) {
	l := accountlogic.NewChangeNotificationEmailLogic(ctx, s.svcCtx)
	return l.ChangeNotificationEmail(in)
}

func (s *AccountServer) RemoveNotificationEmail(ctx context.Context, in *apollo.RemoveNotificationEmailReq) (*apollo.Empty, error) {
	l := accountlogic.NewRemoveNotificationEmailLogic(ctx, s.svcCtx)
	return l.RemoveNotificationEmail(in)
}

func (s *AccountServer) DeleteAccount(ctx context.Context, in *apollo.DeleteAccountReq) (*apollo.Empty, error) {
	l := accountlogic.NewDeleteAccountLogic(ctx, s.svcCtx)
	return l.DeleteAccount(in)
}
