// Code generated by goctl. DO NOT EDIT.
// goctl 1.9.0
// Source: apollo-rpc.proto

package server

import (
	"context"

	"jian-unified-system/apollo/apollo-rpc/apollo"
	"jian-unified-system/apollo/apollo-rpc/internal/logic/account"
	"jian-unified-system/apollo/apollo-rpc/internal/svc"
)

type AccountServer struct {
	svcCtx *svc.ServiceContext
	apollo.UnimplementedAccountServer
}

func NewAccountServer(svcCtx *svc.ServiceContext) *AccountServer {
	return &AccountServer{
		svcCtx: svcCtx,
	}
}

// 注册
func (s *AccountServer) Registration(ctx context.Context, in *apollo.RegistrationReq) (*apollo.Empty, error) {
	l := accountlogic.NewRegistrationLogic(ctx, s.svcCtx)
	return l.Registration(in)
}

// 登录
func (s *AccountServer) Login(ctx context.Context, in *apollo.LoginReq) (*apollo.LoginResp, error) {
	l := accountlogic.NewLoginLogic(ctx, s.svcCtx)
	return l.Login(in)
}

// 用户信息
func (s *AccountServer) UserInfo(ctx context.Context, in *apollo.UserInfoReq) (*apollo.UserInfoResp, error) {
	l := accountlogic.NewUserInfoLogic(ctx, s.svcCtx)
	return l.UserInfo(in)
}

// 生成子系统令牌
func (s *AccountServer) GenerateToken(ctx context.Context, in *apollo.GenerateTokenReq) (*apollo.GenerateTokenResp, error) {
	l := accountlogic.NewGenerateTokenLogic(ctx, s.svcCtx)
	return l.GenerateToken(in)
}

// 验证子系统令牌
func (s *AccountServer) ValidateToken(ctx context.Context, in *apollo.ValidateTokenReq) (*apollo.ValidateTokenResp, error) {
	l := accountlogic.NewValidateTokenLogic(ctx, s.svcCtx)
	return l.ValidateToken(in)
}
