// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v3.19.4
// source: hephaestus.proto

package income

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	Auth_Session_FullMethodName = "/income.Auth/Session"
	Auth_Logout_FullMethodName  = "/income.Auth/Logout"
)

// AuthClient is the client API for Auth service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type AuthClient interface {
	Session(ctx context.Context, in *SessionRequest, opts ...grpc.CallOption) (*SessionResp, error)
	Logout(ctx context.Context, in *LogoutRequest, opts ...grpc.CallOption) (*Empty, error)
}

type authClient struct {
	cc grpc.ClientConnInterface
}

func NewAuthClient(cc grpc.ClientConnInterface) AuthClient {
	return &authClient{cc}
}

func (c *authClient) Session(ctx context.Context, in *SessionRequest, opts ...grpc.CallOption) (*SessionResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SessionResp)
	err := c.cc.Invoke(ctx, Auth_Session_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *authClient) Logout(ctx context.Context, in *LogoutRequest, opts ...grpc.CallOption) (*Empty, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Empty)
	err := c.cc.Invoke(ctx, Auth_Logout_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// AuthServer is the server API for Auth service.
// All implementations must embed UnimplementedAuthServer
// for forward compatibility.
type AuthServer interface {
	Session(context.Context, *SessionRequest) (*SessionResp, error)
	Logout(context.Context, *LogoutRequest) (*Empty, error)
	mustEmbedUnimplementedAuthServer()
}

// UnimplementedAuthServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedAuthServer struct{}

func (UnimplementedAuthServer) Session(context.Context, *SessionRequest) (*SessionResp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Session not implemented")
}
func (UnimplementedAuthServer) Logout(context.Context, *LogoutRequest) (*Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Logout not implemented")
}
func (UnimplementedAuthServer) mustEmbedUnimplementedAuthServer() {}
func (UnimplementedAuthServer) testEmbeddedByValue()              {}

// UnsafeAuthServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to AuthServer will
// result in compilation errors.
type UnsafeAuthServer interface {
	mustEmbedUnimplementedAuthServer()
}

func RegisterAuthServer(s grpc.ServiceRegistrar, srv AuthServer) {
	// If the following call pancis, it indicates UnimplementedAuthServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&Auth_ServiceDesc, srv)
}

func _Auth_Session_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SessionRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AuthServer).Session(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Auth_Session_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AuthServer).Session(ctx, req.(*SessionRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Auth_Logout_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(LogoutRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AuthServer).Logout(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Auth_Logout_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AuthServer).Logout(ctx, req.(*LogoutRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// Auth_ServiceDesc is the grpc.ServiceDesc for Auth service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Auth_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "income.Auth",
	HandlerType: (*AuthServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Session",
			Handler:    _Auth_Session_Handler,
		},
		{
			MethodName: "Logout",
			Handler:    _Auth_Logout_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "hephaestus.proto",
}

const (
	Records_CreateRecord_FullMethodName  = "/income.Records/CreateRecord"
	Records_ListRecords_FullMethodName   = "/income.Records/ListRecords"
	Records_GetRecord_FullMethodName     = "/income.Records/GetRecord"
	Records_UpdateRecord_FullMethodName  = "/income.Records/UpdateRecord"
	Records_ArchiveRecord_FullMethodName = "/income.Records/ArchiveRecord"
	Records_RestoreRecord_FullMethodName = "/income.Records/RestoreRecord"
	Records_ClearOverride_FullMethodName = "/income.Records/ClearOverride"
	Records_ListRevisions_FullMethodName = "/income.Records/ListRevisions"
)

// RecordsClient is the client API for Records service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type RecordsClient interface {
	CreateRecord(ctx context.Context, in *CreateRecordRequest, opts ...grpc.CallOption) (*Record, error)
	ListRecords(ctx context.Context, in *ListRecordsRequest, opts ...grpc.CallOption) (*RecordList, error)
	GetRecord(ctx context.Context, in *GetRecordRequest, opts ...grpc.CallOption) (*Record, error)
	UpdateRecord(ctx context.Context, in *UpdateRecordRequest, opts ...grpc.CallOption) (*Record, error)
	ArchiveRecord(ctx context.Context, in *ArchiveRecordRequest, opts ...grpc.CallOption) (*Record, error)
	RestoreRecord(ctx context.Context, in *RestoreRecordRequest, opts ...grpc.CallOption) (*Record, error)
	ClearOverride(ctx context.Context, in *ClearOverrideRequest, opts ...grpc.CallOption) (*Record, error)
	ListRevisions(ctx context.Context, in *ListRevisionsRequest, opts ...grpc.CallOption) (*RevisionList, error)
}

type recordsClient struct {
	cc grpc.ClientConnInterface
}

func NewRecordsClient(cc grpc.ClientConnInterface) RecordsClient {
	return &recordsClient{cc}
}

func (c *recordsClient) CreateRecord(ctx context.Context, in *CreateRecordRequest, opts ...grpc.CallOption) (*Record, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Record)
	err := c.cc.Invoke(ctx, Records_CreateRecord_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *recordsClient) ListRecords(ctx context.Context, in *ListRecordsRequest, opts ...grpc.CallOption) (*RecordList, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(RecordList)
	err := c.cc.Invoke(ctx, Records_ListRecords_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *recordsClient) GetRecord(ctx context.Context, in *GetRecordRequest, opts ...grpc.CallOption) (*Record, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Record)
	err := c.cc.Invoke(ctx, Records_GetRecord_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *recordsClient) UpdateRecord(ctx context.Context, in *UpdateRecordRequest, opts ...grpc.CallOption) (*Record, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Record)
	err := c.cc.Invoke(ctx, Records_UpdateRecord_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *recordsClient) ArchiveRecord(ctx context.Context, in *ArchiveRecordRequest, opts ...grpc.CallOption) (*Record, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Record)
	err := c.cc.Invoke(ctx, Records_ArchiveRecord_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *recordsClient) RestoreRecord(ctx context.Context, in *RestoreRecordRequest, opts ...grpc.CallOption) (*Record, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Record)
	err := c.cc.Invoke(ctx, Records_RestoreRecord_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *recordsClient) ClearOverride(ctx context.Context, in *ClearOverrideRequest, opts ...grpc.CallOption) (*Record, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Record)
	err := c.cc.Invoke(ctx, Records_ClearOverride_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *recordsClient) ListRevisions(ctx context.Context, in *ListRevisionsRequest, opts ...grpc.CallOption) (*RevisionList, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(RevisionList)
	err := c.cc.Invoke(ctx, Records_ListRevisions_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// RecordsServer is the server API for Records service.
// All implementations must embed UnimplementedRecordsServer
// for forward compatibility.
type RecordsServer interface {
	CreateRecord(context.Context, *CreateRecordRequest) (*Record, error)
	ListRecords(context.Context, *ListRecordsRequest) (*RecordList, error)
	GetRecord(context.Context, *GetRecordRequest) (*Record, error)
	UpdateRecord(context.Context, *UpdateRecordRequest) (*Record, error)
	ArchiveRecord(context.Context, *ArchiveRecordRequest) (*Record, error)
	RestoreRecord(context.Context, *RestoreRecordRequest) (*Record, error)
	ClearOverride(context.Context, *ClearOverrideRequest) (*Record, error)
	ListRevisions(context.Context, *ListRevisionsRequest) (*RevisionList, error)
	mustEmbedUnimplementedRecordsServer()
}

// UnimplementedRecordsServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedRecordsServer struct{}

func (UnimplementedRecordsServer) CreateRecord(context.Context, *CreateRecordRequest) (*Record, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreateRecord not implemented")
}
func (UnimplementedRecordsServer) ListRecords(context.Context, *ListRecordsRequest) (*RecordList, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ListRecords not implemented")
}
func (UnimplementedRecordsServer) GetRecord(context.Context, *GetRecordRequest) (*Record, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetRecord not implemented")
}
func (UnimplementedRecordsServer) UpdateRecord(context.Context, *UpdateRecordRequest) (*Record, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UpdateRecord not implemented")
}
func (UnimplementedRecordsServer) ArchiveRecord(context.Context, *ArchiveRecordRequest) (*Record, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ArchiveRecord not implemented")
}
func (UnimplementedRecordsServer) RestoreRecord(context.Context, *RestoreRecordRequest) (*Record, error) {
	return nil, status.Errorf(codes.Unimplemented, "method RestoreRecord not implemented")
}
func (UnimplementedRecordsServer) ClearOverride(context.Context, *ClearOverrideRequest) (*Record, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ClearOverride not implemented")
}
func (UnimplementedRecordsServer) ListRevisions(context.Context, *ListRevisionsRequest) (*RevisionList, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ListRevisions not implemented")
}
func (UnimplementedRecordsServer) mustEmbedUnimplementedRecordsServer() {}
func (UnimplementedRecordsServer) testEmbeddedByValue()                 {}

// UnsafeRecordsServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to RecordsServer will
// result in compilation errors.
type UnsafeRecordsServer interface {
	mustEmbedUnimplementedRecordsServer()
}

func RegisterRecordsServer(s grpc.ServiceRegistrar, srv RecordsServer) {
	// If the following call pancis, it indicates UnimplementedRecordsServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&Records_ServiceDesc, srv)
}

func _Records_CreateRecord_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateRecordRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RecordsServer).CreateRecord(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Records_CreateRecord_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RecordsServer).CreateRecord(ctx, req.(*CreateRecordRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Records_ListRecords_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListRecordsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RecordsServer).ListRecords(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Records_ListRecords_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RecordsServer).ListRecords(ctx, req.(*ListRecordsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Records_GetRecord_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetRecordRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RecordsServer).GetRecord(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Records_GetRecord_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RecordsServer).GetRecord(ctx, req.(*GetRecordRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Records_UpdateRecord_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateRecordRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RecordsServer).UpdateRecord(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Records_UpdateRecord_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RecordsServer).UpdateRecord(ctx, req.(*UpdateRecordRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Records_ArchiveRecord_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ArchiveRecordRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RecordsServer).ArchiveRecord(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Records_ArchiveRecord_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RecordsServer).ArchiveRecord(ctx, req.(*ArchiveRecordRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Records_RestoreRecord_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RestoreRecordRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RecordsServer).RestoreRecord(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Records_RestoreRecord_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RecordsServer).RestoreRecord(ctx, req.(*RestoreRecordRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Records_ClearOverride_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ClearOverrideRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RecordsServer).ClearOverride(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Records_ClearOverride_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RecordsServer).ClearOverride(ctx, req.(*ClearOverrideRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Records_ListRevisions_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListRevisionsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RecordsServer).ListRevisions(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Records_ListRevisions_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RecordsServer).ListRevisions(ctx, req.(*ListRevisionsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// Records_ServiceDesc is the grpc.ServiceDesc for Records service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Records_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "income.Records",
	HandlerType: (*RecordsServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CreateRecord",
			Handler:    _Records_CreateRecord_Handler,
		},
		{
			MethodName: "ListRecords",
			Handler:    _Records_ListRecords_Handler,
		},
		{
			MethodName: "GetRecord",
			Handler:    _Records_GetRecord_Handler,
		},
		{
			MethodName: "UpdateRecord",
			Handler:    _Records_UpdateRecord_Handler,
		},
		{
			MethodName: "ArchiveRecord",
			Handler:    _Records_ArchiveRecord_Handler,
		},
		{
			MethodName: "RestoreRecord",
			Handler:    _Records_RestoreRecord_Handler,
		},
		{
			MethodName: "ClearOverride",
			Handler:    _Records_ClearOverride_Handler,
		},
		{
			MethodName: "ListRevisions",
			Handler:    _Records_ListRevisions_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "hephaestus.proto",
}

const (
	Reporting_Summary_FullMethodName  = "/income.Reporting/Summary"
	Reporting_Calendar_FullMethodName = "/income.Reporting/Calendar"
	Reporting_Series_FullMethodName   = "/income.Reporting/Series"
	Reporting_Export_FullMethodName   = "/income.Reporting/Export"
)

// ReportingClient is the client API for Reporting service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type ReportingClient interface {
	Summary(ctx context.Context, in *SummaryRequest, opts ...grpc.CallOption) (*IncomeSummary, error)
	Calendar(ctx context.Context, in *CalendarRequest, opts ...grpc.CallOption) (*PeriodList, error)
	Series(ctx context.Context, in *SeriesRequest, opts ...grpc.CallOption) (*PeriodList, error)
	Export(ctx context.Context, in *ExportRequest, opts ...grpc.CallOption) (*ExportResp, error)
}

type reportingClient struct {
	cc grpc.ClientConnInterface
}

func NewReportingClient(cc grpc.ClientConnInterface) ReportingClient {
	return &reportingClient{cc}
}

func (c *reportingClient) Summary(ctx context.Context, in *SummaryRequest, opts ...grpc.CallOption) (*IncomeSummary, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(IncomeSummary)
	err := c.cc.Invoke(ctx, Reporting_Summary_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *reportingClient) Calendar(ctx context.Context, in *CalendarRequest, opts ...grpc.CallOption) (*PeriodList, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(PeriodList)
	err := c.cc.Invoke(ctx, Reporting_Calendar_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *reportingClient) Series(ctx context.Context, in *SeriesRequest, opts ...grpc.CallOption) (*PeriodList, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(PeriodList)
	err := c.cc.Invoke(ctx, Reporting_Series_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *reportingClient) Export(ctx context.Context, in *ExportRequest, opts ...grpc.CallOption) (*ExportResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ExportResp)
	err := c.cc.Invoke(ctx, Reporting_Export_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// ReportingServer is the server API for Reporting service.
// All implementations must embed UnimplementedReportingServer
// for forward compatibility.
type ReportingServer interface {
	Summary(context.Context, *SummaryRequest) (*IncomeSummary, error)
	Calendar(context.Context, *CalendarRequest) (*PeriodList, error)
	Series(context.Context, *SeriesRequest) (*PeriodList, error)
	Export(context.Context, *ExportRequest) (*ExportResp, error)
	mustEmbedUnimplementedReportingServer()
}

// UnimplementedReportingServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedReportingServer struct{}

func (UnimplementedReportingServer) Summary(context.Context, *SummaryRequest) (*IncomeSummary, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Summary not implemented")
}
func (UnimplementedReportingServer) Calendar(context.Context, *CalendarRequest) (*PeriodList, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Calendar not implemented")
}
func (UnimplementedReportingServer) Series(context.Context, *SeriesRequest) (*PeriodList, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Series not implemented")
}
func (UnimplementedReportingServer) Export(context.Context, *ExportRequest) (*ExportResp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Export not implemented")
}
func (UnimplementedReportingServer) mustEmbedUnimplementedReportingServer() {}
func (UnimplementedReportingServer) testEmbeddedByValue()                   {}

// UnsafeReportingServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to ReportingServer will
// result in compilation errors.
type UnsafeReportingServer interface {
	mustEmbedUnimplementedReportingServer()
}

func RegisterReportingServer(s grpc.ServiceRegistrar, srv ReportingServer) {
	// If the following call pancis, it indicates UnimplementedReportingServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&Reporting_ServiceDesc, srv)
}

func _Reporting_Summary_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SummaryRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ReportingServer).Summary(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Reporting_Summary_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ReportingServer).Summary(ctx, req.(*SummaryRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Reporting_Calendar_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CalendarRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ReportingServer).Calendar(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Reporting_Calendar_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ReportingServer).Calendar(ctx, req.(*CalendarRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Reporting_Series_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SeriesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ReportingServer).Series(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Reporting_Series_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ReportingServer).Series(ctx, req.(*SeriesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Reporting_Export_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ExportRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ReportingServer).Export(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Reporting_Export_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ReportingServer).Export(ctx, req.(*ExportRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// Reporting_ServiceDesc is the grpc.ServiceDesc for Reporting service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Reporting_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "income.Reporting",
	HandlerType: (*ReportingServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Summary",
			Handler:    _Reporting_Summary_Handler,
		},
		{
			MethodName: "Calendar",
			Handler:    _Reporting_Calendar_Handler,
		},
		{
			MethodName: "Series",
			Handler:    _Reporting_Series_Handler,
		},
		{
			MethodName: "Export",
			Handler:    _Reporting_Export_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "hephaestus.proto",
}

const (
	Imports_TrashBatch_FullMethodName   = "/income.Imports/TrashBatch"
	Imports_ReadSheet_FullMethodName    = "/income.Imports/ReadSheet"
	Imports_GoogleStage_FullMethodName  = "/income.Imports/GoogleStage"
	Imports_CreateSource_FullMethodName = "/income.Imports/CreateSource"
	Imports_ListSources_FullMethodName  = "/income.Imports/ListSources"
	Imports_DeleteSource_FullMethodName = "/income.Imports/DeleteSource"
	Imports_Stage_FullMethodName        = "/income.Imports/Stage"
	Imports_ListBatches_FullMethodName  = "/income.Imports/ListBatches"
	Imports_GetBatch_FullMethodName     = "/income.Imports/GetBatch"
	Imports_Preview_FullMethodName      = "/income.Imports/Preview"
	Imports_ListRows_FullMethodName     = "/income.Imports/ListRows"
	Imports_Commit_FullMethodName       = "/income.Imports/Commit"
	Imports_Cancel_FullMethodName       = "/income.Imports/Cancel"
)

// ImportsClient is the client API for Imports service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type ImportsClient interface {
	TrashBatch(ctx context.Context, in *TrashBatchRequest, opts ...grpc.CallOption) (*Batch, error)
	ReadSheet(ctx context.Context, in *ReadSheetRequest, opts ...grpc.CallOption) (*SheetData, error)
	GoogleStage(ctx context.Context, in *GoogleStageRequest, opts ...grpc.CallOption) (*Batch, error)
	CreateSource(ctx context.Context, in *CreateSourceRequest, opts ...grpc.CallOption) (*Source, error)
	ListSources(ctx context.Context, in *ListSourcesRequest, opts ...grpc.CallOption) (*SourceList, error)
	DeleteSource(ctx context.Context, in *DeleteSourceRequest, opts ...grpc.CallOption) (*Empty, error)
	Stage(ctx context.Context, in *StageRequest, opts ...grpc.CallOption) (*Batch, error)
	ListBatches(ctx context.Context, in *ListBatchesRequest, opts ...grpc.CallOption) (*BatchList, error)
	GetBatch(ctx context.Context, in *GetBatchRequest, opts ...grpc.CallOption) (*Batch, error)
	Preview(ctx context.Context, in *PreviewRequest, opts ...grpc.CallOption) (*Batch, error)
	ListRows(ctx context.Context, in *ListRowsRequest, opts ...grpc.CallOption) (*BatchRows, error)
	Commit(ctx context.Context, in *CommitRequest, opts ...grpc.CallOption) (*Batch, error)
	Cancel(ctx context.Context, in *CancelRequest, opts ...grpc.CallOption) (*Batch, error)
}

type importsClient struct {
	cc grpc.ClientConnInterface
}

func NewImportsClient(cc grpc.ClientConnInterface) ImportsClient {
	return &importsClient{cc}
}

func (c *importsClient) TrashBatch(ctx context.Context, in *TrashBatchRequest, opts ...grpc.CallOption) (*Batch, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Batch)
	err := c.cc.Invoke(ctx, Imports_TrashBatch_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *importsClient) ReadSheet(ctx context.Context, in *ReadSheetRequest, opts ...grpc.CallOption) (*SheetData, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SheetData)
	err := c.cc.Invoke(ctx, Imports_ReadSheet_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *importsClient) GoogleStage(ctx context.Context, in *GoogleStageRequest, opts ...grpc.CallOption) (*Batch, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Batch)
	err := c.cc.Invoke(ctx, Imports_GoogleStage_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *importsClient) CreateSource(ctx context.Context, in *CreateSourceRequest, opts ...grpc.CallOption) (*Source, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Source)
	err := c.cc.Invoke(ctx, Imports_CreateSource_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *importsClient) ListSources(ctx context.Context, in *ListSourcesRequest, opts ...grpc.CallOption) (*SourceList, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SourceList)
	err := c.cc.Invoke(ctx, Imports_ListSources_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *importsClient) DeleteSource(ctx context.Context, in *DeleteSourceRequest, opts ...grpc.CallOption) (*Empty, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Empty)
	err := c.cc.Invoke(ctx, Imports_DeleteSource_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *importsClient) Stage(ctx context.Context, in *StageRequest, opts ...grpc.CallOption) (*Batch, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Batch)
	err := c.cc.Invoke(ctx, Imports_Stage_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *importsClient) ListBatches(ctx context.Context, in *ListBatchesRequest, opts ...grpc.CallOption) (*BatchList, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(BatchList)
	err := c.cc.Invoke(ctx, Imports_ListBatches_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *importsClient) GetBatch(ctx context.Context, in *GetBatchRequest, opts ...grpc.CallOption) (*Batch, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Batch)
	err := c.cc.Invoke(ctx, Imports_GetBatch_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *importsClient) Preview(ctx context.Context, in *PreviewRequest, opts ...grpc.CallOption) (*Batch, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Batch)
	err := c.cc.Invoke(ctx, Imports_Preview_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *importsClient) ListRows(ctx context.Context, in *ListRowsRequest, opts ...grpc.CallOption) (*BatchRows, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(BatchRows)
	err := c.cc.Invoke(ctx, Imports_ListRows_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *importsClient) Commit(ctx context.Context, in *CommitRequest, opts ...grpc.CallOption) (*Batch, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Batch)
	err := c.cc.Invoke(ctx, Imports_Commit_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *importsClient) Cancel(ctx context.Context, in *CancelRequest, opts ...grpc.CallOption) (*Batch, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Batch)
	err := c.cc.Invoke(ctx, Imports_Cancel_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// ImportsServer is the server API for Imports service.
// All implementations must embed UnimplementedImportsServer
// for forward compatibility.
type ImportsServer interface {
	TrashBatch(context.Context, *TrashBatchRequest) (*Batch, error)
	ReadSheet(context.Context, *ReadSheetRequest) (*SheetData, error)
	GoogleStage(context.Context, *GoogleStageRequest) (*Batch, error)
	CreateSource(context.Context, *CreateSourceRequest) (*Source, error)
	ListSources(context.Context, *ListSourcesRequest) (*SourceList, error)
	DeleteSource(context.Context, *DeleteSourceRequest) (*Empty, error)
	Stage(context.Context, *StageRequest) (*Batch, error)
	ListBatches(context.Context, *ListBatchesRequest) (*BatchList, error)
	GetBatch(context.Context, *GetBatchRequest) (*Batch, error)
	Preview(context.Context, *PreviewRequest) (*Batch, error)
	ListRows(context.Context, *ListRowsRequest) (*BatchRows, error)
	Commit(context.Context, *CommitRequest) (*Batch, error)
	Cancel(context.Context, *CancelRequest) (*Batch, error)
	mustEmbedUnimplementedImportsServer()
}

// UnimplementedImportsServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedImportsServer struct{}

func (UnimplementedImportsServer) TrashBatch(context.Context, *TrashBatchRequest) (*Batch, error) {
	return nil, status.Errorf(codes.Unimplemented, "method TrashBatch not implemented")
}
func (UnimplementedImportsServer) ReadSheet(context.Context, *ReadSheetRequest) (*SheetData, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ReadSheet not implemented")
}
func (UnimplementedImportsServer) GoogleStage(context.Context, *GoogleStageRequest) (*Batch, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GoogleStage not implemented")
}
func (UnimplementedImportsServer) CreateSource(context.Context, *CreateSourceRequest) (*Source, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreateSource not implemented")
}
func (UnimplementedImportsServer) ListSources(context.Context, *ListSourcesRequest) (*SourceList, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ListSources not implemented")
}
func (UnimplementedImportsServer) DeleteSource(context.Context, *DeleteSourceRequest) (*Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DeleteSource not implemented")
}
func (UnimplementedImportsServer) Stage(context.Context, *StageRequest) (*Batch, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Stage not implemented")
}
func (UnimplementedImportsServer) ListBatches(context.Context, *ListBatchesRequest) (*BatchList, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ListBatches not implemented")
}
func (UnimplementedImportsServer) GetBatch(context.Context, *GetBatchRequest) (*Batch, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetBatch not implemented")
}
func (UnimplementedImportsServer) Preview(context.Context, *PreviewRequest) (*Batch, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Preview not implemented")
}
func (UnimplementedImportsServer) ListRows(context.Context, *ListRowsRequest) (*BatchRows, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ListRows not implemented")
}
func (UnimplementedImportsServer) Commit(context.Context, *CommitRequest) (*Batch, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Commit not implemented")
}
func (UnimplementedImportsServer) Cancel(context.Context, *CancelRequest) (*Batch, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Cancel not implemented")
}
func (UnimplementedImportsServer) mustEmbedUnimplementedImportsServer() {}
func (UnimplementedImportsServer) testEmbeddedByValue()                 {}

// UnsafeImportsServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to ImportsServer will
// result in compilation errors.
type UnsafeImportsServer interface {
	mustEmbedUnimplementedImportsServer()
}

func RegisterImportsServer(s grpc.ServiceRegistrar, srv ImportsServer) {
	// If the following call pancis, it indicates UnimplementedImportsServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&Imports_ServiceDesc, srv)
}

func _Imports_TrashBatch_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(TrashBatchRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ImportsServer).TrashBatch(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Imports_TrashBatch_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ImportsServer).TrashBatch(ctx, req.(*TrashBatchRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Imports_ReadSheet_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ReadSheetRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ImportsServer).ReadSheet(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Imports_ReadSheet_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ImportsServer).ReadSheet(ctx, req.(*ReadSheetRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Imports_GoogleStage_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GoogleStageRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ImportsServer).GoogleStage(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Imports_GoogleStage_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ImportsServer).GoogleStage(ctx, req.(*GoogleStageRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Imports_CreateSource_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateSourceRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ImportsServer).CreateSource(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Imports_CreateSource_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ImportsServer).CreateSource(ctx, req.(*CreateSourceRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Imports_ListSources_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListSourcesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ImportsServer).ListSources(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Imports_ListSources_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ImportsServer).ListSources(ctx, req.(*ListSourcesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Imports_DeleteSource_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteSourceRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ImportsServer).DeleteSource(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Imports_DeleteSource_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ImportsServer).DeleteSource(ctx, req.(*DeleteSourceRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Imports_Stage_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(StageRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ImportsServer).Stage(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Imports_Stage_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ImportsServer).Stage(ctx, req.(*StageRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Imports_ListBatches_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListBatchesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ImportsServer).ListBatches(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Imports_ListBatches_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ImportsServer).ListBatches(ctx, req.(*ListBatchesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Imports_GetBatch_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetBatchRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ImportsServer).GetBatch(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Imports_GetBatch_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ImportsServer).GetBatch(ctx, req.(*GetBatchRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Imports_Preview_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PreviewRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ImportsServer).Preview(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Imports_Preview_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ImportsServer).Preview(ctx, req.(*PreviewRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Imports_ListRows_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListRowsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ImportsServer).ListRows(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Imports_ListRows_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ImportsServer).ListRows(ctx, req.(*ListRowsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Imports_Commit_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CommitRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ImportsServer).Commit(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Imports_Commit_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ImportsServer).Commit(ctx, req.(*CommitRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Imports_Cancel_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CancelRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ImportsServer).Cancel(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Imports_Cancel_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ImportsServer).Cancel(ctx, req.(*CancelRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// Imports_ServiceDesc is the grpc.ServiceDesc for Imports service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Imports_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "income.Imports",
	HandlerType: (*ImportsServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "TrashBatch",
			Handler:    _Imports_TrashBatch_Handler,
		},
		{
			MethodName: "ReadSheet",
			Handler:    _Imports_ReadSheet_Handler,
		},
		{
			MethodName: "GoogleStage",
			Handler:    _Imports_GoogleStage_Handler,
		},
		{
			MethodName: "CreateSource",
			Handler:    _Imports_CreateSource_Handler,
		},
		{
			MethodName: "ListSources",
			Handler:    _Imports_ListSources_Handler,
		},
		{
			MethodName: "DeleteSource",
			Handler:    _Imports_DeleteSource_Handler,
		},
		{
			MethodName: "Stage",
			Handler:    _Imports_Stage_Handler,
		},
		{
			MethodName: "ListBatches",
			Handler:    _Imports_ListBatches_Handler,
		},
		{
			MethodName: "GetBatch",
			Handler:    _Imports_GetBatch_Handler,
		},
		{
			MethodName: "Preview",
			Handler:    _Imports_Preview_Handler,
		},
		{
			MethodName: "ListRows",
			Handler:    _Imports_ListRows_Handler,
		},
		{
			MethodName: "Commit",
			Handler:    _Imports_Commit_Handler,
		},
		{
			MethodName: "Cancel",
			Handler:    _Imports_Cancel_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "hephaestus.proto",
}

const (
	Health_Health_FullMethodName = "/income.Health/Health"
)

// HealthClient is the client API for Health service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type HealthClient interface {
	Health(ctx context.Context, in *HealthRequest, opts ...grpc.CallOption) (*HealthResp, error)
}

type healthClient struct {
	cc grpc.ClientConnInterface
}

func NewHealthClient(cc grpc.ClientConnInterface) HealthClient {
	return &healthClient{cc}
}

func (c *healthClient) Health(ctx context.Context, in *HealthRequest, opts ...grpc.CallOption) (*HealthResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(HealthResp)
	err := c.cc.Invoke(ctx, Health_Health_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// HealthServer is the server API for Health service.
// All implementations must embed UnimplementedHealthServer
// for forward compatibility.
type HealthServer interface {
	Health(context.Context, *HealthRequest) (*HealthResp, error)
	mustEmbedUnimplementedHealthServer()
}

// UnimplementedHealthServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedHealthServer struct{}

func (UnimplementedHealthServer) Health(context.Context, *HealthRequest) (*HealthResp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Health not implemented")
}
func (UnimplementedHealthServer) mustEmbedUnimplementedHealthServer() {}
func (UnimplementedHealthServer) testEmbeddedByValue()                {}

// UnsafeHealthServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to HealthServer will
// result in compilation errors.
type UnsafeHealthServer interface {
	mustEmbedUnimplementedHealthServer()
}

func RegisterHealthServer(s grpc.ServiceRegistrar, srv HealthServer) {
	// If the following call pancis, it indicates UnimplementedHealthServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&Health_ServiceDesc, srv)
}

func _Health_Health_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(HealthRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(HealthServer).Health(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Health_Health_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(HealthServer).Health(ctx, req.(*HealthRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// Health_ServiceDesc is the grpc.ServiceDesc for Health service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Health_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "income.Health",
	HandlerType: (*HealthServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Health",
			Handler:    _Health_Health_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "hephaestus.proto",
}
