// Code generated by goctl. DO NOT EDIT.
// goctl 1.9.2

package handler

import (
	"net/http"

	auth "jian-unified-system/hephaestus/hephaestus-api/internal/handler/auth"
	google "jian-unified-system/hephaestus/hephaestus-api/internal/handler/google"
	health "jian-unified-system/hephaestus/hephaestus-api/internal/handler/health"
	imports "jian-unified-system/hephaestus/hephaestus-api/internal/handler/imports"
	records "jian-unified-system/hephaestus/hephaestus-api/internal/handler/records"
	reporting "jian-unified-system/hephaestus/hephaestus-api/internal/handler/reporting"
	"jian-unified-system/hephaestus/hephaestus-api/internal/svc"

	"github.com/zeromicro/go-zero/rest"
)

func RegisterHandlers(server *rest.Server, serverCtx *svc.ServiceContext) {
	server.AddRoutes(
		[]rest.Route{
			{
				Method:  http.MethodGet,
				Path:    "/auth/callback",
				Handler: auth.AuthCallbackHandler(serverCtx),
			},
			{
				Method:  http.MethodGet,
				Path:    "/auth/start",
				Handler: auth.AuthStartHandler(serverCtx),
			},
			{
				Method:  http.MethodGet,
				Path:    "/session",
				Handler: auth.SessionHandler(serverCtx),
			},
			{
				Method:  http.MethodDelete,
				Path:    "/session",
				Handler: auth.LogoutHandler(serverCtx),
			},
		},
		rest.WithPrefix("/api/v1"),
	)

	server.AddRoutes(
		[]rest.Route{
			{
				Method:  http.MethodGet,
				Path:    "/callback",
				Handler: google.GoogleCallbackHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/connect",
				Handler: google.GoogleConnectHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/disconnect",
				Handler: google.GoogleDisconnectHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/imports",
				Handler: google.GoogleStageHandler(serverCtx),
			},
			{
				Method:  http.MethodGet,
				Path:    "/status",
				Handler: google.GoogleStatusHandler(serverCtx),
			},
		},
		rest.WithPrefix("/api/v1/google"),
	)

	server.AddRoutes(
		[]rest.Route{
			{
				Method:  http.MethodGet,
				Path:    "/health/ready",
				Handler: health.HealthHandler(serverCtx),
			},
		},
		rest.WithPrefix("/api/v1"),
	)

	server.AddRoutes(
		[]rest.Route{
			{
				Method:  http.MethodPost,
				Path:    "/imports",
				Handler: imports.StageHandler(serverCtx),
			},
			{
				Method:  http.MethodGet,
				Path:    "/imports",
				Handler: imports.ListBatchesHandler(serverCtx),
			},
			{
				Method:  http.MethodGet,
				Path:    "/imports/:id",
				Handler: imports.GetBatchHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/imports/:id/cancel",
				Handler: imports.CancelHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/imports/:id/commit",
				Handler: imports.CommitHandler(serverCtx),
			},
			{
				Method:  http.MethodPut,
				Path:    "/imports/:id/mapping",
				Handler: imports.PreviewHandler(serverCtx),
			},
			{
				Method:  http.MethodGet,
				Path:    "/imports/:id/rows",
				Handler: imports.ListRowsHandler(serverCtx),
			},
			{
				Method:  http.MethodGet,
				Path:    "/imports/:id/sheet",
				Handler: imports.ReadSheetHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/imports/:id/trash",
				Handler: imports.TrashBatchHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/sources",
				Handler: imports.CreateSourceHandler(serverCtx),
			},
			{
				Method:  http.MethodGet,
				Path:    "/sources",
				Handler: imports.ListSourcesHandler(serverCtx),
			},
			{
				Method:  http.MethodDelete,
				Path:    "/sources/:id",
				Handler: imports.DeleteSourceHandler(serverCtx),
			},
		},
		rest.WithPrefix("/api/v1"),
	)

	server.AddRoutes(
		[]rest.Route{
			{
				Method:  http.MethodPost,
				Path:    "/work-records",
				Handler: records.CreateRecordHandler(serverCtx),
			},
			{
				Method:  http.MethodGet,
				Path:    "/work-records",
				Handler: records.ListRecordsHandler(serverCtx),
			},
			{
				Method:  http.MethodGet,
				Path:    "/work-records/:id",
				Handler: records.GetRecordHandler(serverCtx),
			},
			{
				Method:  http.MethodPatch,
				Path:    "/work-records/:id",
				Handler: records.UpdateRecordHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/work-records/:id/archive",
				Handler: records.ArchiveRecordHandler(serverCtx),
			},
			{
				Method:  http.MethodDelete,
				Path:    "/work-records/:id/overrides/:field",
				Handler: records.ClearOverrideHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/work-records/:id/restore",
				Handler: records.RestoreRecordHandler(serverCtx),
			},
			{
				Method:  http.MethodGet,
				Path:    "/work-records/:id/revisions",
				Handler: records.ListRevisionsHandler(serverCtx),
			},
		},
		rest.WithPrefix("/api/v1"),
	)

	server.AddRoutes(
		[]rest.Route{
			{
				Method:  http.MethodGet,
				Path:    "/income-calendar",
				Handler: reporting.CalendarHandler(serverCtx),
			},
			{
				Method:  http.MethodGet,
				Path:    "/income-export.csv",
				Handler: reporting.ExportHandler(serverCtx),
			},
			{
				Method:  http.MethodGet,
				Path:    "/income-series",
				Handler: reporting.SeriesHandler(serverCtx),
			},
			{
				Method:  http.MethodGet,
				Path:    "/income-summary",
				Handler: reporting.SummaryHandler(serverCtx),
			},
		},
		rest.WithPrefix("/api/v1"),
	)
}
