// Code generated by goctl. DO NOT EDIT.
// goctl 1.7.6

package types

type BaseResponse struct {
	Code    int    `json:"code"`
	Message string `json:"message"`
}

type Data struct {
	OptionsJson string `json:"options_json"` // WebAuthn注册选项
	SessionID   string `json:"session_id"`   // 会话标识
}

type LoginFinishReq struct {
	SessionID string `json:"session_id" validate:"required"`
	Assertion string `json:"assertion" validate:"required"` // 前端返回的断言数据
}

type LoginFinishResp struct {
	BaseResponse
	Token string
}

type LoginStartReq struct {
}

type LoginStartResp struct {
	BaseResponse
	Data
}

type RegFinishReq struct {
	SessionID  string `json:"session_id" validate:"required"`
	Credential string `json:"credential" validate:"required"` // 前端返回的认证数据
}

type RegStartReq struct {
	UserName    string `json:"user_name" validate:"required"`
	DisplayName string `json:"display_name"`
}

type RegStartResp struct {
	BaseResponse
	Data
}
