// Code generated by goctl. DO NOT EDIT.
// goctl 1.9.2
// Source: apollo-rpc.proto

package passkeys

import (
	"context"

	"jian-unified-system/apollo/apollo-rpc/apollo"

	"github.com/zeromicro/go-zero/zrpc"
	"google.golang.org/grpc"
)

type (
	AccountProfile                 = apollo.AccountProfile
	AddContactReq                  = apollo.AddContactReq
	AddContactResp                 = apollo.AddContactResp
	ChangeNotificationEmailReq     = apollo.ChangeNotificationEmailReq
	ChangePasswordReq              = apollo.ChangePasswordReq
	DeleteAccountReq               = apollo.DeleteAccountReq
	Empty                          = apollo.Empty
	FindTenPasskeysReq             = apollo.FindTenPasskeysReq
	FindTenPasskeysResp            = apollo.FindTenPasskeysResp
	FindTenSubsystemTokensReq      = apollo.FindTenSubsystemTokensReq
	FindTenSubsystemTokensResp     = apollo.FindTenSubsystemTokensResp
	GenerateSubsystemTokenReq      = apollo.GenerateSubsystemTokenReq
	GenerateSubsystemTokenResp     = apollo.GenerateSubsystemTokenResp
	GoogleSheetRow                 = apollo.GoogleSheetRow
	GoogleSheetsReq                = apollo.GoogleSheetsReq
	GoogleSheetsResp               = apollo.GoogleSheetsResp
	LoginReq                       = apollo.LoginReq
	LoginResp                      = apollo.LoginResp
	Passkey                        = apollo.Passkey
	PasskeysFinishLoginReq         = apollo.PasskeysFinishLoginReq
	PasskeysFinishLoginResp        = apollo.PasskeysFinishLoginResp
	PasskeysFinishRegistrationReq  = apollo.PasskeysFinishRegistrationReq
	PasskeysFinishRegistrationResp = apollo.PasskeysFinishRegistrationResp
	PasskeysStartLoginResp         = apollo.PasskeysStartLoginResp
	PasskeysStartRegistrationReq   = apollo.PasskeysStartRegistrationReq
	PasskeysStartRegistrationResp  = apollo.PasskeysStartRegistrationResp
	PasswordUpdatedDate            = apollo.PasswordUpdatedDate
	RegistrationReq                = apollo.RegistrationReq
	RemoveContactReq               = apollo.RemoveContactReq
	RemoveNotificationEmailReq     = apollo.RemoveNotificationEmailReq
	RemovePasskeyReq               = apollo.RemovePasskeyReq
	RemovePasskeyResp              = apollo.RemovePasskeyResp
	RemoveSubsystemTokenReq        = apollo.RemoveSubsystemTokenReq
	RemoveSubsystemTokenResp       = apollo.RemoveSubsystemTokenResp
	SSOAuthorizeReq                = apollo.SSOAuthorizeReq
	SSOCodeResp                    = apollo.SSOCodeResp
	SSOExchangeReq                 = apollo.SSOExchangeReq
	SSOLogoutReq                   = apollo.SSOLogoutReq
	SSOSessionResp                 = apollo.SSOSessionResp
	SSOTokenReq                    = apollo.SSOTokenReq
	SessionVersionReq              = apollo.SessionVersionReq
	SessionVersionResp             = apollo.SessionVersionResp
	StartAuthorizationReq          = apollo.StartAuthorizationReq
	StartAuthorizationResp         = apollo.StartAuthorizationResp
	SubsystemToken                 = apollo.SubsystemToken
	ThirdPartyAccountInfo          = apollo.ThirdPartyAccountInfo
	ThirdPartyAccounts             = apollo.ThirdPartyAccounts
	ThirdPartyBindReq              = apollo.ThirdPartyBindReq
	ThirdPartyContinueReq          = apollo.ThirdPartyContinueReq
	ThirdPartyContinueResp         = apollo.ThirdPartyContinueResp
	ThirdPartyGetInfoReq           = apollo.ThirdPartyGetInfoReq
	ThirdPartyGetInfoResp          = apollo.ThirdPartyGetInfoResp
	ThirdPartyRemoveReq            = apollo.ThirdPartyRemoveReq
	UpdateBirthdayReq              = apollo.UpdateBirthdayReq
	UpdateLanguageReq              = apollo.UpdateLanguageReq
	UpdateNameReq                  = apollo.UpdateNameReq
	UserContact                    = apollo.UserContact
	UserInfoReq                    = apollo.UserInfoReq
	UserInfoResp                   = apollo.UserInfoResp
	UserSecurityInfoReq            = apollo.UserSecurityInfoReq
	UserSecurityInfoResp           = apollo.UserSecurityInfoResp
	ValidateSubsystemTokenReq      = apollo.ValidateSubsystemTokenReq
	ValidateSubsystemTokenResp     = apollo.ValidateSubsystemTokenResp

	Passkeys interface {
		StartRegistration(ctx context.Context, in *PasskeysStartRegistrationReq, opts ...grpc.CallOption) (*PasskeysStartRegistrationResp, error)
		FinishRegistration(ctx context.Context, in *PasskeysFinishRegistrationReq, opts ...grpc.CallOption) (*PasskeysFinishRegistrationResp, error)
		StartLogin(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*PasskeysStartLoginResp, error)
		FinishLogin(ctx context.Context, in *PasskeysFinishLoginReq, opts ...grpc.CallOption) (*PasskeysFinishLoginResp, error)
		FindTenPasskeys(ctx context.Context, in *FindTenPasskeysReq, opts ...grpc.CallOption) (*FindTenPasskeysResp, error)
		RemovePasskey(ctx context.Context, in *RemovePasskeyReq, opts ...grpc.CallOption) (*RemovePasskeyResp, error)
	}

	defaultPasskeys struct {
		cli zrpc.Client
	}
)

func NewPasskeys(cli zrpc.Client) Passkeys {
	return &defaultPasskeys{
		cli: cli,
	}
}

func (m *defaultPasskeys) StartRegistration(ctx context.Context, in *PasskeysStartRegistrationReq, opts ...grpc.CallOption) (*PasskeysStartRegistrationResp, error) {
	client := apollo.NewPasskeysClient(m.cli.Conn())
	return client.StartRegistration(ctx, in, opts...)
}

func (m *defaultPasskeys) FinishRegistration(ctx context.Context, in *PasskeysFinishRegistrationReq, opts ...grpc.CallOption) (*PasskeysFinishRegistrationResp, error) {
	client := apollo.NewPasskeysClient(m.cli.Conn())
	return client.FinishRegistration(ctx, in, opts...)
}

func (m *defaultPasskeys) StartLogin(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*PasskeysStartLoginResp, error) {
	client := apollo.NewPasskeysClient(m.cli.Conn())
	return client.StartLogin(ctx, in, opts...)
}

func (m *defaultPasskeys) FinishLogin(ctx context.Context, in *PasskeysFinishLoginReq, opts ...grpc.CallOption) (*PasskeysFinishLoginResp, error) {
	client := apollo.NewPasskeysClient(m.cli.Conn())
	return client.FinishLogin(ctx, in, opts...)
}

func (m *defaultPasskeys) FindTenPasskeys(ctx context.Context, in *FindTenPasskeysReq, opts ...grpc.CallOption) (*FindTenPasskeysResp, error) {
	client := apollo.NewPasskeysClient(m.cli.Conn())
	return client.FindTenPasskeys(ctx, in, opts...)
}

func (m *defaultPasskeys) RemovePasskey(ctx context.Context, in *RemovePasskeyReq, opts ...grpc.CallOption) (*RemovePasskeyResp, error) {
	client := apollo.NewPasskeysClient(m.cli.Conn())
	return client.RemovePasskey(ctx, in, opts...)
}
