// Code generated by goctl. DO NOT EDIT.
// versions:
//  goctl version: 1.8.5

package apollo

import (
	"context"
	"database/sql"
	"fmt"
	"jian-unified-system/jus-core/data/mysql/model"
	"strings"
	"time"

	"github.com/zeromicro/go-zero/core/stores/builder"
	"github.com/zeromicro/go-zero/core/stores/cache"
	"github.com/zeromicro/go-zero/core/stores/sqlc"
	"github.com/zeromicro/go-zero/core/stores/sqlx"
	"github.com/zeromicro/go-zero/core/stringx"
)

var (
	passkeyFieldNames          = builder.RawFieldNames(&Passkey{})
	passkeyRows                = strings.Join(passkeyFieldNames, ",")
	passkeyRowsExpectAutoSet   = strings.Join(stringx.Remove(passkeyFieldNames, "`create_at`", "`create_time`", "`created_at`", "`update_at`", "`update_time`", "`updated_at`"), ",")
	passkeyRowsWithPlaceHolder = strings.Join(stringx.Remove(passkeyFieldNames, "`credential_id`", "`create_at`", "`create_time`", "`created_at`", "`update_at`", "`update_time`", "`updated_at`"), "=?,") + "=?"

	cacheApolloPasskeyCredentialIdPrefix = "cache:apollo:passkey:credentialId:"
)

type (
	passkeyModel interface {
		Insert(ctx context.Context, data *Passkey) (sql.Result, error)
		FindOne(ctx context.Context, credentialId string) (*Passkey, error)
		FindBatch(ctx context.Context, userId int64, page int64) (*[]Passkey, error)
		CountPasskeys(ctx context.Context, userId int64) (int64, error)
		Update(ctx context.Context, data *Passkey, userId int64) error
		Delete(ctx context.Context, credentialId string) error
		DeleteOrRestorePasskey(ctx context.Context, data *Passkey) error
		EnableOrDisablePasskey(ctx context.Context, data *Passkey) error
	}

	defaultPasskeyModel struct {
		sqlc.CachedConn
		table string
	}

	Passkey struct {
		CredentialId string         `db:"credential_id"`
		UserId       int64          `db:"user_id"`
		DisplayName  string         `db:"display_name"`
		PublicKey    string         `db:"public_key"`
		SignCount    int64          `db:"sign_count"`
		Transports   sql.NullString `db:"transports"`
		CreatedAt    time.Time      `db:"created_at"`
		LastUsedAt   time.Time      `db:"last_used_at"`
		IsEnabled    int64          `db:"is_enabled"` // 0: disabled; 1: enabled
		IsDeleted    int64          `db:"is_deleted"`
	}
)

func newPasskeyModel(conn sqlx.SqlConn, c cache.CacheConf, opts ...cache.Option) *defaultPasskeyModel {
	return &defaultPasskeyModel{
		CachedConn: sqlc.NewConn(conn, c, opts...),
		table:      "`passkey`",
	}
}

func (m *defaultPasskeyModel) Delete(ctx context.Context, credentialId string) error {
	apolloPasskeyCredentialIdKey := fmt.Sprintf("%s%v", cacheApolloPasskeyCredentialIdPrefix, credentialId)
	_, err := m.ExecCtx(ctx, func(ctx context.Context, conn sqlx.SqlConn) (result sql.Result, err error) {
		query := fmt.Sprintf("delete from %s where `credential_id` = ?", m.table)
		return conn.ExecCtx(ctx, query, credentialId)
	}, apolloPasskeyCredentialIdKey)
	return err
}

func (m *defaultPasskeyModel) DeleteOrRestorePasskey(ctx context.Context, data *Passkey) error {
	apolloPasskeyCredentialIdKey := fmt.Sprintf("%s%v", cacheApolloPasskeyCredentialIdPrefix, data.CredentialId)
	_, err := m.ExecCtx(ctx, func(ctx context.Context, conn sqlx.SqlConn) (result sql.Result, err error) {
		query := fmt.Sprintf("update %s set `is_deleted` = ? where `credential_id` = ? and `user_id` = ? ", m.table)
		return conn.ExecCtx(ctx, query, data.IsDeleted, data.CredentialId, data.UserId)
	}, apolloPasskeyCredentialIdKey)
	return err
}

func (m *defaultPasskeyModel) EnableOrDisablePasskey(ctx context.Context, data *Passkey) error {
	apolloPasskeyCredentialIdKey := fmt.Sprintf("%s%v", cacheApolloPasskeyCredentialIdPrefix, data.CredentialId)
	_, err := m.ExecCtx(ctx, func(ctx context.Context, conn sqlx.SqlConn) (result sql.Result, err error) {
		query := fmt.Sprintf("update %s set `is_enabled` = ? where `credential_id` = ? and `user_id` = ? ", m.table)
		return conn.ExecCtx(ctx, query, data.IsEnabled, data.CredentialId, data.UserId)
	}, apolloPasskeyCredentialIdKey)
	return err
}

func (m *defaultPasskeyModel) FindOne(ctx context.Context, credentialId string) (*Passkey, error) {
	apolloPasskeyCredentialIdKey := fmt.Sprintf("%s%v", cacheApolloPasskeyCredentialIdPrefix, credentialId)
	var resp Passkey
	err := m.QueryRowCtx(ctx, &resp, apolloPasskeyCredentialIdKey, func(ctx context.Context, conn sqlx.SqlConn, v any) error {
		query := fmt.Sprintf("select %s from %s where `credential_id` = ? and `is_deleted` = 0 limit 1", passkeyRows, m.table)
		return conn.QueryRowCtx(ctx, v, query, credentialId)
	})
	switch err {
	case nil:
		return &resp, nil
	case sqlc.ErrNotFound:
		return nil, model.ErrNotFound
	default:
		return nil, err
	}
}

func (m *defaultPasskeyModel) FindBatch(ctx context.Context, userId int64, page int64) (*[]Passkey, error) {
	var resp []Passkey
	offset := (page - 1) * 10
	query := fmt.Sprintf("select %s from %s where `user_id` = ? /*and `is_enabled` = 1*/ and `is_deleted` = 0 ORDER BY `created_at` DESC limit 10 OFFSET ?", passkeyRows, m.table)
	err := m.QueryRowsNoCacheCtx(ctx, &resp, query, userId, offset)
	switch err {
	case nil:
		return &resp, nil
	case sqlc.ErrNotFound:
		return nil, model.ErrNotFound
	default:
		return nil, err
	}
}

func (m *defaultPasskeyModel) CountPasskeys(ctx context.Context, userId int64) (int64, error) {
	var resp int64
	query := fmt.Sprintf("select COUNT(`credential_id`) from %s where `user_id` = ?", m.table)
	err := m.QueryRowNoCacheCtx(ctx, &resp, query, userId)

	switch err {
	case nil:
		return resp, nil
	case sqlc.ErrNotFound:
		return 0, model.ErrNotFound
	default:
		return 0, err
	}
}

func (m *defaultPasskeyModel) Insert(ctx context.Context, data *Passkey) (sql.Result, error) {
	apolloPasskeyCredentialIdKey := fmt.Sprintf("%s%v", cacheApolloPasskeyCredentialIdPrefix, data.CredentialId)
	ret, err := m.ExecCtx(ctx, func(ctx context.Context, conn sqlx.SqlConn) (result sql.Result, err error) {
		query := fmt.Sprintf("insert into %s (%s) values (?, ?, ?, ?, ?, ?, ?)", m.table, passkeyRowsExpectAutoSet)
		return conn.ExecCtx(ctx, query, data.CredentialId, data.UserId, data.DisplayName, data.PublicKey, data.SignCount, data.Transports, data.LastUsedAt)
	}, apolloPasskeyCredentialIdKey)
	return ret, err
}

func (m *defaultPasskeyModel) Update(ctx context.Context, data *Passkey, userId int64) error {
	apolloPasskeyCredentialIdKey := fmt.Sprintf("%s%v", cacheApolloPasskeyCredentialIdPrefix, data.CredentialId)
	_, err := m.ExecCtx(ctx, func(ctx context.Context, conn sqlx.SqlConn) (result sql.Result, err error) {
		query := fmt.Sprintf("update %s set %s where `credential_id` = ? and `user_id` = ? ", m.table, passkeyRowsWithPlaceHolder)
		return conn.ExecCtx(ctx, query, data.CredentialId, data.UserId, data.DisplayName, data.PublicKey, data.SignCount, data.Transports, data.LastUsedAt, data.IsEnabled, data.IsDeleted, userId)
	}, apolloPasskeyCredentialIdKey)
	return err
}

func (m *defaultPasskeyModel) formatPrimary(primary any) string {
	return fmt.Sprintf("%s%v", cacheApolloPasskeyCredentialIdPrefix, primary)
}

func (m *defaultPasskeyModel) queryPrimary(ctx context.Context, conn sqlx.SqlConn, v, primary any) error {
	query := fmt.Sprintf("select %s from %s where `credential_id` = ? limit 1", passkeyRows, m.table)
	return conn.QueryRowCtx(ctx, v, query, primary)
}

func (m *defaultPasskeyModel) tableName() string {
	return m.table
}
