// Code generated by goctl. DO NOT EDIT.
// goctl 1.8.5
// Source: jquantum-rpc.proto

package job

import (
	"context"

	"jian-unified-system/jquantum/jquantum-rpc/jquantum"

	"github.com/zeromicro/go-zero/zrpc"
	"google.golang.org/grpc"
)

type (
	Empty = jquantum.Empty

	Job interface {
		// 注册
		Submit(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*Empty, error)
	}

	defaultJob struct {
		cli zrpc.Client
	}
)

func NewJob(cli zrpc.Client) Job {
	return &defaultJob{
		cli: cli,
	}
}

// 注册
func (m *defaultJob) Submit(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*Empty, error) {
	client := jquantum.NewJobClient(m.cli.Conn())
	return client.Submit(ctx, in, opts...)
}
