// Code generated by goctl. DO NOT EDIT.
// goctl 1.9.2
// Source: apollo-rpc.proto

package server

import (
	"context"

	"jian-unified-system/apollo/apollo-rpc/apollo"
	"jian-unified-system/apollo/apollo-rpc/internal/logic/sso"
	"jian-unified-system/apollo/apollo-rpc/internal/svc"
)

type SsoServer struct {
	svcCtx *svc.ServiceContext
	apollo.UnimplementedSsoServer
}

func NewSsoServer(svcCtx *svc.ServiceContext) *SsoServer {
	return &SsoServer{
		svcCtx: svcCtx,
	}
}

// Authenticated server-to-server Sheets broker; Google credentials never leave Apollo.
func (s *SsoServer) GoogleSheets(ctx context.Context, in *apollo.GoogleSheetsReq) (*apollo.GoogleSheetsResp, error) {
	l := ssologic.NewGoogleSheetsLogic(ctx, s.svcCtx)
	return l.GoogleSheets(in)
}

func (s *SsoServer) Logout(ctx context.Context, in *apollo.SSOLogoutReq) (*apollo.Empty, error) {
	l := ssologic.NewLogoutLogic(ctx, s.svcCtx)
	return l.Logout(in)
}

func (s *SsoServer) Authorize(ctx context.Context, in *apollo.SSOAuthorizeReq) (*apollo.SSOCodeResp, error) {
	l := ssologic.NewAuthorizeLogic(ctx, s.svcCtx)
	return l.Authorize(in)
}

func (s *SsoServer) Exchange(ctx context.Context, in *apollo.SSOExchangeReq) (*apollo.SSOSessionResp, error) {
	l := ssologic.NewExchangeLogic(ctx, s.svcCtx)
	return l.Exchange(in)
}

func (s *SsoServer) Introspect(ctx context.Context, in *apollo.SSOTokenReq) (*apollo.SSOSessionResp, error) {
	l := ssologic.NewIntrospectLogic(ctx, s.svcCtx)
	return l.Introspect(in)
}

func (s *SsoServer) Revoke(ctx context.Context, in *apollo.SSOTokenReq) (*apollo.Empty, error) {
	l := ssologic.NewRevokeLogic(ctx, s.svcCtx)
	return l.Revoke(in)
}
