// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v3.19.4
// source: jquantum-rpc.proto

package jquantum

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	_ "google.golang.org/protobuf/types/known/emptypb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Job
// ========== 任务流程 ==========
type SubmitReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        int64                  `protobuf:"varint,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Thread        []byte                 `protobuf:"bytes,2,opt,name=thread,proto3" json:"thread,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SubmitReq) Reset() {
	*x = SubmitReq{}
	mi := &file_jquantum_rpc_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SubmitReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SubmitReq) ProtoMessage() {}

func (x *SubmitReq) ProtoReflect() protoreflect.Message {
	mi := &file_jquantum_rpc_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SubmitReq.ProtoReflect.Descriptor instead.
func (*SubmitReq) Descriptor() ([]byte, []int) {
	return file_jquantum_rpc_proto_rawDescGZIP(), []int{0}
}

func (x *SubmitReq) GetUserId() int64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *SubmitReq) GetThread() []byte {
	if x != nil {
		return x.Thread
	}
	return nil
}

type SubmitResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	JobId         string                 `protobuf:"bytes,1,opt,name=job_id,json=jobId,proto3" json:"job_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SubmitResp) Reset() {
	*x = SubmitResp{}
	mi := &file_jquantum_rpc_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SubmitResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SubmitResp) ProtoMessage() {}

func (x *SubmitResp) ProtoReflect() protoreflect.Message {
	mi := &file_jquantum_rpc_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SubmitResp.ProtoReflect.Descriptor instead.
func (*SubmitResp) Descriptor() ([]byte, []int) {
	return file_jquantum_rpc_proto_rawDescGZIP(), []int{1}
}

func (x *SubmitResp) GetJobId() string {
	if x != nil {
		return x.JobId
	}
	return ""
}

type RetrieveResultReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        int64                  `protobuf:"varint,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	JobId         string                 `protobuf:"bytes,2,opt,name=job_id,json=jobId,proto3" json:"job_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RetrieveResultReq) Reset() {
	*x = RetrieveResultReq{}
	mi := &file_jquantum_rpc_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RetrieveResultReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RetrieveResultReq) ProtoMessage() {}

func (x *RetrieveResultReq) ProtoReflect() protoreflect.Message {
	mi := &file_jquantum_rpc_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RetrieveResultReq.ProtoReflect.Descriptor instead.
func (*RetrieveResultReq) Descriptor() ([]byte, []int) {
	return file_jquantum_rpc_proto_rawDescGZIP(), []int{2}
}

func (x *RetrieveResultReq) GetUserId() int64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *RetrieveResultReq) GetJobId() string {
	if x != nil {
		return x.JobId
	}
	return ""
}

type RetrieveResultResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Result        []byte                 `protobuf:"bytes,1,opt,name=result,proto3" json:"result,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RetrieveResultResp) Reset() {
	*x = RetrieveResultResp{}
	mi := &file_jquantum_rpc_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RetrieveResultResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RetrieveResultResp) ProtoMessage() {}

func (x *RetrieveResultResp) ProtoReflect() protoreflect.Message {
	mi := &file_jquantum_rpc_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RetrieveResultResp.ProtoReflect.Descriptor instead.
func (*RetrieveResultResp) Descriptor() ([]byte, []int) {
	return file_jquantum_rpc_proto_rawDescGZIP(), []int{3}
}

func (x *RetrieveResultResp) GetResult() []byte {
	if x != nil {
		return x.Result
	}
	return nil
}

type ValidateTokenReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        int64                  `protobuf:"varint,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	TokenId       int64                  `protobuf:"varint,2,opt,name=token_id,json=tokenId,proto3" json:"token_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ValidateTokenReq) Reset() {
	*x = ValidateTokenReq{}
	mi := &file_jquantum_rpc_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ValidateTokenReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ValidateTokenReq) ProtoMessage() {}

func (x *ValidateTokenReq) ProtoReflect() protoreflect.Message {
	mi := &file_jquantum_rpc_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ValidateTokenReq.ProtoReflect.Descriptor instead.
func (*ValidateTokenReq) Descriptor() ([]byte, []int) {
	return file_jquantum_rpc_proto_rawDescGZIP(), []int{4}
}

func (x *ValidateTokenReq) GetUserId() int64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *ValidateTokenReq) GetTokenId() int64 {
	if x != nil {
		return x.TokenId
	}
	return 0
}

type ValidateTokenResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Validated     bool                   `protobuf:"varint,1,opt,name=validated,proto3" json:"validated,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ValidateTokenResp) Reset() {
	*x = ValidateTokenResp{}
	mi := &file_jquantum_rpc_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ValidateTokenResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ValidateTokenResp) ProtoMessage() {}

func (x *ValidateTokenResp) ProtoReflect() protoreflect.Message {
	mi := &file_jquantum_rpc_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ValidateTokenResp.ProtoReflect.Descriptor instead.
func (*ValidateTokenResp) Descriptor() ([]byte, []int) {
	return file_jquantum_rpc_proto_rawDescGZIP(), []int{5}
}

func (x *ValidateTokenResp) GetValidated() bool {
	if x != nil {
		return x.Validated
	}
	return false
}

type ClusterInfoReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ClusterInfoReq) Reset() {
	*x = ClusterInfoReq{}
	mi := &file_jquantum_rpc_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ClusterInfoReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ClusterInfoReq) ProtoMessage() {}

func (x *ClusterInfoReq) ProtoReflect() protoreflect.Message {
	mi := &file_jquantum_rpc_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ClusterInfoReq.ProtoReflect.Descriptor instead.
func (*ClusterInfoReq) Descriptor() ([]byte, []int) {
	return file_jquantum_rpc_proto_rawDescGZIP(), []int{6}
}

type ClusterInfoResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TotalCPU      int64                  `protobuf:"varint,1,opt,name=totalCPU,proto3" json:"totalCPU,omitempty"`
	TotalMem      int64                  `protobuf:"varint,2,opt,name=totalMem,proto3" json:"totalMem,omitempty"`
	MaxQubits     int64                  `protobuf:"varint,3,opt,name=max_qubits,json=maxQubits,proto3" json:"max_qubits,omitempty"`
	Nodes         int64                  `protobuf:"varint,4,opt,name=nodes,proto3" json:"nodes,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ClusterInfoResp) Reset() {
	*x = ClusterInfoResp{}
	mi := &file_jquantum_rpc_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ClusterInfoResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ClusterInfoResp) ProtoMessage() {}

func (x *ClusterInfoResp) ProtoReflect() protoreflect.Message {
	mi := &file_jquantum_rpc_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ClusterInfoResp.ProtoReflect.Descriptor instead.
func (*ClusterInfoResp) Descriptor() ([]byte, []int) {
	return file_jquantum_rpc_proto_rawDescGZIP(), []int{7}
}

func (x *ClusterInfoResp) GetTotalCPU() int64 {
	if x != nil {
		return x.TotalCPU
	}
	return 0
}

func (x *ClusterInfoResp) GetTotalMem() int64 {
	if x != nil {
		return x.TotalMem
	}
	return 0
}

func (x *ClusterInfoResp) GetMaxQubits() int64 {
	if x != nil {
		return x.MaxQubits
	}
	return 0
}

func (x *ClusterInfoResp) GetNodes() int64 {
	if x != nil {
		return x.Nodes
	}
	return 0
}

var File_jquantum_rpc_proto protoreflect.FileDescriptor

const file_jquantum_rpc_proto_rawDesc = "" +
	"\n" +
	"\x12jquantum-rpc.proto\x12\bjquantum\x1a\x1bgoogle/protobuf/empty.proto\"<\n" +
	"\tSubmitReq\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\x03R\x06userId\x12\x16\n" +
	"\x06thread\x18\x02 \x01(\fR\x06thread\"#\n" +
	"\n" +
	"SubmitResp\x12\x15\n" +
	"\x06job_id\x18\x01 \x01(\tR\x05jobId\"C\n" +
	"\x11RetrieveResultReq\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\x03R\x06userId\x12\x15\n" +
	"\x06job_id\x18\x02 \x01(\tR\x05jobId\",\n" +
	"\x12RetrieveResultResp\x12\x16\n" +
	"\x06result\x18\x01 \x01(\fR\x06result\"F\n" +
	"\x10ValidateTokenReq\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\x03R\x06userId\x12\x19\n" +
	"\btoken_id\x18\x02 \x01(\x03R\atokenId\"1\n" +
	"\x11ValidateTokenResp\x12\x1c\n" +
	"\tvalidated\x18\x01 \x01(\bR\tvalidated\"\x10\n" +
	"\x0eClusterInfoReq\"~\n" +
	"\x0fClusterInfoResp\x12\x1a\n" +
	"\btotalCPU\x18\x01 \x01(\x03R\btotalCPU\x12\x1a\n" +
	"\btotalMem\x18\x02 \x01(\x03R\btotalMem\x12\x1d\n" +
	"\n" +
	"max_qubits\x18\x03 \x01(\x03R\tmaxQubits\x12\x14\n" +
	"\x05nodes\x18\x04 \x01(\x03R\x05nodes2\x9a\x02\n" +
	"\bJQuantum\x123\n" +
	"\x06Submit\x12\x13.jquantum.SubmitReq\x1a\x14.jquantum.SubmitResp\x12K\n" +
	"\x0eRetrieveResult\x12\x1b.jquantum.RetrieveResultReq\x1a\x1c.jquantum.RetrieveResultResp\x12H\n" +
	"\rValidateToken\x12\x1a.jquantum.ValidateTokenReq\x1a\x1b.jquantum.ValidateTokenResp\x12B\n" +
	"\vClusterInfo\x12\x18.jquantum.ClusterInfoReq\x1a\x19.jquantum.ClusterInfoRespB\fZ\n" +
	"./jquantumb\x06proto3"

var (
	file_jquantum_rpc_proto_rawDescOnce sync.Once
	file_jquantum_rpc_proto_rawDescData []byte
)

func file_jquantum_rpc_proto_rawDescGZIP() []byte {
	file_jquantum_rpc_proto_rawDescOnce.Do(func() {
		file_jquantum_rpc_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_jquantum_rpc_proto_rawDesc), len(file_jquantum_rpc_proto_rawDesc)))
	})
	return file_jquantum_rpc_proto_rawDescData
}

var file_jquantum_rpc_proto_msgTypes = make([]protoimpl.MessageInfo, 8)
var file_jquantum_rpc_proto_goTypes = []any{
	(*SubmitReq)(nil),          // 0: jquantum.SubmitReq
	(*SubmitResp)(nil),         // 1: jquantum.SubmitResp
	(*RetrieveResultReq)(nil),  // 2: jquantum.RetrieveResultReq
	(*RetrieveResultResp)(nil), // 3: jquantum.RetrieveResultResp
	(*ValidateTokenReq)(nil),   // 4: jquantum.ValidateTokenReq
	(*ValidateTokenResp)(nil),  // 5: jquantum.ValidateTokenResp
	(*ClusterInfoReq)(nil),     // 6: jquantum.ClusterInfoReq
	(*ClusterInfoResp)(nil),    // 7: jquantum.ClusterInfoResp
}
var file_jquantum_rpc_proto_depIdxs = []int32{
	0, // 0: jquantum.JQuantum.Submit:input_type -> jquantum.SubmitReq
	2, // 1: jquantum.JQuantum.RetrieveResult:input_type -> jquantum.RetrieveResultReq
	4, // 2: jquantum.JQuantum.ValidateToken:input_type -> jquantum.ValidateTokenReq
	6, // 3: jquantum.JQuantum.ClusterInfo:input_type -> jquantum.ClusterInfoReq
	1, // 4: jquantum.JQuantum.Submit:output_type -> jquantum.SubmitResp
	3, // 5: jquantum.JQuantum.RetrieveResult:output_type -> jquantum.RetrieveResultResp
	5, // 6: jquantum.JQuantum.ValidateToken:output_type -> jquantum.ValidateTokenResp
	7, // 7: jquantum.JQuantum.ClusterInfo:output_type -> jquantum.ClusterInfoResp
	4, // [4:8] is the sub-list for method output_type
	0, // [0:4] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_jquantum_rpc_proto_init() }
func file_jquantum_rpc_proto_init() {
	if File_jquantum_rpc_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_jquantum_rpc_proto_rawDesc), len(file_jquantum_rpc_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   8,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_jquantum_rpc_proto_goTypes,
		DependencyIndexes: file_jquantum_rpc_proto_depIdxs,
		MessageInfos:      file_jquantum_rpc_proto_msgTypes,
	}.Build()
	File_jquantum_rpc_proto = out.File
	file_jquantum_rpc_proto_goTypes = nil
	file_jquantum_rpc_proto_depIdxs = nil
}
