// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v3.19.4
// source: jquantum-rpc.proto

package jquantum

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	JQuantum_Submit_FullMethodName = "/apollo.JQuantum/Submit"
)

// JQuantumClient is the client API for JQuantum service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// ================= 计算任务定义 =================
type JQuantumClient interface {
	// Submit 提交任务
	Submit(ctx context.Context, in *SubmitReq, opts ...grpc.CallOption) (*SubmitResp, error)
}

type jQuantumClient struct {
	cc grpc.ClientConnInterface
}

func NewJQuantumClient(cc grpc.ClientConnInterface) JQuantumClient {
	return &jQuantumClient{cc}
}

func (c *jQuantumClient) Submit(ctx context.Context, in *SubmitReq, opts ...grpc.CallOption) (*SubmitResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SubmitResp)
	err := c.cc.Invoke(ctx, JQuantum_Submit_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// JQuantumServer is the server API for JQuantum service.
// All implementations must embed UnimplementedJQuantumServer
// for forward compatibility.
//
// ================= 计算任务定义 =================
type JQuantumServer interface {
	// Submit 提交任务
	Submit(context.Context, *SubmitReq) (*SubmitResp, error)
	mustEmbedUnimplementedJQuantumServer()
}

// UnimplementedJQuantumServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedJQuantumServer struct{}

func (UnimplementedJQuantumServer) Submit(context.Context, *SubmitReq) (*SubmitResp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Submit not implemented")
}
func (UnimplementedJQuantumServer) mustEmbedUnimplementedJQuantumServer() {}
func (UnimplementedJQuantumServer) testEmbeddedByValue()                  {}

// UnsafeJQuantumServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to JQuantumServer will
// result in compilation errors.
type UnsafeJQuantumServer interface {
	mustEmbedUnimplementedJQuantumServer()
}

func RegisterJQuantumServer(s grpc.ServiceRegistrar, srv JQuantumServer) {
	// If the following call pancis, it indicates UnimplementedJQuantumServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&JQuantum_ServiceDesc, srv)
}

func _JQuantum_Submit_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SubmitReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(JQuantumServer).Submit(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: JQuantum_Submit_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(JQuantumServer).Submit(ctx, req.(*SubmitReq))
	}
	return interceptor(ctx, in, info, handler)
}

// JQuantum_ServiceDesc is the grpc.ServiceDesc for JQuantum service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var JQuantum_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "apollo.JQuantum",
	HandlerType: (*JQuantumServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Submit",
			Handler:    _JQuantum_Submit_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "jquantum-rpc.proto",
}
