// Code generated by goctl. DO NOT EDIT.
// goctl 1.9.0
// Source: jquantum-rpc.proto

package server

import (
	"context"

	"jian-unified-system/jquantum/jquantum-rpc/internal/logic/jquantum"
	"jian-unified-system/jquantum/jquantum-rpc/internal/svc"
	"jian-unified-system/jquantum/jquantum-rpc/jquantum"
)

type JQuantumServer struct {
	svcCtx *svc.ServiceContext
	jquantum.UnimplementedJQuantumServer
}

func NewJQuantumServer(svcCtx *svc.ServiceContext) *JQuantumServer {
	return &JQuantumServer{
		svcCtx: svcCtx,
	}
}

// Submit 提交任务
func (s *JQuantumServer) Submit(ctx context.Context, in *jquantum.SubmitReq) (*jquantum.SubmitResp, error) {
	l := jquantumlogic.NewSubmitLogic(ctx, s.svcCtx)
	return l.Submit(in)
}

// RetrieveResult 获取计算任务结果
func (s *JQuantumServer) RetrieveResult(ctx context.Context, in *jquantum.RetrieveResultReq) (*jquantum.RetrieveResultResp, error) {
	l := jquantumlogic.NewRetrieveResultLogic(ctx, s.svcCtx)
	return l.RetrieveResult(in)
}
