// Framework generated by goctl 1.9.2; application adapter implemented after generation.
package healthlogic

import (
	"context"
	"jian-unified-system/hephaestus/hephaestus-rpc/income"
	"jian-unified-system/hephaestus/hephaestus-rpc/internal/svc"
	"jian-unified-system/hephaestus/internal/transport"
)

type HealthLogic struct {
	ctx    context.Context
	svcCtx *svc.ServiceContext
}

func NewHealthLogic(ctx context.Context, svcCtx *svc.ServiceContext) *HealthLogic {
	return &HealthLogic{ctx, svcCtx}
}
func (l *HealthLogic) Health(in *income.HealthRequest) (*income.HealthResp, error) {
	if in.Input == nil {
		in.Input = &income.Empty{}
	}
	return &income.HealthResp{Status: "ready"}, transport.RPCError(l.svcCtx.Store.Health(l.ctx))
}
