// Code generated by goctl. DO NOT EDIT.
// goctl 1.9.2
// Source: hephaestus.proto

package reporting

import (
	"context"

	"jian-unified-system/hephaestus/hephaestus-rpc/income"

	"github.com/zeromicro/go-zero/zrpc"
	"google.golang.org/grpc"
)

type (
	ArchiveRecordRequest = income.ArchiveRecordRequest
	Batch                = income.Batch
	BatchList            = income.BatchList
	BatchRows            = income.BatchRows
	BatchRowsReq         = income.BatchRowsReq
	CalendarRequest      = income.CalendarRequest
	CancelRequest        = income.CancelRequest
	Change               = income.Change
	ClearOverrideReq     = income.ClearOverrideReq
	ClearOverrideRequest = income.ClearOverrideRequest
	ColumnMapping        = income.ColumnMapping
	CommitReq            = income.CommitReq
	CommitRequest        = income.CommitRequest
	CreateRecordReq      = income.CreateRecordReq
	CreateRecordRequest  = income.CreateRecordRequest
	CreateSourceReq      = income.CreateSourceReq
	CreateSourceRequest  = income.CreateSourceRequest
	DeleteSourceRequest  = income.DeleteSourceRequest
	Empty                = income.Empty
	ExportRequest        = income.ExportRequest
	ExportResp           = income.ExportResp
	GetBatchRequest      = income.GetBatchRequest
	GetRecordRequest     = income.GetRecordRequest
	GoogleStageReq       = income.GoogleStageReq
	GoogleStageRequest   = income.GoogleStageRequest
	HealthRequest        = income.HealthRequest
	HealthResp           = income.HealthResp
	IDReq                = income.IDReq
	ImportRow            = income.ImportRow
	IncomeSummary        = income.IncomeSummary
	ListBatchesRequest   = income.ListBatchesRequest
	ListRecordsRequest   = income.ListRecordsRequest
	ListRevisionsRequest = income.ListRevisionsRequest
	ListRowsRequest      = income.ListRowsRequest
	ListSourcesRequest   = income.ListSourcesRequest
	LogoutRequest        = income.LogoutRequest
	MappingReq           = income.MappingReq
	Period               = income.Period
	PeriodList           = income.PeriodList
	PreviewRequest       = income.PreviewRequest
	QueryReq             = income.QueryReq
	ReadSheetRequest     = income.ReadSheetRequest
	Record               = income.Record
	RecordData           = income.RecordData
	RecordList           = income.RecordList
	RestoreRecordRequest = income.RestoreRecordRequest
	Revision             = income.Revision
	RevisionList         = income.RevisionList
	RowDecision          = income.RowDecision
	SeriesRequest        = income.SeriesRequest
	SessionRequest       = income.SessionRequest
	SessionResp          = income.SessionResp
	SheetData            = income.SheetData
	SheetReq             = income.SheetReq
	SheetRow             = income.SheetRow
	Source               = income.Source
	SourceList           = income.SourceList
	StageReq             = income.StageReq
	StageRequest         = income.StageRequest
	SummaryRequest       = income.SummaryRequest
	TrashBatchReq        = income.TrashBatchReq
	TrashBatchRequest    = income.TrashBatchRequest
	UpdateRecordReq      = income.UpdateRecordReq
	UpdateRecordRequest  = income.UpdateRecordRequest

	Reporting interface {
		Summary(ctx context.Context, in *SummaryRequest, opts ...grpc.CallOption) (*IncomeSummary, error)
		Calendar(ctx context.Context, in *CalendarRequest, opts ...grpc.CallOption) (*PeriodList, error)
		Series(ctx context.Context, in *SeriesRequest, opts ...grpc.CallOption) (*PeriodList, error)
		Export(ctx context.Context, in *ExportRequest, opts ...grpc.CallOption) (*ExportResp, error)
	}

	defaultReporting struct {
		cli zrpc.Client
	}
)

func NewReporting(cli zrpc.Client) Reporting {
	return &defaultReporting{
		cli: cli,
	}
}

func (m *defaultReporting) Summary(ctx context.Context, in *SummaryRequest, opts ...grpc.CallOption) (*IncomeSummary, error) {
	client := income.NewReportingClient(m.cli.Conn())
	return client.Summary(ctx, in, opts...)
}

func (m *defaultReporting) Calendar(ctx context.Context, in *CalendarRequest, opts ...grpc.CallOption) (*PeriodList, error) {
	client := income.NewReportingClient(m.cli.Conn())
	return client.Calendar(ctx, in, opts...)
}

func (m *defaultReporting) Series(ctx context.Context, in *SeriesRequest, opts ...grpc.CallOption) (*PeriodList, error) {
	client := income.NewReportingClient(m.cli.Conn())
	return client.Series(ctx, in, opts...)
}

func (m *defaultReporting) Export(ctx context.Context, in *ExportRequest, opts ...grpc.CallOption) (*ExportResp, error) {
	client := income.NewReportingClient(m.cli.Conn())
	return client.Export(ctx, in, opts...)
}
