// Framework generated by goctl 1.9.2; application adapter implemented after generation.
package reportinglogic

import (
	"context"
	"jian-unified-system/hephaestus/hephaestus-rpc/income"
	"jian-unified-system/hephaestus/hephaestus-rpc/internal/adapter"
	"jian-unified-system/hephaestus/hephaestus-rpc/internal/svc"
	"jian-unified-system/hephaestus/internal/transport"
)

type ExportLogic struct {
	ctx    context.Context
	svcCtx *svc.ServiceContext
}

func NewExportLogic(ctx context.Context, svcCtx *svc.ServiceContext) *ExportLogic {
	return &ExportLogic{ctx, svcCtx}
}
func (l *ExportLogic) Export(in *income.ExportRequest) (*income.ExportResp, error) {
	if in.Input == nil {
		in.Input = &income.QueryReq{}
	}
	if e := adapter.Authorize(l.ctx, l.svcCtx.App, in.OwnerId, in.SessionToken); e != nil {
		return nil, transport.RPCError(e)
	}
	v, e := l.svcCtx.App.Export(l.ctx, in.OwnerId, adapter.Filter(in.Input))
	return transport.Result[income.ExportResp](map[string]any{"content": v}, e)
}
