// Framework generated by goctl 1.9.2; application adapter implemented after generation.
package reportinglogic

import (
	"context"
	"jian-unified-system/hephaestus/hephaestus-rpc/income"
	"jian-unified-system/hephaestus/hephaestus-rpc/internal/adapter"
	"jian-unified-system/hephaestus/hephaestus-rpc/internal/svc"
	"jian-unified-system/hephaestus/internal/transport"
)

type SeriesLogic struct {
	ctx    context.Context
	svcCtx *svc.ServiceContext
}

func NewSeriesLogic(ctx context.Context, svcCtx *svc.ServiceContext) *SeriesLogic {
	return &SeriesLogic{ctx, svcCtx}
}
func (l *SeriesLogic) Series(in *income.SeriesRequest) (*income.PeriodList, error) {
	if in.Input == nil {
		in.Input = &income.QueryReq{}
	}
	if e := adapter.Authorize(l.ctx, l.svcCtx.App, in.OwnerId, in.SessionToken); e != nil {
		return nil, transport.RPCError(e)
	}
	v, e := l.svcCtx.App.Periods(l.ctx, in.OwnerId, adapter.Filter(in.Input), false)
	return transport.Result[income.PeriodList](v, e)
}
