// Code generated by goctl. DO NOT EDIT.
// goctl 1.9.2
// Source: hephaestus.proto

package server

import (
	"context"

	"jian-unified-system/hephaestus/hephaestus-rpc/income"
	"jian-unified-system/hephaestus/hephaestus-rpc/internal/logic/records"
	"jian-unified-system/hephaestus/hephaestus-rpc/internal/svc"
)

type RecordsServer struct {
	svcCtx *svc.ServiceContext
	income.UnimplementedRecordsServer
}

func NewRecordsServer(svcCtx *svc.ServiceContext) *RecordsServer {
	return &RecordsServer{
		svcCtx: svcCtx,
	}
}

func (s *RecordsServer) CreateRecord(ctx context.Context, in *income.CreateRecordRequest) (*income.Record, error) {
	l := recordslogic.NewCreateRecordLogic(ctx, s.svcCtx)
	return l.CreateRecord(in)
}

func (s *RecordsServer) ListRecords(ctx context.Context, in *income.ListRecordsRequest) (*income.RecordList, error) {
	l := recordslogic.NewListRecordsLogic(ctx, s.svcCtx)
	return l.ListRecords(in)
}

func (s *RecordsServer) GetRecord(ctx context.Context, in *income.GetRecordRequest) (*income.Record, error) {
	l := recordslogic.NewGetRecordLogic(ctx, s.svcCtx)
	return l.GetRecord(in)
}

func (s *RecordsServer) UpdateRecord(ctx context.Context, in *income.UpdateRecordRequest) (*income.Record, error) {
	l := recordslogic.NewUpdateRecordLogic(ctx, s.svcCtx)
	return l.UpdateRecord(in)
}

func (s *RecordsServer) ArchiveRecord(ctx context.Context, in *income.ArchiveRecordRequest) (*income.Record, error) {
	l := recordslogic.NewArchiveRecordLogic(ctx, s.svcCtx)
	return l.ArchiveRecord(in)
}

func (s *RecordsServer) RestoreRecord(ctx context.Context, in *income.RestoreRecordRequest) (*income.Record, error) {
	l := recordslogic.NewRestoreRecordLogic(ctx, s.svcCtx)
	return l.RestoreRecord(in)
}

func (s *RecordsServer) ClearOverride(ctx context.Context, in *income.ClearOverrideRequest) (*income.Record, error) {
	l := recordslogic.NewClearOverrideLogic(ctx, s.svcCtx)
	return l.ClearOverride(in)
}

func (s *RecordsServer) ListRevisions(ctx context.Context, in *income.ListRevisionsRequest) (*income.RevisionList, error) {
	l := recordslogic.NewListRevisionsLogic(ctx, s.svcCtx)
	return l.ListRevisions(in)
}
