// Code generated by goctl. DO NOT EDIT.
// goctl 1.8.5
// Source: jquantum-rpc.proto

package server

import (
	"context"

	"jian-unified-system/jquantum/jquantum-rpc/internal/logic/job"
	"jian-unified-system/jquantum/jquantum-rpc/internal/svc"
	"jian-unified-system/jquantum/jquantum-rpc/jquantum"
)

type JobServer struct {
	svcCtx *svc.ServiceContext
	jquantum.UnimplementedJobServer
}

func NewJobServer(svcCtx *svc.ServiceContext) *JobServer {
	return &JobServer{
		svcCtx: svcCtx,
	}
}

// 注册
func (s *JobServer) Submit(ctx context.Context, in *jquantum.Empty) (*jquantum.Empty, error) {
	l := joblogic.NewSubmitLogic(ctx, s.svcCtx)
	return l.Submit(in)
}
