// Code generated by goctl. DO NOT EDIT.
// goctl 1.8.5

package handler

import (
	"net/http"

	passkeys "jian-unified-system/apollo/apollo-api/internal/handler/passkeys"
	"jian-unified-system/apollo/apollo-api/internal/svc"

	"github.com/zeromicro/go-zero/rest"
)

func RegisterHandlers(server *rest.Server, serverCtx *svc.ServiceContext) {
	server.AddRoutes(
		[]rest.Route{
			{
				Method:  http.MethodPost,
				Path:    "/login/finish",
				Handler: passkeys.LoginFinishHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/login/start",
				Handler: passkeys.LoginStartHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/registration/finish",
				Handler: passkeys.RegFinishHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/registration/start",
				Handler: passkeys.RegStartHandler(serverCtx),
			},
		},
		rest.WithPrefix("/v1/passkeys"),
	)
}
