// Code generated by goctl. DO NOT EDIT.
// goctl 1.8.5

package handler

import (
	"net/http"

	account "jian-unified-system/apollo/apollo-api/internal/handler/account"
	passkeys "jian-unified-system/apollo/apollo-api/internal/handler/passkeys"
	"jian-unified-system/apollo/apollo-api/internal/svc"

	"github.com/zeromicro/go-zero/rest"
)

func RegisterHandlers(server *rest.Server, serverCtx *svc.ServiceContext) {
	server.AddRoutes(
		[]rest.Route{
			{
				Method:  http.MethodPost,
				Path:    "/login",
				Handler: account.LoginHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/registration",
				Handler: account.RegHandler(serverCtx),
			},
		},
		rest.WithPrefix("/v1/account"),
	)

	server.AddRoutes(
		rest.WithMiddlewares(
			[]rest.Middleware{serverCtx.JWTVerifyAgentMiddleware.Handle},
			[]rest.Route{
				{
					Method:  http.MethodPost,
					Path:    "/VerifyToken",
					Handler: account.VerifyTokenHandler(serverCtx),
				},
			}...,
		),
		rest.WithJwt(serverCtx.Config.Auth.AccessSecret),
		rest.WithPrefix("/v1/account"),
	)

	server.AddRoutes(
		[]rest.Route{
			{
				Method:  http.MethodPost,
				Path:    "/login/finish",
				Handler: passkeys.PasskeysLoginFinishHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/login/start",
				Handler: passkeys.PasskeysLoginStartHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/registration/finish",
				Handler: passkeys.PasskeysRegFinishHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/registration/start",
				Handler: passkeys.PasskeysRegStartHandler(serverCtx),
			},
		},
		rest.WithPrefix("/v1/passkeys"),
	)
}
