// Framework generated by goctl 1.9.2; application adapter implemented after generation.
package importslogic

import (
	"context"
	"jian-unified-system/hephaestus/hephaestus-rpc/income"
	"jian-unified-system/hephaestus/hephaestus-rpc/internal/adapter"
	"jian-unified-system/hephaestus/hephaestus-rpc/internal/svc"
	"jian-unified-system/hephaestus/internal/transport"
)

type CommitLogic struct {
	ctx    context.Context
	svcCtx *svc.ServiceContext
}

func NewCommitLogic(ctx context.Context, svcCtx *svc.ServiceContext) *CommitLogic {
	return &CommitLogic{ctx, svcCtx}
}
func (l *CommitLogic) Commit(in *income.CommitRequest) (*income.Batch, error) {
	if in.Input == nil {
		in.Input = &income.CommitReq{}
	}
	if e := adapter.Authorize(l.ctx, l.svcCtx.App, in.OwnerId, in.SessionToken); e != nil {
		return nil, transport.RPCError(e)
	}
	id, e := adapter.IntID(in.Input.Id)
	if e != nil {
		return nil, transport.RPCError(e)
	}
	v, e := l.svcCtx.App.Commit(l.ctx, in.OwnerId, id, in.ExpectedVersion, in.IdempotencyKey, in.Input.SelectionHash)
	return transport.Result[income.Batch](v, e)
}
