// Framework generated by goctl 1.9.2; application adapter implemented after generation.
package importslogic

import (
	"context"
	"jian-unified-system/hephaestus/hephaestus-rpc/income"
	"jian-unified-system/hephaestus/hephaestus-rpc/internal/adapter"
	"jian-unified-system/hephaestus/hephaestus-rpc/internal/svc"
	"jian-unified-system/hephaestus/internal/transport"
)

type ListSourcesLogic struct {
	ctx    context.Context
	svcCtx *svc.ServiceContext
}

func NewListSourcesLogic(ctx context.Context, svcCtx *svc.ServiceContext) *ListSourcesLogic {
	return &ListSourcesLogic{ctx, svcCtx}
}
func (l *ListSourcesLogic) ListSources(in *income.ListSourcesRequest) (*income.SourceList, error) {
	if in.Input == nil {
		in.Input = &income.Empty{}
	}
	if e := adapter.Authorize(l.ctx, l.svcCtx.App, in.OwnerId, in.SessionToken); e != nil {
		return nil, transport.RPCError(e)
	}
	v, e := l.svcCtx.App.Repo.Sources(l.ctx, in.OwnerId)
	return transport.Result[income.SourceList](map[string]any{"items": v}, e)
}
