// Framework generated by goctl 1.9.2; application adapter implemented after generation.
package importslogic

import (
	"context"
	"jian-unified-system/hephaestus/hephaestus-rpc/income"
	"jian-unified-system/hephaestus/hephaestus-rpc/internal/adapter"
	d "jian-unified-system/hephaestus/hephaestus-rpc/internal/domain"
	"jian-unified-system/hephaestus/hephaestus-rpc/internal/svc"
	"jian-unified-system/hephaestus/internal/transport"
	"strconv"
)

type ListRowsLogic struct {
	ctx    context.Context
	svcCtx *svc.ServiceContext
}

func NewListRowsLogic(ctx context.Context, svcCtx *svc.ServiceContext) *ListRowsLogic {
	return &ListRowsLogic{ctx, svcCtx}
}
func (l *ListRowsLogic) ListRows(in *income.ListRowsRequest) (*income.BatchRows, error) {
	if in.Input == nil {
		in.Input = &income.BatchRowsReq{}
	}
	if e := adapter.Authorize(l.ctx, l.svcCtx.App, in.OwnerId, in.SessionToken); e != nil {
		return nil, transport.RPCError(e)
	}
	id, e := adapter.IntID(in.Input.Id)
	if e != nil {
		return nil, transport.RPCError(e)
	}
	b, e := l.svcCtx.App.GetBatch(l.ctx, in.OwnerId, id)
	if e != nil {
		return nil, transport.RPCError(e)
	}
	offset, e := adapter.Offset(in.Input.Cursor)
	if e != nil {
		return nil, transport.RPCError(e)
	}
	limit := in.Input.Limit
	if limit == 0 {
		limit = 50
	}
	if limit < 1 || limit > 200 || offset > len(b.Rows) {
		return nil, transport.RPCError(d.Invalid("invalid row page"))
	}
	end := offset + int(limit)
	next := ""
	if end < len(b.Rows) {
		next = strconv.Itoa(end)
	} else {
		end = len(b.Rows)
	}
	return transport.Result[income.BatchRows](map[string]any{"items": b.Rows[offset:end], "next_cursor": next}, nil)
}
