// Framework generated by goctl 1.9.2; application adapter implemented after generation.
package importslogic

import (
	"context"
	"jian-unified-system/hephaestus/hephaestus-rpc/income"
	"jian-unified-system/hephaestus/hephaestus-rpc/internal/adapter"
	"jian-unified-system/hephaestus/hephaestus-rpc/internal/svc"
	"jian-unified-system/hephaestus/internal/transport"
)

type ListBatchesLogic struct {
	ctx    context.Context
	svcCtx *svc.ServiceContext
}

func NewListBatchesLogic(ctx context.Context, svcCtx *svc.ServiceContext) *ListBatchesLogic {
	return &ListBatchesLogic{ctx, svcCtx}
}
func (l *ListBatchesLogic) ListBatches(in *income.ListBatchesRequest) (*income.BatchList, error) {
	if in.Input == nil {
		in.Input = &income.Empty{}
	}
	if e := adapter.Authorize(l.ctx, l.svcCtx.App, in.OwnerId, in.SessionToken); e != nil {
		return nil, transport.RPCError(e)
	}
	v, e := l.svcCtx.App.Repo.Batches(l.ctx, in.OwnerId)
	return transport.Result[income.BatchList](map[string]any{"items": v}, e)
}
