// Framework generated by goctl 1.9.2; application adapter implemented after generation.
package importslogic

import (
	"context"
	"jian-unified-system/hephaestus/hephaestus-rpc/income"
	"jian-unified-system/hephaestus/hephaestus-rpc/internal/adapter"
	a "jian-unified-system/hephaestus/hephaestus-rpc/internal/application"
	d "jian-unified-system/hephaestus/hephaestus-rpc/internal/domain"
	"jian-unified-system/hephaestus/hephaestus-rpc/internal/svc"
	"jian-unified-system/hephaestus/internal/transport"
)

type PreviewLogic struct {
	ctx    context.Context
	svcCtx *svc.ServiceContext
}

func NewPreviewLogic(ctx context.Context, svcCtx *svc.ServiceContext) *PreviewLogic {
	return &PreviewLogic{ctx, svcCtx}
}
func (l *PreviewLogic) Preview(in *income.PreviewRequest) (*income.Batch, error) {
	if in.Input == nil {
		in.Input = &income.MappingReq{}
	}
	if e := adapter.Authorize(l.ctx, l.svcCtx.App, in.OwnerId, in.SessionToken); e != nil {
		return nil, transport.RPCError(e)
	}
	id, e := adapter.IntID(in.Input.Id)
	if e != nil {
		return nil, transport.RPCError(e)
	}
	mapping, e := transport.Convert[a.Mapping](in.Input)
	if e != nil {
		return nil, transport.RPCError(d.Invalid("invalid mapping"))
	}
	v, e := l.svcCtx.App.Preview(l.ctx, in.OwnerId, id, in.ExpectedVersion, in.IdempotencyKey, *mapping)
	return transport.Result[income.Batch](v, e)
}
