name: Build and Push Docker Image by Tag

on:
  push:
    tags:
      - "**-v*.*.*"

jobs:
  docker:
    runs-on: ubuntu-latest

    steps:
      # 1 检出代码
      - name: Checkout repository
        uses: actions/checkout@v4

      # 2 解析 tag，得到子系统路径和版本号
      - name: Parse tag
        id: parse
        run: |
          RAW_TAG=${GITHUB_REF_NAME}
          SERVICE_PATH=${RAW_TAG%-v*}
          VERSION=v${RAW_TAG##*-v}
          SERVICE_NAME=$(basename $SERVICE_PATH)

          echo "RAW_TAG=$RAW_TAG"
          echo "SERVICE_PATH=$SERVICE_PATH"
          echo "SERVICE_NAME=$SERVICE_NAME"
          echo "VERSION=$VERSION"

          echo "SERVICE_PATH=$SERVICE_PATH" >> $GITHUB_ENV
          echo "SERVICE_NAME=$SERVICE_NAME" >> $GITHUB_ENV
          echo "VERSION=$VERSION" >> $GITHUB_ENV

      # 3 登录 DockerHub
      - name: Login to DockerHub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      # 4 Build Docker image
      - name: Build Docker image
        run: |
          IMAGE=${{ secrets.DOCKERHUB_USERNAME }}/$SERVICE_NAME
          echo "Building Docker image: $IMAGE:$VERSION and $IMAGE:latest"
          docker build \
            -f $SERVICE_PATH/deploy/Dockerfile \
            -t $IMAGE:latest \
            -t $IMAGE:$VERSION \
            .

      # 5 Push Docker image
      - name: Push Docker image
        run: |
          IMAGE=${{ secrets.DOCKERHUB_USERNAME }}/$SERVICE_NAME
          docker push $IMAGE:latest
          docker push $IMAGE:$VERSION
